import {WEAPONS,PASSIVES,HEROES,META,REGIONS,MILESTONES,byId,costOf,freshSave,ENEMIES,WEAPON_SLOTS,PASSIVE_SLOTS} from './data.js?v=7';
import {Game} from './engine.js?v=7';
import {Renderer,heroSprite,artReady} from './render.js?v=7';
const $=s=>document.querySelector(s),root=$('#app'),KEY='emberwake-save-v1';let save=freshSave(),storageOK=true;
try {const raw=localStorage.getItem(KEY);if(raw){let old=JSON.parse(raw);validateSave(old);save={...save,...old,settings:{...save.settings,...old.settings},stats:{...save.stats,...old.stats}}}}catch{storageOK=false;}
let game=null,renderer=null,page='camp',modal='',last=0,accumulator=0,saveClock=0,hudClock=0,input={x:0,y:0},stick=null,keys={},wake=null,audio=null,ending=false;
await artReady;
const portrait=Object.fromEntries(HEROES.map(h=>[h.id,heroSprite(h.color,h.id).toDataURL()]));
const time=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));storageOK=true;}catch{storageOK=false;toast('Saving is unavailable. Export a backup in Settings.');}}
function checkpoint(){if(game&&game.mode!=='ended')save.run=game.snapshot();persist();}
function sound(kind='tap'){if(!save.settings.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const n=audio.currentTime;const osc=audio.createOscillator(),gain=audio.createGain();osc.type=kind==='hurt'?'triangle':'sine';const f={tap:420,levelup:660,evolve:880,treasure:740,dash:240,hurt:95,heal:520}[kind]||400;osc.frequency.setValueAtTime(f,n);osc.frequency.exponentialRampToValueAtTime(kind==='hurt'?50:f*1.4,n+.13);gain.gain.setValueAtTime(.04,n);gain.gain.exponentialRampToValueAtTime(.001,n+.19);osc.connect(gain);gain.connect(audio.destination);osc.start(n);osc.stop(n+.2);}catch{}}
let toastTimer;function toast(text){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3500);}
function glyph(icon,color='var(--gold)'){return `<span class="glyph" style="--glyph:${color}">${icon}</span>`;}
function header(){return `<header class="topbar"><button class="wordmark" data-page="camp" aria-label="Emberwake camp">✦ <span>EMBERWAKE</span></button><nav aria-label="Camp navigation">${[['camp','Camp'],['forge','Upgrade'],['codex','Arsenal'],['journal','Milestones']].map(([id,label])=>`<button data-page="${id}" class="${page===id?'active':''}">${label}</button>`).join('')}</nav><div class="header-right"><span class="bank" aria-label="${save.gold} gold">◈ <b>${save.gold.toLocaleString()}</b></span><button class="icon-btn" data-action="settings" aria-label="Settings">⚙</button></div></header>`;}
function render(){game=null;renderer=null;ending=false;modal='';document.body.classList.remove('in-game');root.innerHTML=`<div class="camp-shell ${page==='camp'?'home':''}">${header()}${page==='camp'?camp():page==='forge'?forge():page==='codex'?codex():journal()}<div class="camp-footer"><span>${storageOK?'◆ Progress saved on this device':'Saving unavailable · use backup'}</span><button data-action="howto">How to play <span>?</span></button></div></div><div id="modal-host"></div>`;}
function camp(){const hero=HEROES.find(h=>h.id===save.hero),region=REGIONS.find(r=>r.id===save.region);return `<section class="camp-main"><div class="camp-intro"><div class="eyebrow"><span class="tiny-line"></span> A SURVIVAL ROGUELITE</div><h1>ONE MORE<br><em>DAWN.</em></h1><p>Stay until the darkness breaks.<br>A little stronger every time.</p><div class="run-record"><span>BEST RUN <b>${time(save.stats.bestTime)}</b></span><span>DAWNS REACHED <b>${save.stats.wins}</b></span></div></div><div class="expedition-panel"><div class="section-label">YOUR WAYFINDER</div><div class="hero-heading"><div><h2>${hero.name}</h2><span>${hero.title}</span></div><img class="hero-mini" src="${portrait[hero.id]}" alt="${hero.name}"></div><div class="hero-select" aria-label="Choose character">${HEROES.map(h=>`<button data-hero="${h.id}" class="${save.hero===h.id?'selected':''} ${save.heroes.includes(h.id)?'':'locked'}" aria-label="${h.name}${save.heroes.includes(h.id)?'':', unlock for '+h.cost+' gold'}"><img src="${portrait[h.id]}" alt=""><span>${h.name}</span>${save.heroes.includes(h.id)?'':`<small>◈ ${h.cost}</small>`}</button>`).join('')}</div><p class="hero-bonus">${hero.bonus}</p><label class="region-label" for="region">EXPEDITION</label><select id="region">${REGIONS.map(r=>`<option value="${r.id}" ${save.region===r.id?'selected':''} ${save.stats.wins<r.need?'disabled':''}>${r.name}${save.stats.wins<r.need?' · '+r.need+' wins to unlock':''}</option>`).join('')}</select><div class="region-info"><span>${region.tag}</span><span>30 MIN → ENDLESS</span></div><button class="primary launch" data-action="${save.run?'resume':'start'}"><span>${save.run?'Continue expedition':'Enter the wilds'}</span><span>↗</span></button>${save.run?`<button class="text-btn" data-action="bank-old">Finish saved run & keep gold</button>`:'<div class="launch-note">Auto-attack · Free revive · Keep your gold</div>'}</div></section>`;}
function forge(){return `<section class="page-content"><div class="page-heading"><div><div class="eyebrow">THE EMBER FORGE</div><h1>Stronger. Every run.</h1><p>Permanent upgrades for all four characters. Apply to new expeditions.</p></div><button class="secondary" data-action="respec" ${save.spent?'':'disabled'}>Respec free · ◈ ${save.spent}</button></div><div class="upgrade-grid">${META.map(u=>{const n=save.meta[u.id]||0,cost=costOf(u,n);return `<article class="meta-card">${glyph(u.icon)}<div class="meta-info"><h3>${u.name}</h3><p>${u.desc}</p><div class="ranks" aria-label="Rank ${n} of ${u.max}">${Array.from({length:u.max},(_,i)=>`<i class="${i<n?'filled':''}"></i>`).join('')}</div></div><button class="buy ${n>=u.max?'maxed':''}" data-buy="${u.id}" ${n>=u.max||save.gold<cost?'disabled':''}>${n>=u.max?'MAX':'◈ '+cost}</button></article>`}).join('')}</div><p class="footnote">First upgrades cost 30–70 gold. All gold is kept on defeat. Respec refunds every coin spent here.</p></section>`;}
function codex(){return `<section class="page-content"><div class="page-heading"><div><div class="eyebrow">BUILD SOMETHING UNREASONABLE</div><h1>Your arsenal.</h1><p>Carry 6 weapons + 6 skills. Choose from 16 weapons and 12 skills. Take weapons to rank 8. With a rank 2 partner, a treasure chest awakens their evolution.</p></div></div><div class="codex-grid">${WEAPONS.map(w=>`<article class="weapon-card">${glyph(w.icon,w.color)}<div><h3>${w.name}</h3><p>${w.desc}</p><small>${w.base}</small><div class="recipe"><span>${w.name} <b>8</b> + ${byId(w.pair).name} <b>2</b></span><strong>Treasure chest → ${w.evo}</strong><p>${w.evoDesc}</p></div></div></article>`).join('')}</div><h2 class="minor-heading">Supporting skills</h2><div class="passive-grid">${PASSIVES.map(p=>`<div>${glyph(p.icon,p.color)}<span><b>${p.name}</b><small>${p.desc}</small></span></div>`).join('')}</div></section>`;}
function journal(){return `<section class="page-content"><div class="page-heading"><div><div class="eyebrow">EVERY EXPEDITION COUNTS</div><h1>Leave your mark.</h1><p>Milestone gold is awarded automatically when your run ends.</p></div><span class="count-pill">${save.claimed.length} / ${MILESTONES.length} complete</span></div><div class="milestone-grid">${MILESTONES.map(m=>{let done=save.claimed.includes(m.id),v=Math.min(m.target,save.stats[m.stat]||0);return `<article class="milestone ${done?'done':''}"><div class="milestone-top"><h3>${done?'✓ ':''}${m.name}</h3><b>◈ ${m.reward}</b></div><p>${m.desc}</p><div class="progress"><i style="width:${v/m.target*100}%"></i></div><small>${done?'Completed':`${Math.floor(v).toLocaleString()} / ${m.target.toLocaleString()}`}</small></article>`}).join('')}</div>${save.history.length?`<h2 class="minor-heading">Recent expeditions</h2><div class="history">${save.history.slice(0,5).map(h=>`<div><span>${h.victory?'☀ Dawn reached':'✦ Returned to camp'}</span><span>${esc(h.hero)} · ${time(h.time)} · ${h.kills} defeated</span><b>+${h.gold} gold</b></div>`).join('')}</div>`:''}</section>`;}
function showModal(html,cls=''){modal=cls;$('#modal-host').innerHTML=`<div class="modal-backdrop"><section class="modal ${cls}" role="dialog" aria-modal="true" aria-label="${cls||'Game menu'}">${html}</section></div>`;for(const child of root.children)if(child.id!=='modal-host')child.inert=true;const b=$('#modal-host button');b?.focus();}
function closeModal(){modal='';$('#modal-host').innerHTML='';for(const child of root.children)child.inert=false;}
function settings(){showModal(`<div class="modal-heading"><h2>Make yourself at home.</h2><button class="icon-btn" data-action="close" aria-label="Close settings">×</button></div><label class="setting-row"><span>Sound effects</span><input type="checkbox" id="sound" ${save.settings.sound?'checked':''}></label><label class="setting-row"><span>Screen shake</span><input type="checkbox" id="shake" ${save.settings.shake?'checked':''}></label><label class="setting-row"><span>Weapon effect visibility</span><input type="range" id="fx" min="0.15" max="1" step="0.05" value="${save.settings.fx}" aria-label="Weapon effect visibility"></label><label class="setting-row"><span>Left thumbstick</span><select id="joystick"><option value="floating" ${save.settings.joystick==='floating'?'selected':''}>Starts where you touch</option><option value="fixed" ${save.settings.joystick==='fixed'?'selected':''}>Fixed bottom left</option></select></label><div class="save-info"><h3>Your progress stays here.</h3><p>Saved in this browser on this device. Export a backup before clearing browser data or moving phones. Imported saves replace your current progress.</p><div class="button-row"><button class="secondary" data-action="export">Export save</button><button class="secondary" data-action="import">Import save</button></div><input type="file" id="save-file" accept="application/json,.json" hidden></div><p class="footnote">For a full-screen iPhone experience: Safari → Share → Add to Home Screen. Turn your phone sideways.</p>`,'settings');}
function howto(){showModal(`<div class="modal-heading"><h2>A little light. A lot of trouble.</h2><button class="icon-btn" data-action="close" aria-label="Close instructions">×</button></div><div class="instructions"><p><b>1. Move, and let your weapons work.</b> Drag your left thumb anywhere on the battlefield. On a keyboard, use WASD or arrow keys.</p><p><b>2. Gather the glowing shards.</b> They grant experience. Each level gives you three upgrade choices. The game pauses while you pick.</p><p><b>3. Dash through danger.</b> Use the right-hand button, or Space. You cannot take damage during the dash. Move out of red warning circles before they erupt.</p><p><b>4. Build an evolution.</b> Upgrade a weapon to rank 8 and its matching skill to rank 2, then open a treasure chest. Carry up to six weapons and six skills. Recipes are always visible in your Arsenal.</p><p><b>5. Bring the gold home.</b> Survive 30 minutes to reach dawn, then keep fighting as long as you like. Defeats and early returns keep every coin. Spend it on permanent upgrades or new characters.</p><p class="hint">Green + heals you. A diamond pulls in experience. Bosses drop treasure chests with gold and 3 or 5 rewards. Ancients drop smaller chests. Gold caches grant coins and experience. Every run includes one free revive. Once your build is maxed, levels automatically grant 20 gold and 5 health without interrupting combat.</p></div><button class="primary" data-action="close">Got it. Let’s go.</button>`,'howto');}
async function requestWake(){try{wake=await navigator.wakeLock?.request('screen');}catch{}}
function start(resume=false){ending=false;page='camp';sound();game=new Game(save,event,resume?save.run:null);document.body.classList.add('in-game');root.innerHTML=`<div class="game-shell"><canvas id="arena" aria-label="Emberwake survival battlefield"></canvas><div class="hud"><div class="hud-left"><img src="${portrait[game.hero.id]}" alt=""><div><div class="health-label"><b>${game.hero.name}</b><span id="hp-label"></span></div><div class="health-track"><i id="hp-bar"></i></div></div><span id="level-label" class="level-badge">LV 1</span></div><div class="clock"><b id="timer">00:00</b><span id="phase-label">DAWN IN 30:00</span></div><div class="hud-right"><span>◈ <b id="run-gold">0</b></span><span class="kills">☠ <b id="kills">0</b></span><button class="icon-btn" data-action="pause" aria-label="Pause game">Ⅱ</button></div></div><div class="xp-track"><i id="xp-bar"></i></div><div id="event-banner" aria-live="polite"></div><div id="starter-hint">Drag left to move <span>·</span> Weapons fire automatically <span>·</span> Dash on the right</div><div class="loadout" id="loadout"></div><div id="joystick-base"><div id="joystick-knob"></div></div><button class="dash-button" id="dash" data-action="dash" aria-label="Dash"><strong>↗</strong><span>DASH</span></button><div class="desktop-hint">WASD move · SPACE dash · ESC pause</div><div class="rotate-note">↻ Turn your phone sideways for a wider view</div></div><div id="modal-host"></div>`;renderer=new Renderer($('#arena'));input={x:0,y:0};keys={};setupControls();requestWake();hud();loadout();checkpoint();if(game.mode==='chest')treasureUI();else if(game.mode==='levelup')levelup();else if(game.mode==='down')down();else if(resume){game.mode='paused';pauseUI();}last=performance.now();accumulator=0;}
function event(type,data){if(['levelup','evolve','dash','hurt','heal','treasure'].includes(type))sound(type);if(type==='levelup'){resetInput();levelup();checkpoint();}if(type==='evolve'){banner(`${data.weapon.evo} awakened`);toast(`${data.weapon.name} evolved into ${data.weapon.evo}!`);}if(type==='choose'){loadout();closeModal();checkpoint();}if(type==='warning')banner(data.text);if(type==='cache')banner('An ember cache appeared · Follow ▣');if(type==='treasure')banner('+25 gold · A surge of experience');if(type==='heal')banner('+30 health');if(type==='magnet')banner('All nearby shards are coming to you');if(type==='elite')banner('Ancient defeated · +18 gold · +15 health');if(type==='streak')banner(`${data.kills} shadows defeated`);if(type==='bossdown')banner('Guardian defeated · Collect its treasure chest');if(type==='dawn')banner('DAWN REACHED · Expedition complete! Keep fighting or bank your gold.');if(type==='chest'){resetInput();sound('treasure');loadout();treasureUI();checkpoint();}if(type==='down'){resetInput();checkpoint();down();}if(type==='revive'){closeModal();checkpoint();}if(type==='end')finish(data.victory);}
let bannerTimer;function banner(t){const e=$('#event-banner');if(!e)return;e.textContent=t;e.classList.add('visible');clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>e.classList.remove('visible'),3200);}
function loadout(){if(!game||!$('#loadout'))return;$('#loadout').innerHTML=Object.entries(game.skills).map(([id,n])=>{let s=byId(id);return `<button data-skill="${id}" title="${s.name} rank ${n}" aria-label="${s.name} rank ${n}"><span style="color:${s.color}">${s.icon}</span><small>${game.evolved.includes(id)?'★':n}</small></button>`}).join('');}
function upgradeDetail(id,n){const next=n+1;const details={spear:`${42+n*12} base damage · ${6+n} pierces`,scythe:`${28+n*8} base damage · ${next>=5?2:1} returning scythes`,mine:`${60+n*16} blast damage · ${65+next*6} radius`,venom:`${12+n*4} damage per tick · ${65+next*7} radius`,beam:`${46+n*14} base damage · ${440+n*12} reach`,wisp:`${20+n*6} base damage · ${2+Math.floor(n/2)} spirits`,axe:`${36+n*10} base damage · ${2+Math.floor(n/3)} axes`,tide:`${32+n*10} base damage · ${190+n*22} reach`};if(details[id])return details[id];if(id==='bolt')return `${Math.round(22*(1+n*.28))} base damage · ${1+Math.floor(next/2)} bolts`;if(id==='dagger')return `${Math.round(16*(1+n*.28))} base damage · ${3+Math.floor(next/2)} knives`;if(id==='chain')return `${Math.round(30*(1+n*.3))} base damage · ${next+2} jumps`;if(id==='orbit')return `${18+n*7} base damage · ${next+1} blades`;if(id==='nova')return `${Math.round(38*(1+n*.3))} base damage · ${105+n*16} radius`;if(id==='frost')return `${16+n*6} base damage · ${110+n*13} radius`;if(id==='flame')return `${36+n*12} base damage · ${150+n*13} reach`;return `${65+n*20} base damage · ${65+n*9} blast radius`;}
function levelup(){showModal(`<div class="levelup-title"><span class="eyebrow">LEVEL ${game.level} · TIME PAUSED</span><h2>Feed the fire.</h2><p>Choose one upgrade. Recent picks appear less often.</p></div><div class="choices">${game.choices.map(id=>{if(id==='healreward'||id==='goldreward')return `<button class="choice" data-choice="${id}">${glyph(id==='healreward'?'+':'◈')}<h3>${id==='healreward'?'Restore health':'Gold reserves'}</h3><p>${id==='healreward'?'Heal 40 health.':'Gain 20 gold to keep.'}</p></button>`;let s=byId(id),weapon=WEAPONS.some(w=>w.id===id),n=game.rank(id),partner=weapon?byId(s.pair):(WEAPONS.find(w=>w.pair===id&&game.rank(w.id)>0)||WEAPONS.find(w=>w.pair===id)),synergy=partner&&game.rank(partner.id)>0;return `<button class="choice ${synergy?'synergy':''}" data-choice="${id}" style="--choice:${s.color}"><div class="choice-top">${glyph(s.icon,s.color)}<span>${n?'RANK '+n+' → '+(n+1):'NEW '+(weapon?'WEAPON':'SKILL')}</span></div><h3>${s.name}</h3><p>${weapon?(n?s.upgrade:s.desc):s.desc}</p><div class="choice-detail">${weapon?(n?upgradeDetail(id,n):s.base):'Maximum rank 3'}</div><div class="choice-recipe">${synergy?'<b>✦ BUILD SYNERGY</b>':'EVOLUTION PARTNER'}<span>${partner.name} <small>${game.rank(partner.id)} / ${weapon?2:8}</small></span></div></button>`}).join('')}</div><div class="choice-footer"><span>${WEAPONS.filter(w=>game.rank(w.id)).length}/${WEAPON_SLOTS} weapons · ${PASSIVES.filter(w=>game.rank(w.id)).length}/${PASSIVE_SLOTS} skills</span><button class="secondary" data-action="reroll" ${game.rerolls?'':'disabled'}>⟳ Reroll (${game.rerolls})</button></div>`,'levelup');}
function treasureUI(){const chest=game.chestReward;if(!chest)return;showModal(`<div class="treasure-heading"><div class="eyebrow">${chest.boss?'GUARDIAN TREASURE':'ANCIENT TREASURE'} · TIME PAUSED</div><div class="treasure-art"></div><h2>${chest.rewards.length>=5?'A legendary haul.':'Fortune found you.'}</h2><div class="treasure-gold">+${chest.gold} <span>GOLD</span></div></div><div class="treasure-rewards">${chest.rewards.map((r,i)=>{const item=byId(r.id);return `<div class="treasure-reward ${r.evolved?'evolved':''}" style="--reveal:${i*90}ms">${glyph(item?.icon||'◈',item?.color)}<span><b>${r.evolved?item.evo:item?.name||'Gold reserves'}</b><small>${r.evolved?'EVOLUTION AWAKENED':item?'Rank '+r.rank+' / '+(WEAPONS.some(w=>w.id===r.id)?8:3):'+'+r.gold+' gold · Build fully upgraded'}</small></span></div>`;}).join('')}</div><button class="primary" data-action="close-chest">Keep fighting <span>↗</span></button><p class="hint">Rewards collected and saved. All gold is yours to keep.</p>`,'treasure');}
function pause(){if(!game||game.mode!=='playing')return;game.mode='paused';resetInput();checkpoint();pauseUI();}
function pauseUI(){showModal(`<div class="eyebrow">TAKE YOUR TIME</div><h2>The wild can wait.</h2><p>${time(game.time)} survived · Level ${game.level} · ${Math.floor(game.gold)} gold earned</p><button class="primary" data-action="unpause">Resume expedition <span>↗</span></button><div class="button-row"><button class="secondary" data-action="save-exit">Save & return to camp</button><button class="secondary" data-action="end-run">Finish & keep gold</button></div><p class="hint">Your run saves automatically. Switching apps pauses play.</p>`,'pause');}
function down(){showModal(`<div class="eyebrow">THE FIRE STILL BURNS</div><h2>${game.revives?'One more chance.':'Back to the embers.'}</h2><p>${time(game.time)} survived · ${game.kills} enemies defeated.<br>Your ${Math.floor(game.gold)} gold is safe.</p>${game.revives?'<button class="primary" data-action="revive">Rise again <span>FREE</span></button><p class="hint">Recover 60% health and gain 4 seconds of protection.</p>':''}<button class="secondary full" data-action="end-run">Return to camp & collect gold</button>`,'down');}
function finish(victory=false){if(ending)return;ending=true;resetInput();closeModal();const earned=Math.floor(game.gold)+(victory?100:0);save.gold+=earned;save.stats.runs++;save.stats.kills+=game.kills;save.stats.bestTime=Math.max(save.stats.bestTime,game.time);save.stats.bestLevel=Math.max(save.stats.bestLevel,game.level);save.stats.evolutions+=game.evolutionCount;if(victory)save.stats.wins++;const awarded=[];for(const m of MILESTONES)if(!save.claimed.includes(m.id)&&save.stats[m.stat]>=m.target){save.claimed.push(m.id);save.gold+=m.reward;awarded.push(m);}save.history.unshift({id:game.bankId,hero:game.hero.name,time:game.time,kills:game.kills,gold:earned,victory});save.history=save.history.slice(0,20);save.run=null;persist();wake?.release().catch(()=>{});showModal(`<div class="eyebrow">${victory?'YOU BROUGHT THE DAWN':'EVERY SPARK COUNTS'}</div><h2>${victory?'The sun is yours.':'Stronger than before.'}</h2><div class="result-gold">+${earned} <span>GOLD${victory?' · INCLUDES 100 DAWN BONUS':''}</span></div><div class="result-stats"><span><b>${time(game.time)}</b>Survived</span><span><b>${game.kills}</b>Defeated</span><span><b>${game.level}</b>Level</span><span><b>${game.evolutionCount}</b>Evolved</span></div>${awarded.length?`<div class="awards">${awarded.map(m=>`<div><span>✓ ${m.name}</span><b>+${m.reward} gold</b></div>`).join('')}</div>`:''}<p class="hint">${save.gold>=30?'Your next permanent upgrade is waiting at the forge.':'Every coin counts toward your next permanent upgrade.'}</p><button class="primary" data-action="to-forge">Spend your gold <span>◈ ${save.gold}</span></button><button class="text-btn" data-action="to-camp">Return to camp</button>`,'results');}
function hud(){if(!game||!$('#timer'))return;$('#timer').textContent=time(game.time);$('#phase-label').textContent=game.dawnReached?'ENDLESS · DAWN REACHED':`DAWN IN ${time(Math.max(0,1800-game.time))}`;$('#hp-label').textContent=`${Math.ceil(game.player.hp)} / ${game.maxHp()}`;$('#hp-bar').style.width=Math.max(0,game.player.hp/game.maxHp()*100)+'%';$('#level-label').textContent='LV '+game.level;$('#run-gold').textContent=Math.floor(game.gold);$('#kills').textContent=game.kills;$('#xp-bar').style.width=Math.min(100,game.xp/game.need*100)+'%';$('#dash span').textContent=game.dashCd>0?game.dashCd.toFixed(1)+'s':'DASH';$('#dash').classList.toggle('cooldown',game.dashCd>0);$('#starter-hint').classList.toggle('gone',game.time>12);}
function resetInput(){input={x:0,y:0};keys={};stick=null;$('#joystick-base')?.classList.remove('engaged');if($('#joystick-knob'))$('#joystick-knob').style.transform='';}
function setupControls(){const canvas=$('#arena');canvas.addEventListener('pointerdown',e=>{if(game?.mode!=='playing'||stick)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const rect=canvas.getBoundingClientRect();let x=e.clientX-rect.left,y=e.clientY-rect.top;if(x>rect.width*.8)return;const base=$('#joystick-base'),fixed=save.settings.joystick==='fixed';stick={id:e.pointerId,x:fixed?88:x,y:fixed?rect.height-83:y};base.style.left=stick.x+'px';base.style.top=stick.y+'px';base.classList.add('engaged');move(e);});canvas.addEventListener('pointermove',move);function move(e){if(!stick||e.pointerId!==stick.id)return;const rect=canvas.getBoundingClientRect(),dx=e.clientX-rect.left-stick.x,dy=e.clientY-rect.top-stick.y,len=Math.hypot(dx,dy),max=40;input={x:dx/Math.max(max,len),y:dy/Math.max(max,len)};$('#joystick-knob').style.transform=`translate(${input.x*max}px,${input.y*max}px)`;}
 for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>{if(stick&&e.pointerId===stick.id)resetInput();});$('#dash').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(game)game.dash(input);});}
window.addEventListener('keydown',e=>{if(e.key==='Tab'&&modal){const items=[...document.querySelectorAll('#modal-host button:not(:disabled),#modal-host input,#modal-host select')].filter(el=>!el.hidden);if(items.length){let i=items.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();items.at(-1).focus();}else if(!e.shiftKey&&i===items.length-1){e.preventDefault();items[0].focus();}}}if(!game){if(e.key==='Escape'&&modal)closeModal();return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true;if(e.key===' '&&!e.repeat)game.dash(input);if(e.key==='Escape'){if(game.mode==='playing')pause();else if(game.mode==='paused'){game.mode='playing';closeModal();}}});window.addEventListener('keyup',e=>{delete keys[e.key.toLowerCase()];});
window.addEventListener('blur',()=>{if(game?.mode==='playing')pause();resetInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(game?.mode==='playing')pause();checkpoint();}else if(game?.mode==='playing')requestWake();});window.addEventListener('pagehide',checkpoint);window.addEventListener('resize',()=>renderer?.resize());
function frame(now){const dt=Math.min(.1,(now-(last||now))/1000);last=now;if(game&&renderer){if(!stick)input={x:(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),y:(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)};accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps<6){game.step(1/60,input);accumulator-=1/60;steps++;}renderer.draw(game,save.settings,input,now/1000);hudClock+=dt;if(hudClock>.1){hud();hudClock=0;}saveClock+=dt;if(saveClock>5){if(game.mode!=='ended')checkpoint();saveClock=0;}}requestAnimationFrame(frame);}
root.addEventListener('click',e=>{let b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.page){if(game)return;page=b.dataset.page;render();return;}if(b.dataset.hero){const hero=HEROES.find(h=>h.id===b.dataset.hero);if(save.heroes.includes(hero.id)){save.hero=hero.id;persist();render();}else showModal(`<div class="eyebrow">A NEW WAY TO PLAY</div><h2>${hero.name}, ${hero.title.toLowerCase()}</h2><p>${hero.desc}</p><p class="hero-bonus">${hero.bonus}</p><button class="primary" data-unlock="${hero.id}" ${save.gold<hero.cost?'disabled':''}>Unlock ${hero.name}<span>◈ ${hero.cost}</span></button>${save.gold<hero.cost?`<p class="hint">Earn ${hero.cost-save.gold} more gold to unlock.</p>`:''}<button class="text-btn" data-action="close">Back</button>`,'unlock');return;}
 if(b.dataset.unlock){let h=HEROES.find(h=>h.id===b.dataset.unlock);if(h&&save.gold>=h.cost&&!save.heroes.includes(h.id)){save.gold-=h.cost;save.heroes.push(h.id);save.hero=h.id;persist();render();toast(h.name+' joins the camp');}return;}
 if(b.dataset.buy){let u=META.find(u=>u.id===b.dataset.buy),n=save.meta[u.id]||0,cost=costOf(u,n);if(n<u.max&&save.gold>=cost){save.gold-=cost;save.spent+=cost;save.meta[u.id]=n+1;persist();render();sound();toast(u.name+' upgraded to rank '+(n+1));}return;}
 if(b.dataset.choice){game.choose(b.dataset.choice);return;}
 if(b.dataset.skill){let s=byId(b.dataset.skill);pause();toast(`${s.name} · Rank ${game.rank(s.id)}. ${s.desc}`);return;}
 const a=b.dataset.action;
 if(a==='close-chest')game?.closeChest();if(a==='dash')game?.dash(input);if(a==='start')start();if(a==='resume')start(true);if(a==='settings')settings();if(a==='howto')howto();if(a==='close')closeModal();if(a==='pause')pause();if(a==='unpause'){game.mode='playing';closeModal();requestWake();}if(a==='reroll')game.reroll();if(a==='revive')game.revive();if(a==='save-exit'){checkpoint();wake?.release().catch(()=>{});render();}if(a==='end-run')game.end(false);if(a==='bank-old'){start(true);game.end(false);}if(a==='to-forge'){page='forge';render();}if(a==='to-camp'){page='camp';render();}
 if(a==='respec'){save.gold+=save.spent;save.spent=0;save.meta={};persist();render();toast('All permanent upgrade gold refunded.');}
 if(a==='export'){checkpoint();const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='emberwake-save.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup exported. Keep it somewhere safe.');}
 if(a==='import')$('#save-file').click();
});
root.addEventListener('change',async e=>{if(e.target.id==='region'){save.region=e.target.value;persist();render();}if(['sound','shake','fx','joystick'].includes(e.target.id)){save.settings[e.target.id]=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?Number(e.target.value):e.target.value;persist();}if(e.target.id==='save-file'){try{const f=e.target.files[0];if(!f)return;if(f.size>4e6)throw Error('File too large');const imported=JSON.parse(await f.text());validateSave(imported);showModal(`<h2>Replace this device’s save?</h2><p>The imported save has ${imported.gold} gold, ${imported.stats.runs} expeditions, and ${imported.heroes.length} characters. Export your current save first if you want to keep it.</p><div class="button-row"><button class="secondary" id="cancel-import">Cancel</button><button class="primary" id="confirm-import">Replace save</button></div>`,'import-confirm');$('#cancel-import').onclick=()=>settings();$('#confirm-import').onclick=()=>{save=imported;persist();render();toast('Your progress is restored.');};}catch{toast('That file is not a valid Emberwake save.');}}});
function validateSave(s){
 const fail=()=>{throw Error('Invalid save');},num=(v,max=1e9)=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max;
 if(!s||s.version!==1||!Number.isSafeInteger(s.gold)||!num(s.gold)||!Number.isSafeInteger(s.spent)||!num(s.spent)||!s.stats||!s.meta||!s.settings||!Array.isArray(s.heroes)||!Array.isArray(s.claimed)||!Array.isArray(s.history)||!HEROES.some(h=>h.id===s.hero)||!REGIONS.some(r=>r.id===s.region))fail();
 for(const k of Object.keys(freshSave().stats))if(!num(s.stats[k]))fail();
 for(const [k,v]of Object.entries(s.meta)){let m=META.find(m=>m.id===k);if(!m||!Number.isInteger(v)||v<0||v>m.max)fail();}
 if(!s.heroes.includes(s.hero)||s.heroes.some(id=>!HEROES.some(h=>h.id===id))||s.claimed.some(id=>!MILESTONES.some(m=>m.id===id)))fail();
 if(s.history.length>20||s.history.some(h=>!h||!HEROES.some(a=>a.name===h.hero)||!num(h.time)||!num(h.gold)||!num(h.kills)))fail();
 s.settings={sound:s.settings.sound!==false,shake:s.settings.shake===true,fx:typeof s.settings.fx==='number'?Math.max(.15,Math.min(1,s.settings.fx)):.6,joystick:s.settings.joystick==='fixed'?'fixed':'floating'};
 if(s.run){const r=s.run,template=new Game(freshSave()).snapshot();for(const key of Object.keys(r))if(!Object.hasOwn(template,key))delete r[key];
 if(!r.player||!Number.isFinite(r.player.x)||!Number.isFinite(r.player.y)||!num(r.player.hp,10000)||!num(r.time)||!r.skills||!r.hero||!HEROES.some(h=>h.id===r.hero.id)||!REGIONS.some(a=>a.id===r.region)||!['playing','paused','levelup','down','chest'].includes(r.mode))fail();
 r.hero=HEROES.find(h=>h.id===r.hero.id);for(const [id,n]of Object.entries(r.skills))if(!byId(id)||!Number.isInteger(n)||n<1||n>(WEAPONS.some(w=>w.id===id)?8:3))fail();
 if(r.recentUpgrades!==undefined&&(!Array.isArray(r.recentUpgrades)||r.recentUpgrades.length>2||r.recentUpgrades.some(id=>!byId(id))))fail();
 if(r.waveMinute!==undefined&&(!Number.isInteger(r.waveMinute)||r.waveMinute<0))fail();
 for(const k of ['enemies','bullets','gems','hazards','pickups','choices','evolved'])if(!Array.isArray(r[k])||r[k].length>1500)fail();
 if(r.choices.some(id=>!byId(id)&&!['healreward','goldreward'].includes(id))||r.evolved.some(id=>!WEAPONS.some(w=>w.id===id)))fail();
 for(const k of ['level','xp','need','gold','kills','rerolls','revives','nextId','spawnClock','coinClock','nextElite','nextCache','nextHeal','dashCd','dashing','invuln','evolutionCount'])if(!Number.isFinite(r[k]))fail();
 if(r.chestReward&&(!Array.isArray(r.chestReward.rewards)||r.chestReward.rewards.length>5||!num(r.chestReward.gold)||r.chestReward.rewards.some(v=>!v||(!byId(v.id)&&v.id!=='goldreward')||(byId(v.id)&&(!Number.isInteger(v.rank)||v.rank<1||v.rank>(WEAPONS.some(w=>w.id===v.id)?8:3))))))fail();
 for(const k of ['enemies','bullets','gems','hazards','pickups'])for(const o of r[k])if(!o||!Number.isFinite(o.x)||!Number.isFinite(o.y))fail();
 if(r.enemies.some(e=>!Object.hasOwn(ENEMIES,e.type)||!Number.isFinite(e.hp)))fail();
 }
 return true;
}
function registerTools(){const ctx=document.modelContext;if(!ctx?.registerTool)return;for(const tool of [{name:'read_emberwake_progress',title:'Read Emberwake progress',description:'Read gold, permanent upgrades, unlocked characters, and the active run without changing them.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({build:'arsenal-7',gold:save.gold,meta:{...save.meta},heroes:[...save.heroes],stats:{...save.stats},run:game?{time:game.time,level:game.level,mode:game.mode,health:game.player.hp,maxHealth:game.maxHp(),position:{x:game.player.x,y:game.player.y},kills:game.kills,chestsOpened:game.chestsOpened,bossesKilled:game.bossesKilled,dawnReached:game.dawnReached,skills:{...game.skills}}:null})},{name:'pause_emberwake_run',title:'Pause expedition',description:'Pause the current playing expedition and save its progress. Fails if no expedition is playing.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{if(!game||game.mode!=='playing')throw Error('No expedition is playing');pause();return{mode:game.mode,saved:storageOK};}}])try{Promise.resolve(ctx.registerTool(tool)).catch(()=>{});}catch{}}
render();requestAnimationFrame(frame);registerTools();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
