import {DISCOVERIES,siteGuardian} from './discoveries.js?v=19';
const TAU=Math.PI*2;
export function drawDiscoveries(c,g,b,paint){for(const s of g.discoveries){if(s.state==='claimed'||s.x<b.left-170||s.x>b.right+170||s.y<b.top-170||s.y>b.bottom+170)continue;const def=DISCOVERIES[s.kind],ready=s.state==='ready';c.save();c.translate(s.x,s.y);
 c.fillStyle=g.region==='cinder'?'#3b3028':g.region==='hollow'?'#2d2843':'#263d36';c.strokeStyle=def.color;c.lineWidth=3;c.beginPath();c.ellipse(0,8,83,43,0,0,TAU);c.fill();c.stroke();c.globalAlpha=.25;c.beginPath();c.ellipse(0,8,69,33,0,0,TAU);c.stroke();c.globalAlpha=1;
 for(let i=0;i<4;i++){const a=i*TAU/4+.6,x=Math.cos(a)*75,y=Math.sin(a)*34;c.fillStyle='#131e25';c.fillRect(x-5,y-18,10,24);c.fillStyle=def.color;c.fillRect(x-3,y-22,6,6);}
 if(s.kind==='vault'){paint(c,'chest',0,3,57);if(!ready){c.strokeStyle='#bbb7a5';c.lineWidth=3;c.beginPath();c.moveTo(-22,-22);c.lineTo(24,4);c.moveTo(22,-22);c.lineTo(-24,4);c.stroke();}}
 else if(s.kind==='altar'){paint(c,'rune',0,4,73);c.strokeStyle=def.color;c.lineWidth=2;c.beginPath();c.arc(0,-32,27,g.time*.5,g.time*.5+Math.PI*1.7);c.stroke();}
 else {c.fillStyle='#355b59';c.beginPath();c.ellipse(0,0,32,15,0,0,TAU);c.fill();c.strokeStyle=def.color;c.stroke();c.font='bold 30px sans-serif';c.fillStyle=def.color;c.textAlign='center';c.fillText('♥',0,-9);}
 if(s.state==='sealed'){c.globalAlpha=.7;paint(c,g.region==='ashwood'&&s.kind==='vault'?'boss':siteGuardian(g.region,s.kind),0,-72,78);c.globalAlpha=1;c.fillStyle='#d8d3c0';c.font='bold 12px sans-serif';c.textAlign='center';c.fillText('SLEEPING GUARDIAN',0,-151);}
 c.fillStyle=def.color;c.textAlign='center';c.font='bold 13px sans-serif';c.fillText(def.name.toUpperCase(),0,65);c.font='11px sans-serif';c.fillStyle='#f2e9d5';c.fillText(ready?'UNSEALED · WALK UP TO CLAIM':s.state==='guarded'?'DEFEAT THE GUARDIAN':'APPROACH TO CHALLENGE',0,81);if(s.discovered){c.font='10px sans-serif';c.fillStyle=def.color;c.fillText(def.reward,0,96);}c.restore();}}
export function drawDiscoveryCompass(c,g,w,h,zoom){
 const active=g.discoveries.find(s=>s.state==='guarded'),target=active||g.discoveries.filter(s=>s.state==='ready').sort((a,b)=>Math.hypot(a.x-g.player.x,a.y-g.player.y)-Math.hypot(b.x-g.player.x,b.y-g.player.y))[0]||g.discoveries.filter(s=>s.state!=='claimed').sort((a,b)=>Math.hypot(a.x-g.player.x,a.y-g.player.y)-Math.hypot(b.x-g.player.x,b.y-g.player.y))[0];if(!target)return;
 const dx=target.x-g.player.x,dy=target.y-g.player.y,d=Math.hypot(dx,dy),def=DISCOVERIES[target.kind];let x=w/2+dx*zoom,y=h/2+dy*zoom;
 if(x<35||x>w-35||y<108||y>h-95){const factor=Math.min((w/2-40)/Math.max(1,Math.abs(dx*zoom)),Math.max(30,h/2-105)/Math.max(1,Math.abs(dy*zoom)));x=w/2+dx*zoom*factor;y=h/2+dy*zoom*factor;c.fillStyle='#101c24dd';c.beginPath();c.arc(x,y,14,0,TAU);c.fill();c.strokeStyle=def.color;c.lineWidth=2;c.stroke();c.fillStyle=def.color;c.font='bold 16px sans-serif';c.textAlign='center';c.fillText(target.discovered?def.icon:'?',x,y+5);c.font='bold 10px sans-serif';c.fillText(Math.round(d)+'m',x,y+29);}
 // Keep discovery guidance away from the health, boss and shrine HUDs.
 if(!g.objective){c.fillStyle='#101c24da';const bw=Math.min(w-170,350);c.fillRect((w-bw)/2,h-77,bw,22);c.textAlign='center';c.font='bold 10px sans-serif';c.fillStyle=def.color;c.fillText(target.state==='ready'?def.icon+' '+def.name+' · UNSEALED':target.state==='guarded'?'⚔ '+def.name+' · '+(d>480?'Guardian waits here':'Defeat its guardian'):target.discovered?def.icon+' '+def.name+' · '+def.reward:'? GUARDED DISCOVERY · '+Math.round(d)+'m · Follow the compass',w/2,h-62);}
}
