import {stepDiscoveries,guardSite,unlockSite} from './discoveries.js?v=14';
import {REGIONAL_ENEMIES,ROSTERS,regionalType,regionalPool} from './bestiary.js?v=14';
import {stepRegional,regionalDeath} from './region-combat.js?v=14';
import {resolveTerrain,lavaAt,riftAt,safePoint} from './world.js?v=14';
import {stepWorld,stepObjective,spawnOverlord,attackOverlord} from './expedition.js?v=14';
import {equippedItem,gearItem,gearStats,rollGear} from './gear.js?v=14';
import {WEAPONS,PASSIVES,RELICS,HEROES,byId,ENEMIES,WEAPON_SLOTS,PASSIVE_SLOTS} from './data.js?v=14';
export const MAX_RANGED_ENEMIES=5;
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class Game {
 constructor(save,onEvent=()=>{},snapshot=null){
  this.gear=snapshot?(snapshot.gear?gearItem(snapshot.gear.id,snapshot.gear.level):null):equippedItem(save);this.gearBonuses=gearStats(this.gear);this.spellcraft=JSON.parse(JSON.stringify(snapshot?(snapshot.spellcraft||{}):(save.spellcraft||{})));this.pendingGear=[];this.spawnBudget=0;this.wardClock=0;this.shield=this.gearBonuses.ward||0;this.meta={...save.meta};this.hero=HEROES.find(h=>h.id===save.hero)||HEROES[0];this.region=save.region;this.onEvent=onEvent;
  this.discoveryLayoutVersion=2;this.discoveryChoice=false;this.discoveries=[];this.discoverySerial=0;this.discoveriesCleared=0;this.nextDiscoveryScan=0;this.relics={};this.lateStarted=false;this.objective=null;this.objectivesCompleted=0;this.nextObjective=600;this.nextWorldStrike=610;this.objectiveChoice=false;
  this.rng=(Date.now()>>>0)||7;this.time=0;this.kills=0;this.gold=0;this.level=1;this.xp=0;this.need=18;this.balanceVersion=5;this.recentUpgrades=[];this.waveMinute=0;this.skills={[this.hero.weapon]:1};this.evolved=[];this.rerolls=3+(this.meta.reroll||0);this.revives=1;this.mode='playing';this.enemies=[];this.bullets=[];this.gems=[];this.effects=[];this.hazards=[];this.pickups=[];this.texts=[];this.choices=[];this.cd={};this.spawnClock=0;this.coinClock=0;this.nextElite=60;this.nextCache=75;this.nextHeal=35;this.nextId=1;this.dashCd=0;this.dashing=0;this.invuln=2;this.lastDir={x:0,y:-1};this.nextBoss=180;this.bossesKilled=0;this.dawnReached=false;this.chestReward=null;this.chestsOpened=0;this.bossSpawned=false;this.bossDefeated=false;this.damageDone={};this.pendingLevels=0;this.evolutionCount=0;this.bankId='run-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
  if(!snapshot){this.revives+=this.g('revive');this.skills={[this.hero.weapon]:this.openingRank(this.hero.weapon)};if(this.gearBonuses.startSpell){const id=this.gearBonuses.startSpell;this.skills[id]=Math.min(8,this.openingRank(id)+(id===this.hero.weapon?1:0));}}
  this.player={x:0,y:0,hp:1};this.player.hp=this.maxHp();
  if(snapshot){Object.assign(this,snapshot);this.onEvent=onEvent;this.mode=this.player.hp<=0?'down':this.chestReward?'chest':this.choices?.length?'levelup':'paused';this.nextBoss=snapshot.nextBoss??(Math.floor(this.time/180)+1)*180;this.dawnReached=this.dawnReached||this.time>=1800;for(const id of this.evolved)this.skills[id]=8;if((snapshot.balanceVersion||4)<5){const needed=this.xpNeeded(this.level);this.xp*=needed/Math.max(1,this.need);this.need=needed;for(const e of this.enemies)e.speed*=({crawler:52/30,bat:95/62,brute:38/22,shooter:42/25,charger:65/38}[e.type]||1);this.balanceVersion=5;}this.gear=this.gear?gearItem(this.gear.id,this.gear.level):null;this.gearBonuses=gearStats(this.gear);this.effects=[];this.texts=[];this.hazards=this.hazards||[];for(const pick of this.pickups)Object.assign(pick,safePoint(this.region,pick.x,pick.y));this.migrateRegionalEnemies();this.limitRangedEnemies();this.discoveryLayoutVersion=snapshot.discoveryLayoutVersion||1;this.waveMinute=snapshot.waveMinute??Math.floor(this.time/60);}
 }
 random(){this.rng^=this.rng<<13;this.rng^=this.rng>>>17;this.rng^=this.rng<<5;return (this.rng>>>0)/4294967296;}
 xpNeeded(level=this.level){return level===1?18:Math.floor(18+level*7+level*level*.55);}
 rank(id){return this.skills[id]||0;}
 a(id){return this.relics['ascend_'+id]||0;}
 ascensionOffers(){return RELICS.filter(r=>(this.relics[r.id]||0)<r.max&&(r.id!=='ascend_haste'||WEAPONS.some(w=>this.rank(w.id)>0&&this.haste(w.id)>.300001))).map(r=>({id:r.id,key:this.random()*(this.recentUpgrades.includes(r.id)?.3:1)})).sort((a,b)=>b.key-a.key).slice(0,3).map(r=>r.id);}
 m(id){return this.meta[id]||0;}
 g(id){return this.gearBonuses[id]||0;}
 openingRank(id){return Math.min(8,1+(this.spellcraft[id]?.opening||0)+this.g('spellRanks'));}
 armor(){return this.a('ward')+this.m('armor')+this.rank('guard')+this.g('armor');}
 hurt(amount){const absorbed=Math.min(this.shield,amount);this.shield-=absorbed;this.player.hp-=amount-absorbed;this.invuln=.6;this.emit('hurt');}
 maxHp(){return 100+this.a('vigor')*15+Math.round(this.g('health'))+this.m('health')*10+this.rank('vitality')*25+(this.hero.id==='warden'?35:0);}
 damage(){return (1+this.m('might')*.05+this.rank('power')*.15+this.rank('force')*.04+this.g('damage'))*(this.hero.id==='witch'?1.15:1)*(1+this.a('power')*.08);}
 area(){return 1+Math.min(.8,this.a('area')*.04)+this.m('area')*.05+this.rank('reach')*.15+this.g('area');}
 haste(id){return Math.max(.3,(1-this.m('haste')*.03-this.rank('haste')*.1-this.g('haste'))*(1-(this.spellcraft[id]?.haste||0)*.02)*(1-this.a('haste')*.02));}
 speed(){return 145*(1+Math.min(.4,this.a('flow')*.02)+this.m('speed')*.04+this.rank('agility')*.04+this.g('speed'))*(this.hero.id==='ranger'?1.1:1);}
 magnet(){return 85+this.a('flow')*12+this.m('magnet')*12+this.rank('magnet')*45+this.g('magnet');}
 xpBonus(){return 1+this.m('growth')*.05+this.rank('wisdom')*.2+(this.hero.id==='sage'?.2:0);}
 goldBonus(){return (1+this.m('fortune')*.08)*(this.region==='hollow'?1.25:this.region==='cinder'?1.5:1);}
 snapshot(){const o={};for(const k of Object.keys(this)){if(!['onEvent','effects','texts'].includes(k))o[k]=this[k];}return JSON.parse(JSON.stringify(o));}
 emit(type,data={}){this.onEvent(type,data);}
 gainGold(n){this.gold+=n*this.goldBonus();}
 nearest(x=this.player.x,y=this.player.y){let nearest=null,dist=Infinity;for(const e of this.enemies){if(e.hp<=0)continue;const d=(e.x-x)**2+(e.y-y)**2;if(d<dist){dist=d;nearest=e;}}return nearest;}
 hit(e,amount,weapon,knock=0){if(e.hp<=0)return;const crit=this.random()<.05+this.rank('luck')*.1+this.g('crit');const dmg=amount*this.damage()*(1+(this.spellcraft[weapon]?.power||0)*.04)*(crit?2+this.rank('precision')*.35+this.g('critDamage'):1)*(1-(ENEMIES[e.type]?.armor||0));e.hp-=dmg;e.flash=.09;this.damageDone[weapon]=(this.damageDone[weapon]||0)+Math.min(dmg,e.hp+dmg);if(this.g('leech'))this.player.hp=Math.min(this.maxHp(),this.player.hp+Math.min(dmg,e.hp+dmg)*this.g('leech'));if(knock&&!e.boss){knock*=(1+this.a('area')*.08+this.rank('force')*.3+this.g('knock'))*(ENEMIES[e.type]?.knock??1);const d=Math.hypot(e.x-this.player.x,e.y-this.player.y)||1;e.x+=(e.x-this.player.x)/d*knock;e.y+=(e.y-this.player.y)/d*knock;}
  if(crit&&this.texts.length<20)this.texts.push({x:e.x,y:e.y-15,text:Math.round(dmg)+'!',life:.6,color:'#ffd57d'});
  if(e.hp<=0){regionalDeath(this,e);this.kills++;this.gainGold(e.boss?70:e.elite?18:.17);this.gems.push({x:e.x,y:e.y,value:e.boss?80:e.elite?22:(ENEMIES[e.type]?.xp||1),kind:'xp',born:this.time});if(e.elite){this.player.hp=Math.min(this.maxHp(),this.player.hp+15);this.emit('elite');}if((e.elite||e.boss)&&!e.siteId)this.pickups.push({...safePoint(this.region,e.x,e.y),kind:'chest',boss:e.boss,rewards:e.lateBoss?5:e.boss?(this.random()<.25+this.rank('luck')*.08?5:3):(this.random()<.15?3:1),gold:e.lateBoss?350+Math.floor(this.time/60)*20:e.boss?100+Math.floor(this.time/60)*8:35+Math.floor(this.time/60)*3});if(e.boss){this.bossDefeated=true;this.bossesKilled++;this.emit('bossdown',{site:!!e.siteId});unlockSite(this,e);}if(this.kills%100===0)this.emit('streak',{kills:this.kills});if(this.random()<.002)this.pickups.push({...safePoint(this.region,e.x,e.y),kind:'heal'});}
 }
 migrateRegionalEnemies(){for(const e of this.enemies){const type=regionalType(this.region,e.type,e.boss,this.time,e.lateBoss);if(type===e.type)continue;const old=ENEMIES[e.type],spec=ENEMIES[type];e.type=type;e.speed=spec.speed*this.difficulty().speed*(this.region==='hollow'?1.15:1);if(!e.boss){const ratio=spec.hp/(old?.hp||spec.hp);e.hp*=ratio;e.maxHp*=ratio;e.r=e.elite?21:spec.r;}else e.title=spec.name;e.phase=0;e.attack=3;e.blinkTarget=null;}}
 rangedCount(){return this.enemies.filter(e=>e.hp>0&&ENEMIES[e.type]?.ranged&&!e.boss).length;}
 limitRangedEnemies(){let count=0,converted=false;for(const e of this.enemies){if(e.hp<=0||!ENEMIES[e.type]?.ranged||e.boss)continue;if(++count<=MAX_RANGED_ENEMIES)continue;const old=ENEMIES[e.type];e.type=ROSTERS[this.region]?.[0]||'crawler';const spec=ENEMIES[e.type];e.speed*=spec.speed/old.speed;e.hp*=spec.hp/old.hp;e.maxHp*=spec.hp/old.hp;e.r=spec.r;e.phase=0;converted=true;}if(converted)this.hazards=this.hazards.filter(h=>h.kind!=='shot');}
 spawn(type='crawler',elite=false,boss=false){type=regionalType(this.region,type,boss,this.time);if(ENEMIES[type]?.ranged&&!boss&&this.rangedCount()>=MAX_RANGED_ENEMIES)type=ROSTERS[this.region]?.[0]||'crawler';const a=this.random()*TAU,dist=360+this.random()*150,spec=ENEMIES[type]||ENEMIES.crawler;const veteran=!!spec.region&&!boss&&this.time>=600;const hp=spec.hp*this.difficulty().health*(elite?6:1)*(boss?18:1)*(this.region==='cinder'?1.25:1)*(veteran?1+Math.min(5,(this.time/60-10)*.12):1);const e={id:this.nextId++,type,x:this.player.x+Math.cos(a)*dist,y:this.player.y+Math.sin(a)*dist,hp,maxHp:hp,r:boss?(spec.region?spec.r:35):elite?21:spec.r,speed:spec.speed*this.difficulty().speed*(this.region==='hollow'?1.15:1),elite,boss,slow:0,flash:0,attack:1+this.random()*3,phase:0};if(boss&&spec.region)e.title=spec.name;Object.assign(e,safePoint(this.region,e.x,e.y));this.enemies.push(e);return e;}
 // Region tiers reward permanent progression without scaling against the player's gear.
 // Smooth, bounded extra multipliers preserve the original spawn curve and warning times.
 regionalStrength(){const m=Math.max(0,this.time/60),h=Math.min(30,m);if(this.region==='hollow')return {health:1+h*.45+h*h*.02,speed:1+Math.min(.25,m*.012),damage:1+Math.min(.65,m*.06)};if(this.region==='cinder')return {health:1+h*.75+h*h*.04,speed:1+Math.min(.35,m*.018),damage:1+Math.min(1,m*.09)};return {health:1,speed:1,damage:1};}
 enemyDamage(amount){return amount*this.regionalStrength().damage;}
 difficulty(){const m=this.time/60,strength=this.regionalStrength();return {health:strength.health*(1+m*.35+m*m*.018)*(1+Math.max(0,m-10)*.18+Math.max(0,m-10)**2*.012),speed:(1+Math.min(1.05,m*.024))*strength.speed,cap:Math.min(600,Math.floor(100+m*14+Math.max(0,m-2)*6)),count:Math.min(32,2+m*.65+Math.max(0,m-2)*.1),interval:Math.max(.3,.9-m*.015),surge:false};}
 enemyType(){const m=this.time/60;if(ROSTERS[this.region]){const pool=regionalPool(this.region,m);let n=this.random()*pool.reduce((sum,[,w])=>sum+w,0);for(const [id,w]of pool){n-=w;if(n<=0)return id;}return pool[0][0];}if(m<3){const r=this.random();return m>=2&&r<.3?'shooter':m>=1&&r<.48?'brute':r<.67?'bat':'crawler';}const pool=[['crawler',3],['bat',2],['brute',2],['shooter',.8],['ironhide',3],['charger',1],['reaver',3],['revenant',3],['juggernaut',2],['leech',2],['champion',2],['bulwark',5],['stalker',4],['siege',3],['harbinger',3]].filter(([id])=>ENEMIES[id].minute<=m).map(([id,w])=>[id,w*Math.min(1,.2+Math.max(0,m-ENEMIES[id].minute)*.8)]);let r=this.random()*pool.reduce((n,[,w])=>n+w,0);for(const [id,w]of pool){r-=w;if(r<=0)return id;}return 'crawler';}
 burst(x,y,r,color,life=.4){if(this.effects.length<80)this.effects.push({kind:'ring',x,y,r,color,life,max:life});}
 aoe(x,y,r,dmg,id,knock=0){for(const e of this.enemies)if((e.x-x)**2+(e.y-y)**2<(r+e.r)**2)this.hit(e,dmg,id,knock);}
 fire(id){const rank=this.rank(id),ev=this.evolved.includes(id),p=this.player,area=this.area(),target=this.nearest();if(!target&&id!=='orbit')return;if(target&&Math.hypot(target.x-p.x,target.y-p.y)>410)return;const angle=target?Math.atan2(target.y-p.y,target.x-p.x):0;
  if(id==='bolt'||id==='dagger'){const dagger=id==='dagger';const n=ev?(dagger?11:7):(dagger?3+Math.floor(rank/2):1+Math.floor(rank/2));for(let i=0;i<n;i++){const a=angle+(i-(n-1)/2)*(dagger?.13:.15);this.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*(dagger?340:295),vy:Math.sin(a)*(dagger?340:295),life:1.9,r:dagger?4:6,damage:(dagger?16:22)*(1+(rank-1)*.28)*(ev?1.6:1),id,pierce:ev?7:1+Math.floor(rank/2),hit:[],color:dagger?'#d9e9c7':'#ffbf68'});}this.cd[id]=(dagger?1.1:.8)*this.haste(id)*(ev?.65:1);}
  if(id==='chain'){let t=target,seen=[],points=[{x:p.x,y:p.y}];for(let i=0;i<(ev?16:rank+2)&&t;i++){seen.push(t.id);points.push({x:t.x,y:t.y});this.hit(t,30*(1+(rank-1)*.3)*(ev?1.4:1),id);let min=210*area,next=null;for(const e of this.enemies)if(e.hp>0&&!seen.includes(e.id)){let d=Math.hypot(e.x-t.x,e.y-t.y);if(d<min){next=e;min=d;}}t=next;}this.effects.push({kind:'chain',points,color:'#a7ecff',life:.22,max:.22});this.cd[id]=(ev?1:2.2)*this.haste(id);}
  if(id==='nova'){const r=(105+(rank-1)*16)*(ev?1.7:1)*area;let count=this.enemies.filter(e=>Math.hypot(e.x-p.x,e.y-p.y)<r).length;this.aoe(p.x,p.y,r,38*(1+(rank-1)*.3),id,45);if(ev&&count>=3)p.hp=Math.min(this.maxHp(),p.hp+4);this.burst(p.x,p.y,r,'#d8e6aa');this.cd[id]=(ev?1.9:3)*this.haste(id);}
  if(id==='frost'){const r=(110+(rank-1)*13)*(ev?1.8:1)*area;for(const e of this.enemies)if(Math.hypot(e.x-p.x,e.y-p.y)<r){e.slow=ev?3.5:1.5+rank*.2;this.hit(e,16+(rank-1)*6,id);}this.burst(p.x,p.y,r,'#91e1e9',.65);this.cd[id]=(ev?2.5:4)*this.haste(id);}
  if(id==='flame'){const r=(150+(rank-1)*13)*area;for(const e of this.enemies){const a=Math.atan2(e.y-p.y,e.x-p.x);const diff=Math.atan2(Math.sin(a-angle),Math.cos(a-angle));if(Math.hypot(e.x-p.x,e.y-p.y)<r&&(ev||Math.abs(diff)<.7+rank*.05))this.hit(e,36+(rank-1)*12,id);}this.effects.push({kind:'flame',x:p.x,y:p.y,r,angle,full:ev,color:'#ff9765',life:.4,max:.4});if(ev)this.effects.push({kind:'fire',x:p.x,y:p.y,r:80*area,life:2,max:2,tick:0,id});this.cd[id]=(ev?1:1.4)*this.haste(id);}
  if(id==='meteor'){for(let i=0;i<(ev?3:1);i++){const t=i===0?target:this.enemies[Math.floor(this.random()*this.enemies.length)]||target;if(t)this.hazards.push({x:t.x,y:t.y,r:(65+(rank-1)*9)*area,life:.65,max:.65,kind:'meteor',damage:65+(rank-1)*20,id});}this.cd[id]=(ev?2.2:3.2)*this.haste(id);}
  if(['spear','scythe','wisp','axe'].includes(id)){const count=id==='spear'?(ev?3:1):id==='scythe'?(ev?3:rank>=5?2:1):id==='wisp'?(ev?7:2+Math.floor((rank-1)/2)):(ev?6:2+Math.floor((rank-1)/3));const speed=id==='spear'?430:id==='wisp'?180:230;for(let i=0;i<count;i++){const a=angle+(i-(count-1)/2)*(id==='axe'?.35:.2);this.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:id==='wisp'?3.2:2.1,age:0,r:id==='axe'?10:id==='scythe'?9:5,damage:({spear:42,scythe:28,wisp:20,axe:36}[id]+(rank-1)*({spear:12,scythe:8,wisp:6,axe:10}[id]))*(ev?1.35:1),id,pierce:id==='spear'?5+rank:id==='wisp'?(ev?3:1):4+Math.floor(rank/2),hit:[],color:byId(id).color});}this.cd[id]=({spear:1.8,scythe:2,wisp:2.2,axe:2}[id])*(ev?.7:1)*this.haste(id);}
  if(id==='mine'){for(let i=0;i<(ev?3:1);i++)this.hazards.push({kind:'mine',x:p.x+Math.cos(i*TAU/3)*18,y:p.y+Math.sin(i*TAU/3)*18,r:(65+rank*6)*area,trigger:45+rank*4,life:8,max:8,arm:.55,damage:(60+(rank-1)*16)*(ev?1.4:1),id});this.cd[id]=2.5*this.haste(id)*(ev?.7:1);}
  if(id==='venom'){for(let i=0;i<(ev?2:1);i++){const t=i?this.enemies[Math.floor(this.random()*this.enemies.length)]||target:target;this.effects.push({kind:'pool',x:t.x,y:t.y,r:(65+rank*7)*(ev?1.4:1)*area,life:ev?6:4,max:ev?6:4,tick:0,damage:12+(rank-1)*4,id,color:'#a9df6e',slow:ev});}this.cd[id]=(ev?2.6:3)*this.haste(id);}
  if(id==='beam'){for(let i=0;i<(ev?3:1);i++){const a=angle+(i-1)*(ev?.22:0),length=(440+(rank-1)*12)*area,width=12+rank*2;for(const e of this.enemies){const dx=e.x-p.x,dy=e.y-p.y,along=dx*Math.cos(a)+dy*Math.sin(a),across=Math.abs(-dx*Math.sin(a)+dy*Math.cos(a));if(along>0&&along<length&&across<width+e.r)this.hit(e,(46+(rank-1)*14)*(ev?1.25:1),id);}this.effects.push({kind:'beam',x:p.x,y:p.y,angle:a,r:length,width,color:'#93eeef',life:.3,max:.3});}this.cd[id]=2.4*this.haste(id)*(ev?.7:1);}
  if(id==='tide'){this.hazards.push({kind:'wave',x:p.x,y:p.y,r:(190+(rank-1)*22)*(ev?1.5:1)*area,life:1,max:1,damage:32+(rank-1)*10,id,hit:[]});this.cd[id]=(ev?2.2:3.4)*this.haste(id);}

 }
 dash(input={x:0,y:0}){if(this.mode!=='playing'||this.dashCd>0)return false;const len=Math.hypot(input.x,input.y);if(len>.1)this.lastDir={x:input.x/len,y:input.y/len};this.dashing=.22;this.invuln=.6;this.dashCd=Math.max(1.4,3.6-this.m('dash')*.3-this.rank('agility')*.12);this.emit('dash');return true;}
 offers(){let list=[...WEAPONS,...PASSIVES].filter(s=>{const weapon=WEAPONS.some(w=>w.id===s.id),max=weapon?8:3;const occupied=(weapon?WEAPONS:PASSIVES).filter(w=>this.rank(w.id)>0).length;return this.rank(s.id)<max&&(this.rank(s.id)>0||occupied<(weapon?WEAPON_SLOTS:PASSIVE_SLOTS));});let shuffled=list.map(x=>({x,key:this.random()/(1+this.rank(x.id)*.12)*(this.recentUpgrades.includes(x.id)?.4:1)})).sort((a,b)=>b.key-a.key).map(x=>x.x.id);const asc=this.ascensionOffers();this.choices=this.objectiveChoice||!shuffled.length?asc:this.time>=600?[...shuffled.slice(0,2),...asc.slice(0,3-Math.min(2,shuffled.length))]:shuffled.slice(0,3);if(!this.choices.length)this.choices=['healreward','goldreward'];return this.choices;}
 upgrade(id){const relic=RELICS.find(r=>r.id===id);if(relic){const n=this.relics[id]||0;if(n>=relic.max)return false;this.relics[id]=n+1;if(id==='ascend_vigor'||id==='ascend_ward')this.player.hp=Math.min(this.maxHp(),this.player.hp+(id==='ascend_vigor'?15:10));return true;}const max=WEAPONS.some(w=>w.id===id)?8:3;if(this.rank(id)>=max)return false;this.skills[id]=this.rank(id)?this.rank(id)+1:WEAPONS.some(w=>w.id===id)?this.openingRank(id):1;if(id==='vitality')this.player.hp=Math.min(this.maxHp(),this.player.hp+25);return true;}
 choose(id){if(this.mode!=='levelup'||!this.choices.includes(id))return false;if(id==='healreward')this.player.hp=Math.min(this.maxHp(),this.player.hp+40);else if(id==='goldreward')this.gainGold(20);else {this.upgrade(id);this.recentUpgrades=[id,...this.recentUpgrades].slice(0,2);}this.choices=[];this.objectiveChoice=false;this.discoveryChoice=false;this.mode='playing';this.invuln=Math.max(this.invuln,1.2);this.emit('choose',{id});return true;}
 openChest(pick){if(this.mode!=='playing'||this.player.hp<=0)return false;const before=this.gold;this.gainGold(pick.gold||50);const rewards=[],awarded=new Set();for(let i=0;i<(pick.rewards||3);i++){const evo=WEAPONS.find(w=>this.rank(w.id)>=8&&this.rank(w.pair)>=2&&!this.evolved.includes(w.id));if(evo){this.evolved.push(evo.id);this.evolutionCount++;rewards.push({id:evo.id,rank:8,evolved:true});continue;}const available=[...WEAPONS,...PASSIVES].filter(w=>this.rank(w.id)>0&&this.rank(w.id)<(WEAPONS.includes(w)?8:3));if(available.length){const distinct=available.filter(w=>!awarded.has(w.id)),pool=distinct.length?distinct:available,w=pool[Math.floor(this.random()*pool.length)];awarded.add(w.id);this.upgrade(w.id);rewards.push({id:w.id,rank:this.rank(w.id)});}else{const id=this.ascensionOffers()[0];if(id){this.upgrade(id);rewards.push({id,rank:this.relics[id],ascension:true});}else{this.gainGold(40);rewards.push({id:'goldreward',gold:Math.round(40*this.goldBonus())});}}}pick.taken=true;this.chestsOpened++;const gear=rollGear(this.time,!!pick.boss,()=>this.random());if(gear)this.pendingGear.push({...gear});this.chestReward={gold:Math.floor(this.gold)-Math.floor(before),rewards,boss:!!pick.boss,gear};this.mode='chest';this.invuln=Math.max(this.invuln,2);this.emit('chest',this.chestReward);return true;}
 closeChest(){if(this.mode!=='chest')return false;this.chestReward=null;this.mode='playing';this.emit('choose');return true;}
 reroll(){if(this.mode!=='levelup'||this.rerolls<=0)return false;this.rerolls--;this.offers();this.emit('levelup');return true;}
 revive(){if(this.mode!=='down'||this.revives<=0)return false;this.revives--;this.player.hp=this.maxHp()*.6;this.invuln=4;for(const e of this.enemies)if(Math.hypot(e.x-this.player.x,e.y-this.player.y)<200){const a=Math.atan2(e.y-this.player.y,e.x-this.player.x);e.x=this.player.x+Math.cos(a)*240;e.y=this.player.y+Math.sin(a)*240;}this.mode='playing';this.emit('revive');return true;}
 end(victory=false){if(this.mode==='ended')return;this.mode='ended';this.emit('end',{victory:victory||this.dawnReached||this.time>=1800});}
 step(dt,input={x:0,y:0}){if(this.mode!=='playing')return;dt=clamp(dt,0,.05);this.time+=dt;const p=this.player;
  if(this.time>=1800&&!this.dawnReached){this.dawnReached=true;this.emit('dawn');}
  this.invuln=Math.max(0,this.invuln-dt);this.dashCd=Math.max(0,this.dashCd-dt);this.dashing=Math.max(0,this.dashing-dt);
  p.hp=Math.min(this.maxHp(),p.hp+dt*(this.m('regen')*.15+this.rank('regen')*.6+this.a('regen')*.15+this.g('regen')));if(this.g('ward')){this.wardClock+=dt;if(this.wardClock>=20){this.wardClock%=20;this.shield=this.g('ward');}}
  let len=Math.hypot(input.x,input.y);if(len>.05){let n=Math.max(1,len);input={x:input.x/n,y:input.y/n};this.lastDir={x:input.x/len*n,y:input.y/len*n};}
  const vx=this.dashing>0?this.lastDir.x*640:input.x*this.speed(),vy=this.dashing>0?this.lastDir.y*640:input.y*this.speed();const terrainSlow=(this.region==='cinder'&&lavaAt(p.x,p.y))||(this.region==='hollow'&&riftAt(p.x,p.y,this.time).near&&riftAt(p.x,p.y,this.time).active);p.x+=vx*dt*(terrainSlow&&!this.dashing?.75:1);p.y+=vy*dt*(terrainSlow&&!this.dashing?.75:1);resolveTerrain(this.region,p);stepWorld(this,dt);
  this.spawnClock-=dt;const minute=this.time/60,difficulty=this.difficulty();if(this.spawnClock<=0&&this.enemies.length<difficulty.cap){this.spawnBudget+=difficulty.count;const count=Math.min(difficulty.cap-this.enemies.length,Math.floor(this.spawnBudget));this.spawnBudget-=Math.floor(this.spawnBudget);for(let i=0;i<count;i++){this.spawn(this.enemyType());}this.spawnClock=difficulty.interval;}

  if(this.time>=this.nextElite){this.spawn('brute',true);this.nextElite=this.time+60;this.emit('warning',{text:'An ancient one approaches · Treasure awaits'});}
  if(this.time>=this.nextBoss&&this.time>=600){if(!this.enemies.some(e=>e.boss&&e.hp>0))spawnOverlord(this);else this.nextBoss=this.time+5;}
  if(this.time>=this.nextBoss&&this.time<600&&this.enemies.some(e=>e.boss&&e.hp>0))this.nextBoss=this.time+5;
  if(this.time>=this.nextBoss&&this.time<600){this.bossSpawned=true;const boss=this.spawn('brute',false,true);if(this.region==='ashwood')boss.title=['The Hollow King','The Thorn Sovereign','The Cinder Colossus'][Math.floor(this.time/180-1)%3];this.nextBoss=this.time+180;this.emit('warning',{text:boss.title+' has awakened'});}
  if(this.time>=this.nextCache){const a=this.random()*TAU;this.pickups.push({...safePoint(this.region,p.x+Math.cos(a)*240,p.y+Math.sin(a)*240),kind:'cache'});this.nextCache+=75;this.emit('cache');}
  if(this.time>=this.nextHeal){const a=this.random()*TAU;this.pickups.push({...safePoint(this.region,p.x+Math.cos(a)*130,p.y+Math.sin(a)*130),kind:this.nextHeal%70===0?'magnet':'heal'});this.nextHeal+=35;}
  const waveMinute=Math.floor(minute);if(waveMinute>this.waveMinute){this.waveMinute=waveMinute;const arrivals=Object.entries(ENEMIES).filter(([,s])=>s.minute===waveMinute&&(s.region||'ashwood')===this.region);for(const [id]of arrivals)for(let i=0;i<2&&this.enemies.length<difficulty.cap;i++)this.spawn(id);if(arrivals.length)this.emit('warning',{text:`MINUTE ${waveMinute} · ${arrivals.map(([,s])=>s.name).join(' & ')} arrive`});}
  this.coinClock+=dt;if(this.coinClock>=5){this.gainGold(2);this.coinClock-=5;}
  for(const e of this.enemies){if(e.hp<=0)continue;if(guardSite(this,e,dt))continue;e.slow=Math.max(0,e.slow-dt);e.flash=Math.max(0,e.flash-dt);e.attack-=dt;let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1,spd=e.speed*(e.slow>0?.35:1);
   spd=stepRegional(this,e,dt,dx,dy,d,spd);
   if(e.type==='shooter'&&d<620){spd=d<480?-spd:0;if(e.attack<=0){this.hazards.push({kind:'shot',x:e.x,y:e.y,vx:dx/d*170,vy:dy/d*170,r:5,life:6});e.attack=2.8;}}
   if(e.type==='charger'){if(e.attack<.7&&e.attack>0){spd=0;e.phase=1;e.ax=dx/d;e.ay=dy/d;}else if(e.attack<=0&&e.attack>-.55){e.phase=2;e.x+=e.ax*260*dt;e.y+=e.ay*260*dt;spd=0;}else if(e.attack<=-.55){e.attack=3.5;e.phase=0;}}
   if(e.lateBoss&&e.attack<=0)attackOverlord(this,e);
   if(e.type==='siege'&&e.attack<=0){if(this.hazards.filter(h=>h.kind==='eruption').length<8)this.hazards.push({kind:'eruption',x:p.x,y:p.y,r:48,life:1.6,max:1.6,damage:40+minute});e.attack=7;}
   if((e.boss||e.elite)&&!e.lateBoss&&!REGIONAL_ENEMIES[e.type]&&e.attack<=0){this.hazards.push({kind:'eruption',x:p.x,y:p.y,r:e.boss?72:52,life:1.1,max:1.1,damage:((e.boss?38:24)+minute*1.2)*(e.siteId?1.25:1)});if(e.elite)e.attack=3.5;}
   if(e.boss&&!e.lateBoss&&!REGIONAL_ENEMIES[e.type]&&e.attack<=0){for(let a=0;a<TAU;a+=TAU/12)this.hazards.push({kind:'shot',x:e.x,y:e.y,vx:Math.cos(a+this.time*.2)*130,vy:Math.sin(a+this.time*.2)*130,r:6,life:7});e.attack=e.siteId?2.5:3;this.burst(e.x,e.y,80,'#ed787e');}
   if(e.type==='reaver'||e.type==='stalker'){const side=Math.sin(this.time*1.8+e.id)*.65;e.x+=-dy/d*spd*side*dt;e.y+=dx/d*spd*side*dt;}if(e.type==='revenant')spd*=Math.sin(this.time*2+e.id)>.65?1.6:1;if(e.type==='harbinger')e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.008*dt);if(e.type==='leech')e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.025*dt);e.x+=dx/d*spd*dt;e.y+=dy/d*spd*dt;const oldX=e.x,oldY=e.y;resolveTerrain(this.region,e,e.r);if(Math.abs(e.x-oldX)>1)e.y+=Math.sign(dy||1)*spd*dt;if(Math.abs(e.y-oldY)>1)e.x+=Math.sign(dx||1)*spd*dt;resolveTerrain(this.region,e,e.r);
   if(d>950&&!e.boss&&!e.elite){const a=this.random()*TAU;e.x=p.x+Math.cos(a)*600;e.y=p.y+Math.sin(a)*600;}
   if(Math.hypot(p.x-e.x,p.y-e.y)<e.r+11&&this.invuln<=0){const damage=Math.max(2,this.enemyDamage(((e.lateBoss?65:e.boss?34:e.elite?26:(ENEMIES[e.type]?.damage||12))+minute)*(e.siteId?1.25:1))-this.armor()-(this.hero.id==='warden'?1:0));this.hurt(damage);if(this.g('thorns'))this.hit(e,this.g('thorns'),'gear');this.burst(p.x,p.y,26,'#fa8989',.2);}
  }
  for(const id of Object.keys(this.skills)){if(!WEAPONS.some(w=>w.id===id)||id==='orbit')continue;this.cd[id]=(this.cd[id]||0)-dt;if(this.cd[id]<=0)this.fire(id);}
  if(this.rank('orbit')){const rank=this.rank('orbit'),ev=this.evolved.includes('orbit'),count=ev?12:rank+1,r=(65+rank*5)*this.area();this.cd.orbit=(this.cd.orbit||0)-dt;if(this.cd.orbit<=0){for(let i=0;i<count;i++){const a=this.time*2.1+i*TAU/count,x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;this.aoe(x,y,20,18+(rank-1)*7,'orbit',5);}this.cd.orbit=.18*this.haste('orbit');}}
  for(const b of this.bullets){b.life-=dt;b.age=(b.age||0)+dt;if(b.id==='scythe'&&b.age>.8){if(!b.returning){b.returning=true;b.hit=[];}const d=Math.hypot(p.x-b.x,p.y-b.y)||1;b.vx=(p.x-b.x)/d*300;b.vy=(p.y-b.y)/d*300;if(d<14)b.life=0;}if(b.id==='wisp'){const t=this.nearest(b.x,b.y);if(t){const d=Math.hypot(t.x-b.x,t.y-b.y)||1;b.vx+=(t.x-b.x)/d*600*dt;b.vy+=(t.y-b.y)/d*600*dt;const speed=Math.hypot(b.vx,b.vy)||1;b.vx=b.vx/speed*220;b.vy=b.vy/speed*220;}}b.x+=b.vx*dt;b.y+=b.vy*dt;for(const e of this.enemies){if(e.hp<=0||b.hit.includes(e.id)||b.pierce<=0)continue;if((e.x-b.x)**2+(e.y-b.y)**2<(e.r+b.r+3)**2){b.hit.push(e.id);b.pierce--;this.hit(e,b.damage,b.id);}}}
  this.bullets=this.bullets.filter(b=>b.life>0&&b.pierce>0);
  for(const h of this.hazards){h.life-=dt;if(h.kind==='shot'){h.x+=h.vx*dt;h.y+=h.vy*dt;if(Math.hypot(h.x-p.x,h.y-p.y)<h.r+10&&this.invuln<=0){this.hurt(Math.max(3,this.enemyDamage(18+minute*.65)-this.armor()));h.life=0;}}else if(h.kind==='mine'){h.arm-=dt;if(h.arm<=0&&(h.life<=0||this.enemies.some(e=>e.hp>0&&Math.hypot(e.x-h.x,e.y-h.y)<h.trigger))){this.aoe(h.x,h.y,h.r,h.damage,h.id,25);this.burst(h.x,h.y,h.r,'#ffa778');h.life=0;}}else if(h.kind==='wave'){const radius=h.r*(1-h.life/h.max);for(const e of this.enemies)if(e.hp>0&&!h.hit.includes(e.id)&&Math.hypot(e.x-h.x,e.y-h.y)<radius+e.r){h.hit.push(e.id);this.hit(e,h.damage,h.id,35+this.rank('tide')*3);}}else if(h.kind==='eruption'){if(h.life<=0){if(Math.hypot(h.x-p.x,h.y-p.y)<h.r+10&&this.invuln<=0){this.hurt(Math.max(8,h.damage-this.armor()));}this.burst(h.x,h.y,h.r,h.color||'#ff6e58',.35);}}else if(h.life<=0){this.aoe(h.x,h.y,h.r,h.damage,h.id,20);this.burst(h.x,h.y,h.r,'#ecb3e5',.5);}}
  this.hazards=this.hazards.filter(h=>h.life>0);
  for(const fx of this.effects){fx.life-=dt;if(fx.kind==='fire'||fx.kind==='pool'){fx.tick-=dt;if(fx.tick<=0){this.aoe(fx.x,fx.y,fx.r,fx.damage||15,fx.id||'flame');if(fx.slow)for(const e of this.enemies)if(Math.hypot(e.x-fx.x,e.y-fx.y)<fx.r)e.slow=Math.max(e.slow,.7);fx.tick=.5;}}}this.effects=this.effects.filter(f=>f.life>0);
  for(const t of this.texts){t.life-=dt;t.y-=dt*20;}this.texts=this.texts.filter(t=>t.life>0);
  this.enemies=this.enemies.filter(e=>e.hp>0);
  for(const gem of this.gems){let dx=p.x-gem.x,dy=p.y-gem.y,d=Math.hypot(dx,dy);if(d<this.magnet()||gem.pull){gem.pull=true;gem.x+=dx/(d||1)*Math.min(d,dt*460);gem.y+=dy/(d||1)*Math.min(d,dt*460);if(d<18){this.xp+=gem.value*this.xpBonus();gem.value=0;}}}
  this.gems=this.gems.filter(g=>g.value>0);if(this.gems.length>450){let merged=this.gems.splice(0,150);let total=merged.reduce((s,g)=>s+g.value,0);this.gems.push({x:merged[75].x,y:merged[75].y,value:total,kind:'xp',born:Math.min(...merged.map(g=>g.born??this.time))});}
  for(const pick of this.pickups){if(pick.taken)continue;if(Math.hypot(pick.x-p.x,pick.y-p.y)<(pick.kind==='chest'?42:30)){if(pick.kind==='chest'){if(this.openChest(pick))break;continue;}pick.taken=true;if(pick.kind==='heal'){p.hp=Math.min(this.maxHp(),p.hp+30);this.emit('heal');}else if(pick.kind==='magnet'){this.gems.forEach(g=>g.pull=true);this.emit('magnet');}else {this.gainGold(25);this.xp+=30*this.xpBonus();this.emit('treasure');}}}
  this.pickups=this.pickups.filter(pick=>!pick.taken);const supplies=this.pickups.filter(pick=>pick.kind!=='chest').slice(-30),chests=this.pickups.filter(pick=>pick.kind==='chest');if(chests.length>40){const old=chests.splice(0,chests.length-40),keeper=chests[0];keeper.gold+=old.reduce((n,p)=>n+(p.gold||50)+40*(p.rewards||3),0);}this.pickups=[...supplies,...chests];
  if(this.mode==='chest')return;
  if(p.hp<=0){p.hp=0;this.mode='down';this.emit('down');return;}
  stepDiscoveries(this);if(this.mode!=='playing')return;
  stepObjective(this);if(this.mode!=='playing')return;
  if(this.xp>=this.need){this.xp-=this.need;this.level++;this.need=this.xpNeeded();this.offers();if(this.choices.every(id=>id==='healreward'||id==='goldreward')){this.gainGold(20);p.hp=Math.min(this.maxHp(),p.hp+5);this.choices=[];}else{this.mode='levelup';this.emit('levelup');}}
 }
}
