// Recorded CC0 combat and movement audio, adapted from Oathfire. Credits: audio/sfx/LICENSES.txt.
export const SPELL_SOUNDS={
 bolt:['cast-mark','impact-holy'],orbit:['cast-tether','impact-holy'],chain:['cast-storm','impact-storm'],nova:['cast-holy','impact-holy'],frost:['cast-frost','impact-frost'],flame:['cast-fireball','impact-fire'],dagger:['swing-sword','hit-sword-body'],meteor:['cast-forgefall','impact-stone'],spear:['swing-spear','hit-spear-body'],scythe:['swing-sword-heavy','hit-sword-armor'],mine:['cast-mine','impact-fire'],venom:['cast-thorns','impact-nature'],beam:['cast-overdrive','impact-storm'],wisp:['cast-grave','impact-grave'],axe:['swing-hammer','hit-hammer-body'],tide:['cast-quench','impact-water'],aegis:['cast-bulwark','impact-shell'],torrent:['cast-volley','impact-water'],chrono:['cast-reversal','impact-frost'],blood:['cast-grave','impact-grave'],solar:['cast-sunwall','impact-holy'],void:['cast-grave','impact-grave'],tempest:['cast-storm','impact-storm'],hourglass:['cast-reversal','impact-frost'],verdict:['cast-holy','impact-holy'],briar:['cast-briarstorm','impact-nature'],inferno:['cast-inferno','impact-fire'],hush:['cast-sanctuary','impact-grave'],compass:['cast-guide','impact-holy']
};
const EVENTS={tap:['gear-leather',.24],levelup:['rank-holy',.45],evolve:['rank-arcane',.7],treasure:['rank-command',.5],dash:['cast-windstep',.38],hurt:['hit-hammer-body',.7],heal:['cast-sanctuary',.42],warning:['rank-grave',.5],bossdown:['rank-holy',.75],reaperslain:['rank-command',.9],revive:['cast-reversal',.65],down:['impact-grave',.8],magnet:['cast-tether',.35],dawn:['rank-grave',.85]};
export class CombatFoley{
 constructor(ctx,{fetcher=(...args)=>fetch(...args)}={}){this.ctx=ctx;this.fetcher=fetcher;this.bus=ctx.createGain();this.bus.gain.value=.55;this.limiter=ctx.createDynamicsCompressor?.();if(this.limiter){this.limiter.threshold.value=-14;this.limiter.ratio.value=5;this.limiter.attack.value=.004;this.limiter.release.value=.12;this.bus.connect(this.limiter);this.limiter.connect(ctx.destination);}else this.bus.connect(ctx.destination);this.state='idle';this.buffers={};this.voices=new Set();this.choices=new Map();this.limits=new Map();this.enabled=true;this.played=0;this.dropped=0;this.maxVoices=0;this.lastPosition=null;this.walked=0;this.retryAt=0;this.heardHazards=new WeakSet();}
 async load(){if(this.state==='ready'||this.state==='loading'||Date.now()<this.retryAt)return;this.state='loading';try{const res=await this.fetcher('./audio/sfx/foley.json?v=27');if(!res.ok)throw Error('manifest');this.manifest=await res.json();await Promise.all(Object.entries(this.manifest.banks).map(async([id,b])=>{if(this.buffers[id])return;const r=await this.fetcher('./audio/sfx/'+b.file);if(!r.ok)throw Error(id);this.buffers[id]=await this.ctx.decodeAudioData(await r.arrayBuffer());}));this.state='ready';this.error='';}catch{this.state='unavailable';this.error='Sound effects unavailable offline until downloaded.';this.retryAt=Date.now()+5000;}}
 setEnabled(enabled){if(this.enabled===!!enabled)return;this.enabled=!!enabled;this.bus.gain.setTargetAtTime(this.enabled?.55:0,this.ctx.currentTime,.015);if(!this.enabled)this.stop();}
 limit(key,seconds){const now=this.ctx.currentTime;if(now-(this.limits.get(key)??-100)<seconds)return true;this.limits.set(key,now);return false;}
 cue(key,{gain=1,pan=0,priority=1,pitch=1}={}){
  if(!this.enabled||this.state!=='ready'||this.ctx.state!=='running'||gain<.01)return false;
  const clip=this.manifest.clips[key];if(!clip)return false;
  if(this.voices.size>=24){const expendable=[...this.voices].find(v=>v.priority<priority);if(!expendable){this.dropped++;return false;}expendable.source.stop();this.voices.delete(expendable);}
  const index=((this.choices.get(key)??-1)+1)%clip.variants.length;this.choices.set(key,index);const variant=clip.variants[index];
  const source=this.ctx.createBufferSource(),volume=this.ctx.createGain(),panner=this.ctx.createStereoPanner?.();source.buffer=this.buffers[clip.bank];source.playbackRate.value=pitch;source.loop=false;volume.gain.value=Math.min(1,gain);source.connect(volume);if(panner){panner.pan.value=Math.max(-.8,Math.min(.8,pan));volume.connect(panner);panner.connect(this.bus);}else volume.connect(this.bus);
  const voice={source,volume,panner,priority};this.voices.add(voice);this.maxVoices=Math.max(this.maxVoices,this.voices.size);source.onended=()=>{this.voices.delete(voice);source.disconnect();volume.disconnect();panner?.disconnect();};source.start(this.ctx.currentTime,variant.offset,variant.duration);this.played++;return true;
 }
 event(kind,data={},game=null){
  if(!this.enabled||this.state!=='ready')return;
  if(kind==='cast'||kind==='impact'){
   if(this.limit(kind,kind==='cast'?.085:.065)||this.limit(kind+':'+data.weapon,kind==='cast'?.25:.16))return;
   const family=SPELL_SOUNDS[data.weapon]||['cast-overdrive','impact-holy'];const distance=game?Math.hypot((data.x??game.player.x)-game.player.x,(data.y??game.player.y)-game.player.y):0;
   if(distance>700)return;this.cue(family[kind==='cast'?0:1],{gain:(kind==='cast'?.20:.17)/(1+distance/180),pan:game?((data.x??game.player.x)-game.player.x)/420:0,pitch:data.crit?.92:1,priority:1});return;
  }
  const cue=EVENTS[kind];if(!cue||this.limit('event:'+kind,kind==='warning'?3:.15))return;
  this.cue(cue[0],{gain:cue[1],priority:kind==='hurt'||kind==='warning'||kind==='down'?5:4});
 }
 update(game){if(!game||game.mode!=='playing'){this.lastPosition=null;return;}const p=game.player;for(const h of game.hazards||[]){if(!['shot','eruption'].includes(h.kind)||this.heardHazards.has(h))continue;this.heardHazards.add(h);const d=Math.hypot(h.x-p.x,h.y-p.y);if(d<550&&!this.limit('hostile',.9))this.cue(h.kind==='eruption'?'cast-grave':'cast-mine',{gain:.24/(1+d/250),pan:(h.x-p.x)/450,pitch:.83,priority:3});}if(this.lastPosition){const d=Math.hypot(p.x-this.lastPosition.x,p.y-this.lastPosition.y);if(d<80)this.walked+=d;}this.lastPosition={x:p.x,y:p.y};if(this.walked<35)return;this.walked%=35;if(this.limit('foot',.25))return;const surface=({ashwood:'grass',briarheart:'grass',frostmarch:'snow',drowned:'water',cinder:'dirt',hollow:'stone',clockwork:'stone',sunforge:'stone',eclipse:'stone',astral:'stone'})[game.region]||'grass';this.cue('step-'+surface,{gain:.16,priority:0,pitch:.96+(this.played%4)*.025});if(game.gear)this.cue('gear-'+(game.gear.tier>=4?'plate':'leather'),{gain:.08,priority:0});}
 stop(){for(const v of [...this.voices]){try{v.source.stop();}catch{}this.voices.delete(v);}this.lastPosition=null;}
 status(){return {state:this.state,enabled:this.enabled,voices:this.voices.size,maxVoices:this.maxVoices,played:this.played,dropped:this.dropped,error:this.error||''};}
}
