import {THEMES,scoreState,scoreNotes,scorePosition} from './score.js?v=26';
export {THEMES,scoreState,scoreNotes,scorePosition} from './score.js?v=26';
export function musicSettings(settings={}){return {enabled:typeof settings.music==='boolean'?settings.music:settings.sound!==false,volume:Number.isFinite(settings.musicVolume)?Math.max(0,Math.min(1,settings.musicVolume)):.4};}
const frequency=midi=>440*2**((midi-69)/12);
export class AdaptiveMusic{
 constructor(context){this.context=context;this.master=context.createGain();this.master.gain.value=0;this.filter=context.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=6000;this.compressor=context.createDynamicsCompressor();this.compressor.threshold.value=-18;this.compressor.ratio.value=5;this.master.connect(this.filter);this.filter.connect(this.compressor);this.compressor.connect(context.destination);if(context.createConvolver){const room=context.createConvolver(),wet=context.createGain(),ir=context.createBuffer(2,Math.floor(context.sampleRate*1.3),context.sampleRate);for(let ch=0;ch<2;ch++){const a=ir.getChannelData(ch);let seed=177+ch*71;for(let j=0;j<a.length;j++){seed=(seed*16807)%2147483647;a[j]=(seed/2147483647*2-1)*Math.exp(-j/context.sampleRate*6)*.28;}}room.buffer=ir;wet.gain.value=.18;this.filter.connect(room);room.connect(wet);wet.connect(this.compressor);}this.voices=new Set();this.running=false;this.region=null;this.step=0;this.next=0;this.scheduled=0;this.seconds=0;this.scoreSeconds=0;this.sectionStart=0;this.timbres=new Map();this.volume=0;this.noise=context.createBuffer(1,context.sampleRate,context.sampleRate);const data=this.noise.getChannelData(0);let seed=7341;for(let i=0;i<data.length;i++){seed=(seed*16807)%2147483647;data[i]=(seed/2147483647)*2-1;}}
 update(region,seconds,playing,settings,hidden=false){const options=musicSettings(settings);this.seconds=seconds||0;this.volume=options.volume;if(!playing||hidden||!options.enabled||options.volume===0||this.context.state!=='running'){this.stop();return;}
  const now=this.context.currentTime;if(!this.running||this.region!==region){this.stop();this.running=true;this.region=region;this.step=0;this.sectionStart=0;this.scoreSeconds=seconds;this.next=now+.035;this.master.gain.cancelScheduledValues(now);this.master.gain.setValueAtTime(0,now);}
  this.master.gain.setTargetAtTime(options.volume*.55,now,.12);
  // Do not replay a backlog after an interrupted audio device or background tab.
  if(this.next<now-.2)this.next=now+.035;
  let budget=8;while(this.next<now+.18&&budget-->0){if(this.step%64===0&&scoreState(region,seconds).act!==scoreState(region,this.scoreSeconds).act){this.scoreSeconds=seconds;this.sectionStart=this.step;}for(const note of scoreNotes(region,this.scoreSeconds,this.step-this.sectionStart))this.note(note,this.next+(note.delay||0));this.step++;this.next+=60/scoreState(region,this.scoreSeconds).bpm/4;}
 }
 note(n,when){if(this.voices.size>=64)return;const c=this.context,gain=c.createGain(),filter=c.createBiquadFilter();let source;const noisy=['hat','snare','cymbal'].includes(n.voice);filter.type=noisy?'highpass':'lowpass';filter.frequency.value=n.voice==='hat'?6500:n.voice==='snare'?1400:n.voice==='bass'?1200:THEMES[this.region]?.cutoff||1800;
  if(noisy){source=c.createBufferSource();source.buffer=this.noise;}else{source=c.createOscillator();source.type=n.wave;const partials={reed:[1,.38,.22,.13,.07],flute:[1,.12,.2,.04],bell:[1,.05,.45,.02,.2],pluck:[1,.55,.26,.14,.08,.03],marimba:[1,.02,.34,.01,.08],strings:[1,.5,.32,.21,.15,.1,.07],brass:[1,.7,.5,.32,.22,.14],choir:[1,.15,.4,.1,.2],bass:[1,.25,.1]}[n.instrument];if(partials&&c.createPeriodicWave&&source.setPeriodicWave){if(!this.timbres.has(n.instrument))this.timbres.set(n.instrument,c.createPeriodicWave(new Float32Array(partials.length+1),new Float32Array([0,...partials])));source.setPeriodicWave(this.timbres.get(n.instrument));}source.frequency.setValueAtTime(n.voice==='kick'?125:frequency(n.midi),when);if(n.voice==='kick')source.frequency.exponentialRampToValueAtTime(42,when+.17);}
  const attack=n.attack??(n.voice==='pad'?.16:({strings:.06,reed:.02,flute:.035,brass:.022,choir:.1,pluck:.004,marimba:.004,bell:.004}[n.instrument]||.008));gain.gain.setValueAtTime(.0001,when);gain.gain.exponentialRampToValueAtTime(n.gain,when+Math.min(attack,n.duration/3));if(n.hold)gain.gain.setValueAtTime(n.gain*.7,when+n.duration*n.hold);gain.gain.exponentialRampToValueAtTime(.0001,when+n.duration);source.connect(filter);filter.connect(gain);const pan=c.createStereoPanner?.();if(pan){pan.pan.value=n.pan||0;gain.connect(pan);pan.connect(this.master);}else gain.connect(this.master);
  const voice={source,gain,filter};this.voices.add(voice);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();pan?.disconnect();this.voices.delete(voice);};source.start(when);source.stop(when+n.duration+.02);this.scheduled++;
 }
 stop(){if(!this.running)return;const now=this.context.currentTime;this.master.gain.cancelScheduledValues(now);this.master.gain.setTargetAtTime(0,now,.025);for(const v of this.voices){try{v.source.stop(now+.1);}catch{}}this.running=false;}
 status(){const s=scoreState(this.region,this.scoreSeconds);return {playing:this.running,context:this.context.state,region:this.region,theme:this.region?s.theme.name:null,intensity:s.intensity,act:s.actName,bpm:s.bpm,volume:this.volume,...scorePosition(this.step-this.sectionStart),voices:this.voices.size,scheduledNotes:this.scheduled};}
}
