// Guaranteed boss trophies unlock combat weapons; they never consume equipment slots.
export const RELIC_WEAPONS=[
 {id:'tempest',name:'Thunder crown',icon:'♛',color:'#a8eaff',desc:'Independent lightning strikes bombard several enemy clusters at once.',base:'110 damage · 3 strikes every 2.8s',upgrade:'More lightning strikes and blast damage.',evo:'Storm sovereign',pair:'power',evoDesc:'A storm of six broad lightning strikes shatters separate enemy clusters.',unlock:'Defeat the 20-minute overlord on any map',feat:'overlord20'},
 {id:'hourglass',name:'Hourglass cannon',icon:'◴',color:'#a8f1ed',desc:'Heavy piercing shells slow enemies and briefly freeze the Last Eclipse on impact.',base:'118 damage · 12 pierces · every 2.6s',upgrade:'Heavier shells, deeper piercing and longer control.',evo:'End of ages',pair:'haste',evoDesc:'Twin temporal shells tear through the crowd and arrest the Last Eclipse.',unlock:'Defeat the 25-minute overlord on any map',feat:'overlord25'},
 {id:'verdict',name:'Reaper’s verdict',icon:'⚔',color:'#dbc5ff',desc:'Crossing spectral blades cut through the nearest enemy and the crowd around it.',base:'140 damage per crossing blade · every 3.6s',upgrade:'Longer, wider and much stronger blades.',evo:'Final sentence',pair:'precision',evoDesc:'Three immense crossing blades pronounce judgment on everything in their path.',unlock:'Defeat the Last Eclipse at 30 minutes on any map',feat:'reaper'},
 {id:'briar',name:'Briar vengeance',icon:'❋',color:'#bce99a',desc:'Bramble pulses push back nearby foes. Taking damage triggers a free retaliation pulse.',base:'90 damage · 150 radius · every 3.2s',upgrade:'Wider pulses, greater damage and stronger retaliation.',evo:'Thorn sovereign',pair:'guard',evoDesc:'Vast bramble pulses heal on hitting a crowd; retaliation strikes twice as hard.',unlock:'Defeat the Vaultroot Sentinel guarding a Sealed vault in Ashwood',feat:'ashVault'},
 {id:'inferno',name:'Furnace comet',icon:'☄',color:'#ffc27e',desc:'Fireballs burst on first impact, leaving a pool of burning embers.',base:'104 impact damage + blast · every 3s',upgrade:'Larger impact blasts, stronger fire and more comets.',evo:'World furnace',pair:'reach',evoDesc:'Three fireballs ignite enormous, persistent fields of flame.',unlock:'Defeat the Crater Hoardkeeper guarding a Sealed vault in Cinder Wastes',feat:'cinderVault'}
];
export const WEAPON_FEATS=['overlord20','overlord25','ashVault','cinderVault'];
export function recordWeaponVictory(g,e){if(!e.boss)return;g.weaponFeats??={};if(e.milestone===20||e.milestone===25)g.weaponFeats['overlord'+e.milestone]=1;const site=e.siteId&&g.discoveries.find(s=>s.id===e.siteId);if(site?.kind==='vault'&&g.region==='ashwood')g.weaponFeats.ashVault=1;if(site?.kind==='vault'&&g.region==='cinder')g.weaponFeats.cinderVault=1;}
export function briarPulse(g,retaliation=false){const rank=g.rank('briar');if(!rank)return;const ev=g.evolved.includes('briar'),p=g.player,r=(135+rank*15)*(ev?1.35:1)*g.spellArea('briar'),damage=(65+rank*25)*(retaliation?(ev?2:1.3)*(1+g.craft('briar','retaliation')*.15):1);const count=g.enemies.filter(e=>e.hp>0&&Math.hypot(e.x-p.x,e.y-p.y)<r).length;g.aoe(p.x,p.y,r,damage,'briar',60);g.burst(p.x,p.y,r,'#bce99a',.6);if(ev&&count>=3)p.hp=Math.min(g.maxHp(),p.hp+4);}
export function fireRelicWeapon(g,id){if(!RELIC_WEAPONS.some(w=>w.id===id))return false;const rank=g.rank(id),ev=g.evolved.includes(id),p=g.player,t=g.nearest(),area=g.spellArea(id),extra=g.craft(id,'projectiles');
 if(id==='briar'){briarPulse(g);g.cd[id]=(ev?2.4:3.2)*g.haste(id);return true;}
 if(!t){g.cd[id]=.2;return true;}
 if(id==='tempest'){const targets=g.enemies.filter(e=>e.hp>0).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y)).slice(0,(ev?6:3+Math.floor((rank-1)/3))+extra);for(const e of targets){const r=(ev?100:55+rank*3)*area;g.aoe(e.x,e.y,r,80+rank*30,id,15);g.effects.push({kind:'chain',points:[{x:e.x-25,y:e.y-180},{x:e.x+20,y:e.y-90},{x:e.x,y:e.y}],color:'#a8eaff',life:.4,max:.4});g.burst(e.x,e.y,r,'#a8eaff');}g.cd[id]=(ev?2.1:2.8)*g.haste(id);}
 if(id==='verdict'){const count=(ev?3:2)+extra,length=(240+rank*22)*area,width=(14+rank*2)*(1+g.craft(id,'width')*.15),aim=Math.atan2(t.y-p.y,t.x-p.x);for(let j=0;j<count;j++){const a=aim+Math.PI*j/count,dx=Math.cos(a),dy=Math.sin(a),x=t.x-dx*length,y=t.y-dy*length;for(const e of g.enemies){const ex=e.x-t.x,ey=e.y-t.y;if(Math.abs(ex*dx+ey*dy)<length&&Math.abs(-ex*dy+ey*dx)<width+e.r)g.hit(e,(100+rank*40)*(ev?1.35:1),id);}g.effects.push({kind:'beam',x,y,angle:a,r:length*2,width,color:'#dbc5ff',life:.45,max:.45});}g.cd[id]=3.6*g.haste(id);}
 if(id==='hourglass'||id==='inferno'){const count=(id==='hourglass'?(ev?2:1):(ev?3:1+Math.floor((rank-1)/4)))+extra,a=Math.atan2(t.y-p.y,t.x-p.x);for(let j=0;j<count;j++){const angle=a+(j-(count-1)/2)*.23;g.bullets.push({x:p.x,y:p.y,vx:Math.cos(angle)*300,vy:Math.sin(angle)*300,r:id==='hourglass'?13:10,life:3,damage:id==='hourglass'?90+rank*28:80+rank*24,id,pierce:id==='hourglass'?10+rank*2:1,hit:[],color:id==='hourglass'?'#a8f1ed':'#ffc27e'});}g.cd[id]=(id==='hourglass'?2.6:3)*g.haste(id);}
 return true;
}
export function relicImpact(g,b,e){if(b.id==='hourglass')g.chill(e,2+g.rank(b.id)*.2,(g.evolved.includes(b.id)?2.8:1+g.rank(b.id)*.12),1+g.craft(b.id,'duration')*.2);if(b.id==='inferno'){const rank=g.rank(b.id),ev=g.evolved.includes(b.id),r=(65+rank*7)*(ev?1.3:1)*g.spellArea(b.id),life=(ev?5:3)+g.craft(b.id,'duration')*.6;g.aoe(e.x,e.y,r,60+rank*18,b.id,20);g.effects.push({kind:'pool',x:e.x,y:e.y,r,life,max:life,tick:0,damage:18+rank*5,id:b.id,color:'#ffc27e'});g.burst(e.x,e.y,r,'#ffc27e');}}
