const TAU=Math.PI*2;
const sprite=(rows,palette,scale=2)=>{const c=document.createElement('canvas');c.width=rows[0].length*scale;c.height=rows.length*scale;const x=c.getContext('2d');rows.forEach((r,y)=>[...r].forEach((v,k)=>{if(palette[v]){x.fillStyle=palette[v];x.fillRect(k*scale,y*scale,scale,scale);}}));return c;};
export function heroSprite(color='#eab66c') {return sprite(['.....aaa.....','....aaaaa....','...aabbbaa...','...abcccba...','...abcdcba...','....bcccb....','...aabeaaa...','..aaeeeeeaa..','.aaaeeeeeaaa.','..aaeeeeeaa..','...aeeeeeaa..','...aaeeeaaa..','....ff.ff....','....ff.ff....'],{a:color,b:'#493946',c:'#2d343d',d:'#ffe8b7',e:'#314b49',f:'#222c33'},3);}
const foes={
 crawler:sprite(['....aaa....','..aaaaaaa..','.aabbbbaaa.','.aabdbdbaa.','aaabbbbaaaa','aaaabbbbaaa','.aaa..aaaa.','..aa..aaa..'],{a:'#809b8c',b:'#405c55',d:'#facd94'},3),
 bat:sprite(['a.........a','aa.......aa','aaa..b..aaa','.aaabbbbaa.','..aabdbbaa.','...bbbb...','....bb....'],{a:'#7f849b',b:'#a6a2c1',d:'#ffe0bd'},3),
 brute:sprite(['....aaaa....','...aabbaaa..','..aabbbbbaa.','.aabdbdbbaa.','aaabbbbbbaaa','aaabbbbbbaaa','aaabbbbbbaaa','.aabbbbbbaa.','..aaabaaaba.','...aa..aaa..','...aa..aaa..'],{a:'#876c7b',b:'#ba8997',d:'#ffe2a0'},3),
 shooter:sprite(['....aa....','..aaaaaa..','.aaaaaaba.','aabaaaabaa','aaaaaaaaaa','...cccc...','...cdcc...','...cccc...','..cccccc..'],{a:'#bdb188',b:'#ecdec1',c:'#607878',d:'#f4bbaa'},3),
 charger:sprite(['.....aa.....','...aaaaaa...','..aabbbaaa..','.aabdbdbaa..','aaaabbbbaaaa','..aabbbbaa..','...abbbaa...','..aa...aa...','.aa.....aa..'],{a:'#c29170',b:'#775f59',d:'#fff1c3'},3)
};
export class Renderer {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.sprites={};this.ground=new Image();this.ground.src="ground.jpg";this.resize();}
 resize(){this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=this.w*this.dpr;this.canvas.height=this.h*this.dpr;this.zoom=Math.min(this.w/860,this.h/485);}
 draw(game,settings,input,now){const c=this.ctx,w=this.w,h=this.h,zoom=this.zoom;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.fillStyle=game.region==='hollow'?'#17212f':game.region==='cinder'?'#302723':'#14292a';c.fillRect(0,0,w,h);const p=game.player;let shake=game.invuln>.57&&game.invuln<.69&&settings.shake?3:0;
 c.save();c.translate(w/2+(Math.random()-.5)*shake,h/2);c.scale(zoom,zoom);c.translate(-p.x,-p.y);const left=p.x-w/2/zoom,top=p.y-h/2/zoom,right=p.x+w/2/zoom,bottom=p.y+h/2/zoom;
 if(this.ground.complete&&this.ground.naturalWidth){c.globalAlpha=.68;for(let tx=Math.floor(left/512);tx<=Math.floor(right/512);tx++)for(let ty=Math.floor(top/512);ty<=Math.floor(bottom/512);ty++)c.drawImage(this.ground,tx*512,ty*512,512,512);c.globalAlpha=1;}
 const hash=(x,y)=>{let t=Math.sin(x*127.1+y*311.7)*43758.5453;return t-Math.floor(t);};
 for(let gx=Math.floor(left/85);gx<=Math.ceil(right/85);gx++)for(let gy=Math.floor(top/85);gy<=Math.ceil(bottom/85);gy++){let r=hash(gx,gy),x=gx*85+r*55,y=gy*85+hash(gy,gx)*55;c.fillStyle=game.region==='hollow'?'#283044':game.region==='cinder'?'#45332a':'#223c37';c.fillRect(x,y,3,8);c.fillRect(x-5,y+3,3,5);c.fillRect(x+5,y+2,3,4);if(r>.8){c.fillStyle='#456057';c.globalAlpha=.35;c.fillRect(x+20,y+15,8,3);c.globalAlpha=1;}if(r<.12){c.strokeStyle='#294341';c.lineWidth=2;c.beginPath();c.ellipse(x,y,34,16,0,0,TAU);c.stroke();}}
 // Ancient circular trail markers lend the endless field its bearings.
 for(let gx=Math.floor(left/440);gx<=Math.ceil(right/440);gx++)for(let gy=Math.floor(top/440);gy<=Math.ceil(bottom/440);gy++){let x=gx*440+110,y=gy*440+90;c.strokeStyle='#456153';c.globalAlpha=.17;c.lineWidth=7;c.beginPath();c.arc(x,y,47,0,TAU);c.stroke();c.lineWidth=2;c.beginPath();c.arc(x,y,36,0,TAU);c.stroke();c.globalAlpha=1;}
 c.imageSmoothingEnabled=false;
 for(const g of game.gems){if(g.x<left-10||g.x>right+10||g.y<top-10||g.y>bottom+10)continue;let size=g.value>10?6:g.value>3?4.5:3;c.fillStyle=g.value>10?'#c7a5ff':'#66d9cf';c.save();c.translate(g.x,g.y);c.rotate(Math.PI/4);c.fillRect(-size,-size,size*2,size*2);c.fillStyle='#d1fff2';c.fillRect(-size,-size,size,2);c.restore();}
 for(const pk of game.pickups){c.save();c.translate(pk.x,pk.y);c.fillStyle=pk.kind==='cache'?'#ffbc68':pk.kind==='heal'?'#a9efaa':'#8ddbe8';c.globalAlpha=.12;c.beginPath();c.arc(0,0,24+Math.sin(now*3)*3,0,TAU);c.fill();c.globalAlpha=1;c.font='bold 25px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(pk.kind==='cache'?'▣':pk.kind==='heal'?'+':'◇',0,0);c.restore();}
 for(const hz of game.hazards){if(hz.kind==='shot'){c.fillStyle='#fa8f85';c.beginPath();c.arc(hz.x,hz.y,hz.r+2,0,TAU);c.fill();c.fillStyle='#ffe1ba';c.beginPath();c.arc(hz.x,hz.y,hz.r/2,0,TAU);c.fill();}else{c.strokeStyle='#dca3ed';c.lineWidth=2;c.beginPath();c.arc(hz.x,hz.y,hz.r,0,TAU);c.stroke();c.globalAlpha=.2;c.fillStyle='#dca3ed';c.fill();c.globalAlpha=1;}}
 for(const e of game.enemies){if(e.x<left-60||e.x>right+60||e.y<top-60||e.y>bottom+60)continue;const s=foes[e.type];const factor=e.boss?3:e.elite?1.55:1;const bob=Math.sin(now*(e.type==='bat'?13:7)+e.id)*2;c.fillStyle='#081b1b70';c.beginPath();c.ellipse(e.x,e.y+7,15*factor,6*factor,0,0,TAU);c.fill();if(e.phase===1){c.strokeStyle='#ff9989';c.lineWidth=3;c.setLineDash([5,4]);c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.x+e.ax*130,e.y+e.ay*130);c.stroke();c.setLineDash([]);}c.globalAlpha=e.flash?0.6:1;c.drawImage(s,e.x-s.width/2*factor,e.y-s.height*.8*factor+bob,s.width*factor,s.height*factor);c.globalAlpha=1;if(e.slow){c.strokeStyle='#9feaff';c.beginPath();c.ellipse(e.x,e.y+6,17*factor,8*factor,0,0,TAU);c.stroke();}if(e.elite||e.boss){c.fillStyle='#141c22';c.fillRect(e.x-23*factor,e.y-34*factor,46*factor,4);c.fillStyle=e.boss?'#ed919c':'#ffcf7e';c.fillRect(e.x-23*factor,e.y-34*factor,46*factor*e.hp/e.maxHp,4);}}
 c.globalAlpha=settings.fx;
 for(const fx of game.effects){c.strokeStyle=fx.color||'#ff9f63';c.fillStyle=fx.color||'#ff9f63';let progress=1-fx.life/fx.max;c.globalAlpha=settings.fx*(1-progress*.8);if(fx.kind==='chain'){c.lineWidth=3;c.beginPath();fx.points.forEach((pt,i)=>{if(i===0)c.moveTo(pt.x,pt.y);else{const prev=fx.points[i-1];c.lineTo((pt.x+prev.x)/2+5,(pt.y+prev.y)/2-7);c.lineTo(pt.x,pt.y);}});c.stroke();}else if(fx.kind==='flame'){c.beginPath();c.moveTo(fx.x,fx.y);c.arc(fx.x,fx.y,fx.r*(.8+progress*.2),fx.full?0:fx.angle-.8,fx.full?TAU:fx.angle+.8);c.closePath();c.globalAlpha*=.32;c.fill();}else if(fx.kind==='fire'){c.globalAlpha*=.17;c.beginPath();c.arc(fx.x,fx.y,fx.r,0,TAU);c.fill();}else {c.lineWidth=3;c.beginPath();c.arc(fx.x,fx.y,fx.r*(.6+progress*.4),0,TAU);c.stroke();c.globalAlpha*=.08;c.fill();}}
 c.globalAlpha=1;
 for(const b of game.bullets){c.strokeStyle=b.color;c.lineWidth=b.r;c.lineCap='round';c.beginPath();c.moveTo(b.x-b.vx*.03,b.y-b.vy*.03);c.lineTo(b.x,b.y);c.stroke();c.lineCap='butt';}
 if(game.rank('orbit')){let rank=game.rank('orbit'),ev=game.evolved.includes('orbit'),n=ev?7:rank+1,r=(65+rank*5)*game.area();c.strokeStyle='#b2acf1';c.globalAlpha=.13;c.lineWidth=1;c.beginPath();c.arc(p.x,p.y,r,0,TAU);c.stroke();c.globalAlpha=1;for(let i=0;i<n;i++){let a=game.time*2.1+i*TAU/n;c.save();c.translate(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r);c.rotate(a+Math.PI/4);c.fillStyle=ev?'#efe7ff':'#bfb3ff';c.fillRect(-4,-12,8,24);c.fillStyle='#fff';c.fillRect(-2,-10,3,17);c.restore();}}
 // Player outline and indicator always render above effects.
 c.fillStyle='#06181980';c.beginPath();c.ellipse(p.x,p.y+10,17,7,0,0,TAU);c.fill();c.strokeStyle=game.invuln>0?'#ffe7b4':'#adf1d6';c.globalAlpha=.7;c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y+8,20,10,0,0,TAU);c.stroke();c.globalAlpha=game.invuln>0?(Math.sin(now*22)>.3?.6:1):1;let hero=this.sprites[game.hero.id]||(this.sprites[game.hero.id]=heroSprite(game.hero.color));c.drawImage(hero,p.x-hero.width/2,p.y-hero.height+12+(Math.hypot(input.x,input.y)>.1?Math.sin(now*15)*2:0));c.globalAlpha=1;
 if(game.invuln>1){c.strokeStyle='#ffe2a7';c.lineWidth=1.5;c.beginPath();c.arc(p.x,p.y-6,27,0,TAU);c.stroke();}
 for(const t of game.texts){c.globalAlpha=Math.min(1,t.life*3);c.fillStyle=t.color;c.font='bold 14px sans-serif';c.textAlign='center';c.fillText(t.text,t.x,t.y);}c.globalAlpha=1;
 c.restore();
 // Draw offscreen supply arrows in screen space.
 for(const pk of game.pickups.filter(p=>p.kind==='cache').slice(-2)){let sx=(pk.x-p.x)*zoom+w/2,sy=(pk.y-p.y)*zoom+h/2;if(sx<35||sx>w-35||sy<75||sy>h-60){const a=Math.atan2(sy-h/2,sx-w/2),rx=Math.min(w/2-40,(h/2-70)/Math.max(.1,Math.abs(Math.sin(a)))) ;let x=w/2+Math.cos(a)*rx,y=Math.max(78,Math.min(h-60,h/2+Math.sin(a)*rx));x=Math.max(35,Math.min(w-35,x));c.save();c.translate(x,y);c.fillStyle='#ffce84';c.font='20px sans-serif';c.textAlign='center';c.fillText('▣',0,0);c.font='11px sans-serif';c.fillText(Math.round(Math.hypot(pk.x-p.x,pk.y-p.y))+'m',0,16);c.restore();}}
 const vignette=c.createRadialGradient(w/2,h/2,h*.25,w/2,h/2,w*.65);vignette.addColorStop(0,'#07141900');vignette.addColorStop(1,'#07141966');c.fillStyle=vignette;c.fillRect(0,0,w,h);
 }
}
