const TAU=Math.PI*2;
const atlas=new Image();atlas.src='sprites.png';const enemyAtlas=new Image();enemyAtlas.src='enemies-v7.png';export const artReady=Promise.all([atlas.decode(),enemyAtlas.decode()]).catch(()=>{});
const enemyRects={ironhide:[12,16,495,480],reaver:[531,10,493,482],revenant:[1060,0,454,492],juggernaut:[0,496,512,512],leech:[529,510,495,494],champion:[1050,500,464,506]};
const enemyHeights={ironhide:49,reaver:49,revenant:53,juggernaut:72,leech:50,champion:57};
const rectangles={ranger:[105,99,190,212],warden:[446,87,233,225],witch:[850,90,194,222],sage:[1236,83,205,234],crawler:[94,429,219,192],bat:[448,447,261,147],brute:[824,413,242,222],shooter:[1266,420,169,206],charger:[92,720,222,223],boss:[472,686,214,251],chest:[843,749,207,165],rune:[1256,705,165,248]};
const detailed={};function art(id){const source=enemyRects[id]?enemyAtlas:atlas,rect=enemyRects[id]||rectangles[id];if(!source.naturalWidth||!rect)return null;if(detailed[id])return detailed[id];const [x,y,w,h]=rect,canvas=document.createElement('canvas');canvas.width=w+4;canvas.height=h+4;canvas.getContext('2d').drawImage(source,x-2,y-2,w+4,h+4,0,0,w+4,h+4);return detailed[id]=canvas;}
function paint(c,id,x,y,height,flip=false,tilt=0){const source=art(id);if(!source)return false;const width=height*source.width/source.height;c.save();c.translate(x,y);if(flip)c.scale(-1,1);if(tilt)c.rotate(tilt);c.drawImage(source,-width/2,-height+12,width,height);c.restore();return true;}
const glow=document.createElement('canvas');glow.width=glow.height=64;const gc=glow.getContext('2d'),gr=gc.createRadialGradient(32,32,0,32,32,32);gr.addColorStop(0,'#ffe9aa80');gr.addColorStop(.3,'#ffb64b30');gr.addColorStop(1,'#ffb64b00');gc.fillStyle=gr;gc.fillRect(0,0,64,64);
const sprite=(rows,palette,scale=2)=>{const c=document.createElement('canvas');c.width=rows[0].length*scale;c.height=rows.length*scale;const x=c.getContext('2d');rows.forEach((r,y)=>[...r].forEach((v,k)=>{if(palette[v]){x.fillStyle=palette[v];x.fillRect(k*scale,y*scale,scale,scale);}}));return c;};
export function heroSprite(color='#eab66c',id='ranger') {if(art(id))return art(id);return sprite(['.....aaa.....','....aaaaa....','...aabbbaa...','...abcccba...','...abcdcba...','....bcccb....','...aabeaaa...','..aaeeeeeaa..','.aaaeeeeeaaa.','..aaeeeeeaa..','...aeeeeeaa..','...aaeeeaaa..','....ff.ff....','....ff.ff....'],{a:color,b:'#493946',c:'#2d343d',d:'#ffe8b7',e:'#314b49',f:'#222c33'},3);}
const foes={
 crawler:sprite(['....aaa....','..aaaaaaa..','.aabbbbaaa.','.aabdbdbaa.','aaabbbbaaaa','aaaabbbbaaa','.aaa..aaaa.','..aa..aaa..'],{a:'#809b8c',b:'#405c55',d:'#facd94'},3),
 bat:sprite(['a.........a','aa.......aa','aaa..b..aaa','.aaabbbbaa.','..aabdbbaa.','...bbbb...','....bb....'],{a:'#7f849b',b:'#a6a2c1',d:'#ffe0bd'},3),
 brute:sprite(['....aaaa....','...aabbaaa..','..aabbbbbaa.','.aabdbdbbaa.','aaabbbbbbaaa','aaabbbbbbaaa','aaabbbbbbaaa','.aabbbbbbaa.','..aaabaaaba.','...aa..aaa..','...aa..aaa..'],{a:'#876c7b',b:'#ba8997',d:'#ffe2a0'},3),
 shooter:sprite(['....aa....','..aaaaaa..','.aaaaaaba.','aabaaaabaa','aaaaaaaaaa','...cccc...','...cdcc...','...cccc...','..cccccc..'],{a:'#bdb188',b:'#ecdec1',c:'#607878',d:'#f4bbaa'},3),
 charger:sprite(['.....aa.....','...aaaaaa...','..aabbbaaa..','.aabdbdbaa..','aaaabbbbaaaa','..aabbbbaa..','...abbbaa...','..aa...aa...','.aa.....aa..'],{a:'#c29170',b:'#775f59',d:'#fff1c3'},3)
};
export class Renderer {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.sprites={};this.ground=new Image();this.ground.src="ground.jpg";this.resize();}
 resize(){this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=this.w*this.dpr;this.canvas.height=this.h*this.dpr;this.zoom=Math.min(this.w/860,this.h/485);}
 draw(game,settings,input,now){const c=this.ctx,w=this.w,h=this.h,zoom=this.zoom;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.fillStyle=game.region==='hollow'?'#17212f':game.region==='cinder'?'#302723':'#14292a';c.fillRect(0,0,w,h);const p=game.player;let shake=game.invuln>.57&&game.invuln<.69&&settings.shake?3:0;
 c.save();c.translate(w/2+(Math.random()-.5)*shake,h/2);c.scale(zoom,zoom);c.translate(-p.x,-p.y);const left=p.x-w/2/zoom,top=p.y-h/2/zoom,right=p.x+w/2/zoom,bottom=p.y+h/2/zoom;
 if(this.ground.complete&&this.ground.naturalWidth){c.globalAlpha=.68;for(let tx=Math.floor(left/512);tx<=Math.floor(right/512);tx++)for(let ty=Math.floor(top/512);ty<=Math.floor(bottom/512);ty++)c.drawImage(this.ground,tx*512,ty*512,512,512);c.globalAlpha=1;}
 const hash=(x,y)=>{let t=Math.sin(x*127.1+y*311.7)*43758.5453;return t-Math.floor(t);};
 for(let gx=Math.floor(left/85);gx<=Math.ceil(right/85);gx++)for(let gy=Math.floor(top/85);gy<=Math.ceil(bottom/85);gy++){let r=hash(gx,gy),x=gx*85+r*55,y=gy*85+hash(gy,gx)*55;c.fillStyle=game.region==='hollow'?'#283044':game.region==='cinder'?'#45332a':'#223c37';c.fillRect(x,y,3,8);c.fillRect(x-5,y+3,3,5);c.fillRect(x+5,y+2,3,4);if(r>.8){c.fillStyle='#456057';c.globalAlpha=.35;c.fillRect(x+20,y+15,8,3);c.globalAlpha=1;}if(r<.12){c.strokeStyle='#294341';c.lineWidth=2;c.beginPath();c.ellipse(x,y,34,16,0,0,TAU);c.stroke();}}
 // Ancient circular trail markers lend the endless field its bearings.
 for(let gx=Math.floor(left/440);gx<=Math.ceil(right/440);gx++)for(let gy=Math.floor(top/440);gy<=Math.ceil(bottom/440);gy++){let x=gx*440+110,y=gy*440+90;c.strokeStyle='#456153';c.globalAlpha=.17;c.lineWidth=7;c.beginPath();c.arc(x,y,47,0,TAU);c.stroke();c.lineWidth=2;c.beginPath();c.arc(x,y,36,0,TAU);c.stroke();c.globalAlpha=1;}
 c.imageSmoothingEnabled=true;
 for(let gx=Math.floor(left/380);gx<=Math.ceil(right/380);gx++)for(let gy=Math.floor(top/380);gy<=Math.ceil(bottom/380);gy++){const x=gx*380+hash(gx,gy)*210,y=gy*380+hash(gy,gx)*210;if(hash(gx+9,gy)>.46){c.globalAlpha=.75;paint(c,'rune',x,y,54);c.globalAlpha=1;}}
 for(let i=0;i<24;i++){const x=left+((i*157.3+Math.sin(now*.3+i)*18)%(right-left)),y=top+((i*79.7+now*3)%(bottom-top));c.globalAlpha=(.2+Math.sin(now*1.5+i)*.15);c.fillStyle='#ccebb5';c.beginPath();c.arc(x,y,1.4,0,TAU);c.fill();}c.globalAlpha=1;
 for(const g of game.gems){if(g.x<left-10||g.x>right+10||g.y<top-10||g.y>bottom+10)continue;let size=g.value>10?6:g.value>3?4.5:3;c.fillStyle=g.value>10?'#c7a5ff':'#66d9cf';c.save();c.translate(g.x,g.y);c.rotate(Math.PI/4);c.fillRect(-size,-size,size*2,size*2);c.fillStyle='#d1fff2';c.fillRect(-size,-size,size,2);c.restore();}
 for(const pk of game.pickups){if(pk.x<left-60||pk.x>right+60||pk.y<top-60||pk.y>bottom+60)continue;c.save();c.translate(pk.x,pk.y);const treasure=pk.kind==='chest'||pk.kind==='cache';c.fillStyle=treasure?'#ffbc68':pk.kind==='heal'?'#a9efaa':'#8ddbe8';c.globalAlpha=.16;c.beginPath();c.arc(0,0,24+Math.sin(now*3)*3,0,TAU);c.fill();c.globalAlpha=1;if(treasure){c.drawImage(glow,-48,-52,96,96);paint(c,'chest',0,Math.sin(now*3)*2,pk.kind==='chest'?38:27);if(pk.kind==='chest'){c.strokeStyle='#ffda8a';c.globalAlpha=.6;c.lineWidth=1;c.beginPath();c.ellipse(0,5,24,11,0,0,TAU);c.stroke();c.globalAlpha=1;}}else{c.font='bold 25px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(pk.kind==='heal'?'+':'◇',0,0);}c.restore();}
 for(const hz of game.hazards){if(hz.kind==='mine'){c.save();c.translate(hz.x,hz.y);c.globalAlpha=settings.fx;c.strokeStyle='#ffc076';c.fillStyle=hz.arm>0?'#715032':'#f79246';c.lineWidth=2;c.beginPath();for(let i=0;i<12;i++){const a=i*TAU/12,r=i%2?7:13;c.lineTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fill();c.stroke();c.globalAlpha*=.2;c.beginPath();c.arc(0,0,hz.trigger,0,TAU);c.stroke();c.restore();}else if(hz.kind==='wave'){c.globalAlpha=settings.fx*hz.life/hz.max;c.strokeStyle='#91d6ff';c.lineWidth=9;c.beginPath();c.arc(hz.x,hz.y,hz.r*(1-hz.life/hz.max),0,TAU);c.stroke();c.strokeStyle='#ddf9ff';c.lineWidth=2;c.stroke();c.globalAlpha=1;}else if(hz.kind==='shot'){c.fillStyle='#fa8f85';c.beginPath();c.arc(hz.x,hz.y,hz.r+2,0,TAU);c.fill();c.fillStyle='#ffe1ba';c.beginPath();c.arc(hz.x,hz.y,hz.r/2,0,TAU);c.fill();}else{const hostile=hz.kind==='eruption';c.strokeStyle=hostile?'#ff725e':'#dca3ed';c.lineWidth=hostile?3:2;c.beginPath();c.arc(hz.x,hz.y,hz.r,0,TAU);c.stroke();c.globalAlpha=hostile?.18+Math.sin(now*18)*.06:.2;c.fillStyle=hostile?'#ff725e':'#dca3ed';c.fill();c.globalAlpha=1;if(hostile){c.lineWidth=2;c.beginPath();c.arc(hz.x,hz.y,hz.r*(1-hz.life/hz.max),0,TAU);c.stroke();c.fillStyle='#ffcec2';c.font='bold 20px sans-serif';c.textAlign='center';c.fillText('!',hz.x,hz.y+7);}}}
 for(const e of game.enemies){if(e.x<left-60||e.x>right+60||e.y<top-60||e.y>bottom+60)continue;const s=foes[e.type]||foes.brute;const factor=e.boss?3:e.elite?1.55:1;const bob=Math.sin(now*(e.type==='bat'?13:7)+e.id)*2;c.fillStyle='#081b1b70';c.beginPath();c.ellipse(e.x,e.y+7,15*factor,6*factor,0,0,TAU);c.fill();if(e.phase===1){c.strokeStyle='#ff9989';c.lineWidth=3;c.setLineDash([5,4]);c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.x+e.ax*130,e.y+e.ay*130);c.stroke();c.setLineDash([]);}c.globalAlpha=e.flash?0.6:1;if(!paint(c,e.boss?'boss':e.type,e.x,e.y+bob,e.boss?116:e.elite?67:enemyHeights[e.type]|| (e.type==='brute'?48:e.type==='bat'?31:38),e.x>p.x,Math.sin(now*5+e.id)*.035))c.drawImage(s,e.x-s.width/2*factor,e.y-s.height*.8*factor+bob,s.width*factor,s.height*factor);c.globalAlpha=1;if(e.slow){c.strokeStyle='#9feaff';c.beginPath();c.ellipse(e.x,e.y+6,17*factor,8*factor,0,0,TAU);c.stroke();}if(e.elite||e.boss){c.fillStyle='#141c22';c.fillRect(e.x-23*factor,e.y-34*factor,46*factor,4);c.fillStyle=e.boss?'#ed919c':'#ffcf7e';c.fillRect(e.x-23*factor,e.y-34*factor,46*factor*e.hp/e.maxHp,4);}}
 c.globalAlpha=settings.fx;
 for(const fx of game.effects){c.strokeStyle=fx.color||'#ff9f63';c.fillStyle=fx.color||'#ff9f63';let progress=1-fx.life/fx.max;c.globalAlpha=settings.fx*(1-progress*.8);if(fx.kind==='chain'){c.lineWidth=3;c.beginPath();fx.points.forEach((pt,i)=>{if(i===0)c.moveTo(pt.x,pt.y);else{const prev=fx.points[i-1];c.lineTo((pt.x+prev.x)/2+5,(pt.y+prev.y)/2-7);c.lineTo(pt.x,pt.y);}});c.lineWidth=7;c.globalAlpha*=.3;c.stroke();c.globalAlpha/= .3;c.lineWidth=2;c.stroke();}else if(fx.kind==='flame'){c.beginPath();c.moveTo(fx.x,fx.y);c.arc(fx.x,fx.y,fx.r*(.8+progress*.2),fx.full?0:fx.angle-.8,fx.full?TAU:fx.angle+.8);c.closePath();c.globalAlpha*=.32;c.fill();}else if(fx.kind==='beam'){c.lineCap='round';c.lineWidth=fx.width*2;c.globalAlpha*=.2;c.beginPath();c.moveTo(fx.x,fx.y);c.lineTo(fx.x+Math.cos(fx.angle)*fx.r,fx.y+Math.sin(fx.angle)*fx.r);c.stroke();c.globalAlpha*=4;c.lineWidth=5;c.strokeStyle='#e4ffff';c.stroke();c.lineCap='butt';}else if(fx.kind==='pool'){c.globalAlpha*=.2;c.beginPath();c.arc(fx.x,fx.y,fx.r,0,TAU);c.fill();c.globalAlpha*=2;c.lineWidth=2;c.stroke();for(let i=0;i<5;i++){const a=i*TAU/5+now*.2;c.beginPath();c.arc(fx.x+Math.cos(a)*fx.r*.6,fx.y+Math.sin(a)*fx.r*.6,3+Math.sin(now*3+i)*2,0,TAU);c.fill();}}else if(fx.kind==='fire'){c.globalAlpha*=.17;c.beginPath();c.arc(fx.x,fx.y,fx.r,0,TAU);c.fill();}else {c.lineWidth=3;c.beginPath();c.arc(fx.x,fx.y,fx.r*(.6+progress*.4),0,TAU);c.stroke();c.globalAlpha*=.08;c.fill();}}
 c.globalAlpha=1;
 for(const b of game.bullets){if(b.x<left-30||b.x>right+30||b.y<top-30||b.y>bottom+30)continue;c.globalAlpha=settings.fx;if(b.id==='scythe'||b.id==='axe'){c.save();c.translate(b.x,b.y);c.rotate(now*11);c.strokeStyle=b.color;c.fillStyle=b.color;c.lineWidth=4;if(b.id==='scythe'){c.beginPath();c.arc(0,0,14,-1.5,1.2);c.stroke();c.strokeStyle='#fff2ff';c.lineWidth=2;c.beginPath();c.arc(0,0,11,-1.5,1.2);c.stroke();}else{c.fillRect(-2,-15,4,30);c.beginPath();c.moveTo(-12,-12);c.lineTo(11,-9);c.lineTo(14,1);c.lineTo(-12,2);c.closePath();c.fill();c.strokeStyle='#fff3cf';c.lineWidth=2;c.stroke();}c.restore();continue;}if(b.id==='wisp'){c.fillStyle=b.color;c.beginPath();c.arc(b.x,b.y,7,0,TAU);c.fill();c.fillStyle='#effff9';c.beginPath();c.arc(b.x,b.y,3,0,TAU);c.fill();}c.drawImage(glow,b.x-20,b.y-20,40,40);c.strokeStyle=b.color;c.lineWidth=b.r+2;c.lineCap='round';c.beginPath();c.moveTo(b.x-b.vx*.045,b.y-b.vy*.045);c.lineTo(b.x,b.y);c.stroke();c.strokeStyle='#fff8de';c.lineWidth=2;c.beginPath();c.moveTo(b.x-b.vx*.022,b.y-b.vy*.022);c.lineTo(b.x,b.y);c.stroke();c.lineCap='butt';}c.globalAlpha=1;
 if(game.rank('orbit')){let rank=game.rank('orbit'),ev=game.evolved.includes('orbit'),n=ev?12:rank+1,r=(65+rank*5)*game.area();c.strokeStyle='#b2acf1';c.globalAlpha=.13;c.lineWidth=1;c.beginPath();c.arc(p.x,p.y,r,0,TAU);c.stroke();c.globalAlpha=1;for(let i=0;i<n;i++){let a=game.time*2.1+i*TAU/n;c.save();c.translate(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r);c.rotate(a+Math.PI/4);c.strokeStyle=ev?'#f0d9ff':'#bfb3ff';c.lineWidth=5;c.beginPath();c.arc(0,0,13,-1.5,1.1);c.stroke();c.strokeStyle='#fff7ff';c.lineWidth=2;c.beginPath();c.arc(0,0,11,-1.4,1);c.stroke();c.restore();}}
 // Player outline and indicator always render above effects.
 c.fillStyle='#06181980';c.beginPath();c.ellipse(p.x,p.y+10,17,7,0,0,TAU);c.fill();c.strokeStyle=game.invuln>0?'#ffe7b4':'#adf1d6';c.globalAlpha=.7;c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y+8,20,10,0,0,TAU);c.stroke();c.globalAlpha=game.invuln>0?(Math.sin(now*22)>.3?.6:1):1;let hero=this.sprites[game.hero.id]||(this.sprites[game.hero.id]=heroSprite(game.hero.color,game.hero.id));const walking=Math.hypot(input.x,input.y)>.1;if(game.dashing){c.globalAlpha=.22;paint(c,game.hero.id,p.x-game.lastDir.x*22,p.y-game.lastDir.y*22,54,game.lastDir.x<0);c.globalAlpha=.8;}paint(c,game.hero.id,p.x,p.y+(walking?Math.sin(now*15)*2:0),54,game.lastDir.x<0,walking?Math.sin(now*9)*.035:0);c.globalAlpha=1;
 if(game.invuln>1){c.strokeStyle='#ffe2a7';c.lineWidth=1.5;c.beginPath();c.arc(p.x,p.y-6,27,0,TAU);c.stroke();}
 for(const t of game.texts){c.globalAlpha=Math.min(1,t.life*3);c.fillStyle=t.color;c.font='bold 14px sans-serif';c.textAlign='center';c.fillText(t.text,t.x,t.y);}c.globalAlpha=1;
 c.restore();
 // Draw offscreen supply arrows in screen space.
 for(const pk of game.pickups.filter(p=>p.kind==='cache'||p.kind==='chest').slice(-4)){let sx=(pk.x-p.x)*zoom+w/2,sy=(pk.y-p.y)*zoom+h/2;if(sx<35||sx>w-35||sy<75||sy>h-60){const a=Math.atan2(sy-h/2,sx-w/2),rx=Math.min(w/2-40,(h/2-70)/Math.max(.1,Math.abs(Math.sin(a)))) ;let x=w/2+Math.cos(a)*rx,y=Math.max(78,Math.min(h-60,h/2+Math.sin(a)*rx));x=Math.max(35,Math.min(w-35,x));c.save();c.translate(x,y);c.fillStyle='#ffce84';c.font='20px sans-serif';c.textAlign='center';c.fillText('▣',0,0);c.font='11px sans-serif';c.fillText(Math.round(Math.hypot(pk.x-p.x,pk.y-p.y))+'m',0,16);c.restore();}}
 const boss=game.enemies.find(e=>e.boss&&e.hp>0);if(boss){const bar=Math.min(240,w*.28),bx=(w-bar)/2;c.fillStyle='#0c171cdc';c.fillRect(bx-10,58,bar+20,32);c.fillStyle='#ffc887';c.textAlign='center';c.font='600 10px sans-serif';c.fillText((boss.title||'The Hollow King').toUpperCase(),w/2,70);c.fillStyle='#573a40';c.fillRect(bx,77,bar,5);c.fillStyle='#ecaa70';c.fillRect(bx,77,bar*Math.max(0,boss.hp/boss.maxHp),5);}
 const vignette=c.createRadialGradient(w/2,h/2,h*.25,w/2,h/2,w*.65);vignette.addColorStop(0,'#07141900');vignette.addColorStop(1,'#07141966');c.fillStyle=vignette;c.fillRect(0,0,w,h);
 }
}
