// Discovery identities are intentionally absent from camp until encountered.
export const SECRET_STAGE={id:'astral',name:'The Unwritten Observatory',secret:true,color:'#a8caef',floor:'#101a30',tag:'Star tides · Broken observatory · Wandering gravity',desc:'A forgotten observatory suspended among moving constellations. Star tides tug at your movement; watch the rotating crossways.',requirement:'Find a forgotten passage',strength:3.8,hero:'horologist',weapon:'compass'};
export const SECRET_WEAPONS=[
 {id:'hush',name:'Bell of the Unheard',secret:true,icon:'♧',color:'#a8eed7',desc:'Leaves echo seals beneath enemies; the seals detonate in a delayed cascade.',base:'90 damage · echo seals every 3s',upgrade:'More seals, wider blasts, stronger echoes.',evo:'The unspoken chorus',pair:'wisdom',evoDesc:'Eight echo seals sing in sequence across the horde.',unlock:'Found while exploring'},
 {id:'compass',name:'Wayward star',secret:true,icon:'✥',color:'#ffe3a1',desc:'A wandering star ricochets between targets, leaving a shining trail.',base:'48 damage · 4 seeking stars every 2.8s',upgrade:'More stars, stronger hits and longer flight.',evo:'Atlas of the lost',pair:'agility',evoDesc:'A constellation of tireless stars hunts through many targets.',unlock:'Found while exploring'}
];
export const TRADE_GOODS=[
 {id:'rerolls',name:'Book of second chances',desc:'+2 rerolls in every new expedition per rank.',cost:650,max:3},
 {id:'banish',name:'Severing ink',desc:'+1 banish per new expedition per rank. Remove an unwanted upgrade from this run’s choices.',cost:900,max:3},
 {id:'glass',name:'Glassfire lens',desc:'Charm: +35% damage, but 20% less maximum health.',cost:1800,max:1},
 {id:'storm',name:'Storm vessel',desc:'Charm: 12% faster recharge, but take 15% more damage.',cost:2200,max:1},
 {id:'wander',name:'Pilgrim’s knot',desc:'Charm: +20% movement speed and 30% faster dash recharge, but 15% less damage.',cost:1200,max:1},
 {id:'gilt',name:'Gilded burden',desc:'Charm: +50% gold, but gain 20% less experience.',cost:1600,max:1}
];
export const SECRET_KINDS=['trader','passage','hush','compass','memory','cache'];
const hash=n=>{const v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v);};
export function ensureSecrets(s){s.secrets??={found:[],purchases:{},charm:'',unions:[]};return s.secrets;}
export function validSecrets(s){if(s.secrets===undefined)return true;const v=s.secrets;return !!v&&!Array.isArray(v)&&Array.isArray(v.found)&&v.found.length<=100&&v.found.every(x=>typeof x==='string'&&/^[a-z]+:(trader|passage|hush|compass|memory|cache)$/.test(x))&&v.purchases&&typeof v.purchases==='object'&&!Array.isArray(v.purchases)&&Object.entries(v.purchases).every(([id,n])=>TRADE_GOODS.some(t=>t.id===id&&Number.isInteger(n)&&n>=0&&n<=t.max))&&['','glass','storm','wander','gilt'].includes(v.charm)&&(!v.charm||v.purchases[v.charm]===1)&&Array.isArray(v.unions)&&v.unions.length<=6&&v.unions.every(x=>['stormwheel','winterstar','phoenix','prismstorm','maelstrom','soulharvest'].includes(x));}
export const traderFound=s=>!!s.secrets?.found.some(id=>id.endsWith(':trader'));
export const tradeCost=(s,t)=>Math.round(t.cost*2**(s.secrets?.purchases[t.id]||0));
export function buyTrade(s,id){const t=TRADE_GOODS.find(t=>t.id===id);if(!t||!traderFound(s))return false;const v=ensureSecrets(s),n=v.purchases[id]||0,cost=tradeCost(s,t);if(n>=t.max||s.gold<cost)return false;s.gold-=cost;v.purchases[id]=n+1;return true;}
export function equipCharm(s,id){if(!traderFound(s)||!['','glass','storm','wander','gilt'].includes(id)||id&&!s.secrets.purchases[id])return false;s.secrets.charm=id;return true;}
export function secretSites(g){const seed=[...g.region].reduce((n,c)=>n+c.charCodeAt(0),0);return SECRET_KINDS.map((kind,j)=>{const a=(j*.98+.58)+hash(seed+j)*.22,dist=[1050,3100,1900,4600,2450,1500][j];return {id:g.region+':'+kind,kind,x:Math.cos(a)*dist,y:Math.sin(a)*dist};}).filter(s=>!(s.kind==='passage'&&g.region==='astral')&&!(s.kind==='compass'&&!['astral','clockwork','drowned'].includes(g.region))&&!(s.kind==='hush'&&!['hollow','briarheart','ashwood'].includes(g.region)));}
export function stepSecrets(g,safePoint){for(const raw of secretSites(g)){if(g.secretClaims.includes(raw.id))continue;const site={...raw,...safePoint(g.region,raw.x,raw.y)};if(Math.hypot(site.x-g.player.x,site.y-g.player.y)>40)continue;g.secretClaims.push(site.id);g.invuln=Math.max(g.invuln,3);
 if(site.kind==='memory'){g.rerolls+=2;g.player.hp=Math.min(g.maxHp(),g.player.hp+35);}
 if(site.kind==='cache')g.gainGold(300+g.time/6);
 g.emit('secret',{kind:site.kind});}}
export function recordSecrets(s,g){const v=ensureSecrets(s),newIds=(g?.secretClaims||[]).filter(id=>!v.found.includes(id));v.found=[...new Set([...v.found,...(g?.secretClaims||[])])];v.unions=[...new Set([...v.unions,...(g?.unionSeen||[])])];for(const id of newIds){const kind=id.split(':')[1];if(kind==='passage'&&!s.unlockedRegions.includes('astral'))s.unlockedRegions.push('astral');if(['hush','compass'].includes(kind)&&!s.unlockedWeapons.includes(kind))s.unlockedWeapons.push(kind);}return newIds;}
export function fireSecret(g,id){if(!SECRET_WEAPONS.some(w=>w.id===id))return false;const t=g.nearest();if(!t){g.cd[id]=.2;return true;}const n=g.rank(id),ev=g.evolved.includes(id);if(id==='hush'){const targets=g.enemies.filter(e=>e.hp>0).slice(0,(ev?8:2+Math.floor(n/2))+g.craft(id,'projectiles'));targets.forEach((e,j)=>g.hazards.push({kind:'meteor',x:e.x,y:e.y,r:(65+n*5)*g.spellArea(id),life:.45+j*.12,max:.45+j*.12,damage:65+n*25,id}));g.cd[id]=3*g.haste(id);}else {const count=(ev?9:3+Math.floor(n/2))+g.craft(id,'projectiles');for(let j=0;j<count;j++){const a=j*Math.PI*2/count;g.bullets.push({x:g.player.x,y:g.player.y,vx:Math.cos(a)*200,vy:Math.sin(a)*200,r:7,life:3.5+g.craft(id,'duration')*.4,damage:35+n*14,id,pierce:ev?8:3,hit:[],color:'#ffe3a1'});}g.cd[id]=2.8*g.haste(id);}return true;}
export function drawSecrets(c,g,b,safePoint){for(const raw of secretSites(g)){if(g.secretClaims.includes(raw.id))continue;const s={...raw,...safePoint(g.region,raw.x,raw.y)};if(s.x<b.left-100||s.x>b.right+100||s.y<b.top-100||s.y>b.bottom+100)continue;c.save();c.translate(s.x,s.y);c.strokeStyle='#d8c899';c.fillStyle='#d8c899';c.lineWidth=2;const near=Math.hypot(s.x-g.player.x,s.y-g.player.y)<180;
 if(s.kind==='trader'){c.fillStyle='#344b4c';c.fillRect(-34,-18,68,32);c.fillStyle='#d5b789';c.beginPath();c.moveTo(-43,-18);c.lineTo(0,-58);c.lineTo(43,-18);c.closePath();c.fill();c.fillStyle='#ffdfa0';c.fillRect(23,-22,7,12);c.beginPath();c.arc(-22,20,10,0,Math.PI*2);c.arc(22,20,10,0,Math.PI*2);c.stroke();}
 else if(s.kind==='passage'){for(let j=1;j<8;j++){c.globalAlpha=j/10;c.fillRect(-j*2,80-j*10,j*4,4);}c.globalAlpha=1;c.beginPath();c.ellipse(0,-20,28,45,0,Math.PI,Math.PI*2);c.lineTo(28,15);c.moveTo(-28,-20);c.lineTo(-28,15);c.stroke();c.fillStyle='#a5cff655';c.fillRect(-20,-28,40,40);}
 else{c.fillStyle='#314744';c.fillRect(-20,-5,40,20);c.fillStyle='#e4d8aa';c.font='30px serif';c.textAlign='center';c.fillText({hush:'♧',compass:'✥',memory:'◈',cache:'▣'}[s.kind],0,-12+Math.sin(g.time*2)*3);}
 if(near){c.fillStyle='#eee1bc';c.font='11px sans-serif';c.textAlign='center';c.fillText('Approach to investigate',0,45);}c.restore();}}
