import {drawChallengeWorld} from './challenge-art.js?v=21';
import {obstacles,cell,riftAt} from './world.js?v=21';
const TAU=Math.PI*2;
export function drawWorld(c,g,b){const {left,top,right,bottom}=b;
 if(g.region!=='ashwood'){
  c.fillStyle=g.region==='hollow'?'#1e2034':'#28282c';c.fillRect(left,top,right-left,bottom-top);
  const size=g.region==='hollow'?70:80;for(let x=Math.floor(left/size);x<=Math.floor(right/size);x++)for(let y=Math.floor(top/size);y<=Math.floor(bottom/size);y++){c.fillStyle=(x+y)%2===0?(g.region==='hollow'?'#28283d':'#323035'):(g.region==='hollow'?'#242538':'#2c2c31');c.fillRect(x*size+2,y*size+2,size-4,size-4);c.strokeStyle=g.region==='hollow'?'#44405255':'#61504744';c.strokeRect(x*size+5,y*size+5,size-10,size-10);}
 }
 if(g.region==='hollow'){
  for(let x=Math.floor((left-280)/560);x<=Math.ceil((right-280)/560);x++)for(let y=Math.floor((top-280)/560);y<=Math.ceil((bottom-280)/560);y++){const cx=x*560+280,cy=y*560+280,r=riftAt(cx,cy,g.time);c.strokeStyle=r.active?'#ff354d':r.warning?'#ff6979':'#685d85';c.fillStyle=r.active?'#ff354d48':r.warning?'#ff354d29':'#6a568314';c.lineWidth=r.active?4:2;c.beginPath();c.arc(cx,cy,92,0,TAU);c.fill();c.stroke();c.beginPath();c.arc(cx,cy,78,0,TAU);c.stroke();for(let i=0;i<6;i++){const a=i*TAU/6+g.time*(r.active?.4:.06);c.beginPath();c.moveTo(cx+Math.cos(a)*65,cy+Math.sin(a)*65);c.lineTo(cx+Math.cos(a)*85,cy+Math.sin(a)*85);c.stroke();}if(r.warning||r.active){c.fillStyle='#ffb7bf';c.font='bold 12px sans-serif';c.textAlign='center';c.fillText(r.warning?'RIFT OPENING':'UNSTABLE RIFT',cx,cy+4);}}
  for(const wall of obstacles(g.region,g.player.x,g.player.y)){c.fillStyle='#0a0d1966';c.fillRect(wall.x+9,wall.y+10,wall.w,wall.h);c.fillStyle='#383c51';c.fillRect(wall.x,wall.y,wall.w,wall.h);c.fillStyle='#65617d';c.fillRect(wall.x,wall.y,wall.w,5);c.fillStyle='#202334';c.fillRect(wall.x,wall.y+wall.h-7,wall.w,7);c.strokeStyle='#8d81ab55';c.lineWidth=1;c.strokeRect(wall.x+5,wall.y+7,wall.w-10,wall.h-17);c.fillStyle='#a18ac7';c.fillRect(wall.x+wall.w/2-2,wall.y+9,4,wall.h-24);}
 }
 if(g.region==='cinder'){
  for(let i=Math.floor((left-320)/640);i<=Math.ceil((right-320)/640);i++){const x=320+i*640;c.fillStyle='#bd452c';c.fillRect(x-52,top,104,bottom-top);c.fillStyle='#ed733b';c.fillRect(x-39,top,78,bottom-top);for(let y=Math.floor(top/35)*35;y<bottom;y+=35){c.strokeStyle='#ffbd6655';c.lineWidth=4;c.beginPath();c.moveTo(x-35,y);c.quadraticCurveTo(x,y+Math.sin(g.time+y)*9,x+35,y+5);c.stroke();}for(let j=Math.floor(top/520)-1;j<=Math.ceil(bottom/520);j++){const y=j*520;c.fillStyle='#48434a';c.fillRect(x-70,y-68,140,136);c.strokeStyle='#9b8170';c.lineWidth=3;c.strokeRect(x-70,y-68,140,136);for(let k=-2;k<=2;k++){c.strokeStyle='#24282e';c.beginPath();c.moveTo(x-68,y+k*22);c.lineTo(x+68,y+k*22);c.stroke();}c.fillStyle='#c3ad82';c.fillRect(x-64,y-63,8,8);c.fillRect(x+56,y+55,8,8);}}
 }
 drawChallengeWorld(c,g,b);
 if(g.objective)for(const n of g.objective.nodes){c.save();c.translate(n.x,n.y);c.strokeStyle=n.taken?'#6c8b87':'#baf9e4';c.fillStyle=n.taken?'#31423f':'#366c6580';c.lineWidth=2;c.beginPath();c.ellipse(0,9,31,15,0,0,TAU);c.fill();c.stroke();c.beginPath();c.moveTo(0,-39);c.lineTo(13,-13);c.lineTo(0,2);c.lineTo(-13,-13);c.closePath();c.fillStyle=n.taken?'#597268':'#b6f4df';c.fill();if(!n.taken){c.globalAlpha=.15;c.fillStyle='#9ff3e0';c.fillRect(-3,-95,6,83);c.globalAlpha=1;}c.fillStyle=n.taken?'#7ba495':'#dbfff3';c.font='bold 11px sans-serif';c.textAlign='center';c.fillText(n.taken?'AWAKENED':'SHRINE',0,33);c.restore();}
}
export function drawObjectiveArrows(c,g,w,h,zoom){if(!g.objective)return;const remaining=g.objective.nodes.filter(n=>!n.taken);for(const n of remaining){const dx=(n.x-g.player.x)*zoom,dy=(n.y-g.player.y)*zoom;let x=w/2+dx,y=h/2+dy;if(x>35&&x<w-35&&y>108&&y<h-105)continue;const scale=Math.min((w/2-32)/Math.max(1,Math.abs(dx)),(h/2-108)/Math.max(1,Math.abs(dy)));x=w/2+dx*scale;y=h/2+dy*scale;c.save();c.translate(x,y);c.rotate(Math.atan2(dy,dx));c.fillStyle='#c4ffeb';c.strokeStyle='#133c39';c.lineWidth=3;c.beginPath();c.moveTo(10,0);c.lineTo(-5,-7);c.lineTo(-5,7);c.closePath();c.stroke();c.fill();c.restore();c.textAlign='center';c.font='bold 10px sans-serif';c.fillStyle='#dcfff0';c.fillText(Math.round(Math.hypot(dx,dy)/zoom)+'m',x,y+20);}}
export function enemyCrown(c,e,time){if(!['bulwark','stalker','siege','harbinger'].includes(e.type))return;const color=e.lateBoss?(e.fury?'#ff785d':'#ffcf8b'):{bulwark:'#dfac76',stalker:'#b99af8',siege:'#ff9e6b',harbinger:'#9de3d2'}[e.type],r=e.lateBoss?50:e.r+6;c.strokeStyle=color;c.lineWidth=e.lateBoss?3:2;c.beginPath();c.ellipse(e.x,e.y+6,r,r*.4,0,0,TAU);c.stroke();if(e.lateBoss||e.type==='harbinger'){c.save();c.translate(e.x,e.y-(e.lateBoss?125:65));c.rotate(time*.4);for(let i=0;i<5;i++){c.rotate(TAU/5);c.fillStyle=color;c.fillRect(-3,-17,6,10);}c.restore();}}
