import assert from 'node:assert/strict';
import {Game} from '../engine.js';
import {freshSave,WEAPONS,REGIONS} from '../data.js';
import {RELIC_WEAPONS} from '../relic-weapons.js';
import {ensureChronicle,recordChronicle,weaponUnlocked,validChronicle} from '../chronicle.js';
import {buySpell} from '../gear.js';
import {awakenSite} from '../discoveries.js';
import {spawnReaper} from '../challenge.js';
function arena(s=freshSave()){const g=new Game(s);g.skills={};g.invuln=1e9;g.lateStarted=true;g.nextBoss=g.nextElite=g.nextCache=g.nextHeal=g.nextWorldStrike=g.nextObjective=g.nextDiscoveryScan=g.spawnClock=1e9;g.rng=42;return g;}
const s=ensureChronicle(freshSave());s.gold=50000;
for(const w of RELIC_WEAPONS){assert(!weaponUnlocked(s,w.id));assert(!buySpell(s,w.id,'power'));}const locked=arena(s);for(let i=0;i<100;i++)assert(locked.offers().every(id=>!RELIC_WEAPONS.some(w=>w.id===id)));
// Exact milestones wait behind an existing fight, spawn once and survive a reload.
for(const region of REGIONS){const save=ensureChronicle(freshSave());save.region=region.id;let g=arena(save);g.time=1199.9;g.step(.05);assert(!g.enemies.some(e=>e.milestone));g.time=1200;const blocker=g.spawn('brute',false,true);g.step(.01);assert(!g.enemies.some(e=>e.milestone));g.hit(blocker,1e20,'bolt');recordChronicle(save,g);assert(!weaponUnlocked(save,'tempest'),'ordinary boss does not grant milestone trophy');g.step(.01);const b20=g.enemies.find(e=>e.milestone===20);assert(b20);assert.equal(g.enemies.filter(e=>e.hp>0&&e.boss).length,1);const snap=g.snapshot();g=new Game(save,()=>{},snap);g.mode='playing';assert.equal(g.enemies.filter(e=>e.milestone===20).length,1);g.hit(g.enemies.find(e=>e.milestone===20),1e20,'bolt');recordChronicle(save,g);assert(weaponUnlocked(save,'tempest'));assert(!weaponUnlocked(save,'hourglass'));g.time=1500;g.step(.01);assert(g.enemies.some(e=>e.milestone===25));g.hit(g.enemies.find(e=>e.milestone===25),1e20,'bolt');recordChronicle(save,g);assert(weaponUnlocked(save,'hourglass'));g.step(.01);assert(!g.enemies.some(e=>e.milestone));assert.deepEqual(g.milestoneBosses,[20,25]);assert(validChronicle(save));}
// Right guardian kind and region are required, regardless of when it is beaten.
for(const [region,kind,expected] of [['ashwood','altar',null],['hollow','vault',null],['ashwood','vault','briar'],['cinder','vault','inferno']]){const save=ensureChronicle(freshSave());save.region=region;const g=arena(save),site={id:1,kind,state:'sealed',x:0,y:0,discovered:true,guardianId:null};g.discoveries=[site];let checkpoint;g.onEvent=type=>{if(type==='bossdown')checkpoint=g.snapshot();};assert(awakenSite(g,site));g.hit(g.enemies[0],1e20,'bolt');assert.equal(checkpoint.discoveries[0].state,'ready','guardian is unsealed in the immediate defeat checkpoint');recordChronicle(save,g);assert.equal(save.unlockedWeapons.includes('briar'),expected==='briar');assert.equal(save.unlockedWeapons.includes('inferno'),expected==='inferno');if(expected){assert.equal(site.state,'ready');assert(validChronicle(save));assert.equal(recordChronicle(save,g).length,0);const restored=new Game(save,()=>{},g.snapshot());assert.deepEqual(restored.weaponFeats,g.weaponFeats);}}
// Existing proven Eclipse victories are recognized retroactively; run time alone is not.
s.chronicle.records.ashwood={time:1900,reaper:0};recordChronicle(s);assert(!weaponUnlocked(s,'verdict'));s.chronicle.records.ashwood.reaper=1;recordChronicle(s);assert(weaponUnlocked(s,'verdict'));assert.equal(recordChronicle(s).length,0);
const finalSave=ensureChronicle(freshSave()),final=arena(finalSave);spawnReaper(final);final.hit(final.enemies[0],1e20,'bolt');recordChronicle(finalSave,final);assert(weaponUnlocked(finalSave,'verdict'));
// Weapons work at every rank, scale to rank eight, evolve through real chests and retain six-slot rules.
for(const w of RELIC_WEAPONS)for(const rank of [1,8])for(const ev of [false,true]){const save=ensureChronicle(freshSave());save.unlockedWeapons.push(w.id);let g=arena(save);g.skills={[w.id]:rank};g.evolved=ev?[w.id]:[];const e=g.spawn('brute');e.x=70;e.y=0;e.hp=e.maxHp=1e7;e.speed=0;g.fire(w.id);for(let i=0;i<45;i++)g.step(1/60);assert(g.damageDone[w.id]>0,`${w.id}/${rank}/${ev} deals damage`);assert(g.bullets.every(b=>Number.isFinite(b.damage)&&Number.isFinite(b.x)));if(rank===8&&!ev){g.skills[w.pair]=2;g.openChest({boss:true,rewards:1,gold:0});assert(g.evolved.includes(w.id));}}
const retaliation=arena();retaliation.skills={briar:8};const victim=retaliation.spawn();victim.x=60;victim.y=0;victim.hp=1e7;retaliation.hurt(1);const damage=retaliation.damageDone.briar;retaliation.hurt(1);assert.equal(retaliation.damageDone.briar,damage);retaliation.time=2;retaliation.hurt(1);assert(retaliation.damageDone.briar>damage);
console.log(JSON.stringify({checks:['All 5 weapons remain locked until their exact victory condition','20/25-minute encounters queue once on all 9 maps and survive saves','Only correct vault guardians award their weapons; claims are idempotent','Prior Eclipse victories unlock Reaper’s verdict without replay; survival alone does not','All new attacks deal real damage at ranks 1/8 and evolve through chests','Briar retaliation has a real 2-second cooldown']}));
