import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {SIGNATURE_TRACKS} from '../spellcraft.js';
import {Game} from '../engine.js';
import {freshSave,WEAPONS,PASSIVES,HEROES,REGIONS,META,MILESTONES,RELICS,ENEMIES,byId} from '../data.js';
import {ensureChronicle,recordChronicle,validChronicle,EXTRA_WEAPONS,SPECIAL_STAGES,weaponUnlocked} from '../chronicle.js';
import {ensureProgression,validProgression,gearItem,buySpell} from '../gear.js';
import {ensureRegions,safePoint,isSafePoint} from '../world.js';
import {musicSettings} from '../music.js';
import {spawnReaper,challengeHazard,challengeWalls} from '../challenge.js';
import {claimSite} from '../discoveries.js';
import {ROSTERS} from '../bestiary.js';
const checks=[];const s=ensureChronicle(ensureRegions(ensureProgression(freshSave())));s.gold=12000;
const old=JSON.parse(JSON.stringify(s));delete old.chronicle;delete old.unlockedWeapons;old.heroes=['ranger','witch'];old.inventory['chain:4']={level:5};old.equipment.witch='chain:4';old.spellcraft.bolt={power:3};old.run=new Game(old).snapshot();old.run.player.hp=41;old.run.gold=217;old.run.time=820;old.run.skills={bolt:8,power:3};old.run.evolved=['bolt'];for(const k of ['availableWeapons','reaperSpawned','reaperDefeated','reaperWarning','nextChallengeStrike'])delete old.run[k];
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');const validate=app.slice(app.indexOf('function validateSave('),app.indexOf('function registerTools('));const context={Game,freshSave,WEAPONS,PASSIVES,HEROES,REGIONS,META,MILESTONES,RELICS,ENEMIES,byId,validProgression,ensureProgression,gearItem,ensureRegions,ensureChronicle,validChronicle,musicSettings};vm.createContext(context);vm.runInContext(validate+';this.validate=validateSave;',context);
const baseline=JSON.parse(JSON.stringify(old));context.validate(old);recordChronicle(old,old.run);for(const k of ['gold','meta','inventory','equipment','spellcraft','stats'])assert.deepEqual(old[k],baseline[k]);assert(old.heroes.includes('witch'));const restored=new Game(old,()=>{},old.run);assert.equal(restored.player.hp,41);assert.equal(restored.gold,217);assert.equal(restored.time,820);assert.deepEqual(restored.skills,baseline.run.skills);assert.equal(restored.mode,'paused');checks.push('legacy save retains bank, gear, spellcraft, heroes, health, skills and suspended run');
let q=new Game(s);for(let i=0;i<200;i++)assert(q.offers().every(id=>weaponUnlocked(s,id)));assert.equal(buySpell(s,'aegis','power'),false);checks.push('lost weapons cannot roll or be purchased while locked');
q.bossesKilled=1;recordChronicle(s,q);assert(s.unlockedRegions.includes('frostmarch'));for(const region of SPECIAL_STAGES){q=new Game({...s,region:region.id});q.time=600;q.evolutionCount=2;claimSite(q,{state:'ready',kind:'spring'});recordChronicle(s,q);assert(s.heroes.includes(region.hero));assert(s.unlockedWeapons.includes(region.weapon));assert.equal(recordChronicle(s,q).length,0);context.validate(s);let round=JSON.parse(JSON.stringify(s));context.validate(round);assert.deepEqual(round,s);}
assert(buySpell(s,'aegis','power'));checks.push('all six stage-specific rescues and weapons persist idempotently; unlocked spellcraft is purchasable');
for(const region of SPECIAL_STAGES){const g=new Game({...s,region:region.id});for(let x=-800;x<800;x+=113)for(let y=-800;y<800;y+=137){const p=safePoint(region.id,x,y);assert(isSafePoint(region.id,p.x,p.y),`${region.id} safe ${x},${y}`);}g.time=301;for(let i=0;i<40;i++)g.spawn(region.id+'_3');assert.equal(g.rangedCount(),5);assert(g.enemies.every(e=>e.type.startsWith(region.id)));g.enemies=[];g.spawn(region.id+'_4',false,true);g.enemies[0].attack=0;g.step(.05);assert(g.hazards.some(h=>h.kind==='eruption'));assert(g.enemies.every(e=>Number.isFinite(e.hp)&&Number.isFinite(e.x)));}
checks.push('six unique rosters and guardian attacks, five-ranged cap, safe terrain placement');
q=new Game(s);q.time=1799.98;q.nextBoss=1e9;q.spawn('brute',false,true);q.step(.01);assert(!q.reaperSpawned);q.step(.02);assert(q.reaperSpawned);assert.equal(q.enemies.filter(e=>e.reaper).length,1);let r=q.enemies.find(e=>e.reaper);q.hit(r,100,'bolt');assert(r.hp<r.maxHp);const wounded=r.hp;const snap=q.snapshot();context.validate({...s,run:snap});q=new Game(s,()=>{},snap);q.mode='playing';q.step(.01);assert.equal(q.enemies.filter(e=>e.reaper).length,1);checks.push('30:00 spawn occurs once beside an existing boss; ordinary damage works; save/resume preserves boss');
console.log(JSON.stringify({checks},null,2));

const upgraded=JSON.parse(JSON.stringify(s));upgraded.spellcraft=Object.fromEntries(Object.entries(SIGNATURE_TRACKS).map(([id,tracks])=>[id,Object.fromEntries(tracks.map(t=>[t.id,t.max]))]));upgraded.run=new Game(upgraded).snapshot();const exported=JSON.stringify({spellcraft:upgraded.spellcraft,run:upgraded.run.spellcraft,gold:upgraded.gold,spent:upgraded.spellSpent});context.validate(upgraded);assert.equal(JSON.stringify({spellcraft:upgraded.spellcraft,run:upgraded.run.spellcraft,gold:upgraded.gold,spent:upgraded.spellSpent}),exported);console.log('All 48 signature tracks survive the real export/import validator, including a suspended run');
