import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {Game} from '../engine.js';
import {freshSave,WEAPONS,PASSIVES,HEROES,REGIONS,META,MILESTONES,RELICS,ENEMIES,byId} from '../data.js';
import {ensureChronicle,recordChronicle,validChronicle,EXTRA_WEAPONS,SPECIAL_STAGES,eclipseBuild,weaponUnlocked} from '../chronicle.js';
import {ensureProgression,validProgression,gearItem,buySpell} from '../gear.js';
import {ensureRegions,safePoint,isSafePoint} from '../world.js';
import {musicSettings} from '../music.js';
import {spawnReaper,challengeHazard,challengeWalls} from '../challenge.js';
import {claimSite} from '../discoveries.js';
import {ROSTERS} from '../bestiary.js';
const checks=[];const s=ensureChronicle(ensureRegions(ensureProgression(freshSave())));s.gold=12000;
const old=JSON.parse(JSON.stringify(s));delete old.chronicle;delete old.unlockedWeapons;old.heroes=['ranger','witch'];old.inventory['chain:4']={level:5};old.equipment.witch='chain:4';old.spellcraft.bolt={power:3};old.run=new Game(old).snapshot();old.run.player.hp=41;old.run.gold=217;old.run.time=820;old.run.skills={bolt:8,power:3};old.run.evolved=['bolt'];for(const k of ['availableWeapons','reaperSpawned','reaperDefeated','reaperWarning','nextChallengeStrike'])delete old.run[k];
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');const validate=app.slice(app.indexOf('function validateSave('),app.indexOf('function registerTools('));const context={Game,freshSave,WEAPONS,PASSIVES,HEROES,REGIONS,META,MILESTONES,RELICS,ENEMIES,byId,validProgression,ensureProgression,gearItem,ensureRegions,ensureChronicle,validChronicle,musicSettings};vm.createContext(context);vm.runInContext(validate+';this.validate=validateSave;',context);
const baseline=JSON.parse(JSON.stringify(old));context.validate(old);recordChronicle(old,old.run);for(const k of ['gold','meta','inventory','equipment','spellcraft','stats'])assert.deepEqual(old[k],baseline[k]);assert(old.heroes.includes('witch'));const restored=new Game(old,()=>{},old.run);assert.equal(restored.player.hp,41);assert.equal(restored.gold,217);assert.equal(restored.time,820);assert.deepEqual(restored.skills,baseline.run.skills);assert.equal(restored.mode,'paused');checks.push('legacy save retains bank, gear, spellcraft, heroes, health, skills and suspended run');
let q=new Game(s);for(let i=0;i<200;i++)assert(q.offers().every(id=>weaponUnlocked(s,id)));assert.equal(buySpell(s,'aegis','power'),false);checks.push('lost weapons cannot roll or be purchased while locked');
q.bossesKilled=1;recordChronicle(s,q);assert(s.unlockedRegions.includes('frostmarch'));for(const region of SPECIAL_STAGES){q=new Game({...s,region:region.id});q.time=600;q.evolutionCount=2;claimSite(q,{state:'ready',kind:'spring'});recordChronicle(s,q);assert(s.heroes.includes(region.hero));assert(s.unlockedWeapons.includes(region.weapon));assert.equal(recordChronicle(s,q).length,0);context.validate(s);let round=JSON.parse(JSON.stringify(s));context.validate(round);assert.deepEqual(round,s);}
assert(buySpell(s,'aegis','power'));checks.push('all six stage-specific rescues and weapons persist idempotently; unlocked spellcraft is purchasable');
for(const region of SPECIAL_STAGES){const g=new Game({...s,region:region.id});for(let x=-800;x<800;x+=113)for(let y=-800;y<800;y+=137){const p=safePoint(region.id,x,y);assert(isSafePoint(region.id,p.x,p.y),`${region.id} safe ${x},${y}`);}g.time=301;for(let i=0;i<40;i++)g.spawn(region.id+'_3');assert.equal(g.rangedCount(),5);assert(g.enemies.every(e=>e.type.startsWith(region.id)));g.enemies=[];g.spawn(region.id+'_4',false,true);g.enemies[0].attack=0;g.step(.05);assert(g.hazards.some(h=>h.kind==='eruption'));assert(g.enemies.every(e=>Number.isFinite(e.hp)&&Number.isFinite(e.x)));}
checks.push('six unique rosters and guardian attacks, five-ranged cap, safe terrain placement');
q=new Game(s);q.time=1799.98;q.nextBoss=1e9;q.spawn('brute',false,true);q.step(.01);assert(!q.reaperSpawned);q.step(.02);assert(q.reaperSpawned);assert.equal(q.enemies.filter(e=>e.reaper).length,1);let r=q.enemies.find(e=>e.reaper);q.hit(r,1e10,'bolt');assert.equal(r.hp,r.maxHp);const snap=q.snapshot();context.validate({...s,run:snap});q=new Game(s,()=>{},snap);q.mode='playing';q.step(.01);assert.equal(q.enemies.filter(e=>e.reaper).length,1);checks.push('30:00 spawn occurs once beside an existing boss; ordinary damage blocked; save/resume preserves boss');
const pilots=[];
for(const ids of [['aegis','chrono'],['solar','beam'],['blood','scythe']]){
 const state=ensureProgression(freshSave());state.meta=Object.fromEntries(META.map(m=>[m.id,m.max]));state.inventory['bolt:6']={level:10};state.equipment.ranger='bolt:6';let g=new Game(state);g.rng=42;g.time=1800;g.nextCache=g.nextHeal=1e9;g.nextBoss=1e9;g.nextElite=1e9;g.nextWorldStrike=1e9;g.nextObjective=1e9;g.nextDiscoveryScan=1e9;g.spawnClock=1e9;g.lateStarted=true;g.skills=Object.fromEntries([...ids.map(id=>[id,8]),...['guard','regen','haste','reach','power','agility'].map(id=>[id,3])]);g.evolved=ids;g.relics={ascend_power:10,ascend_regen:10,ascend_vigor:10};g.player.hp=g.maxHp();spawnReaper(g);const boss=g.enemies.find(e=>e.reaper);boss.x=140;boss.y=0;let ticks=0;while(!g.reaperDefeated&&g.mode==='playing'&&ticks<18000){const p=g.player,e=boss,d=Math.hypot(e.x-p.x,e.y-p.y)||1;const radial=d<150?-.8:d>220?.8:0;let dx=(e.x-p.x)/d*radial-(e.y-p.y)/d,dy=(e.y-p.y)/d*radial+(e.x-p.x)/d;for(const h of g.hazards)if(h.kind==='eruption'&&Math.hypot(h.x-p.x,h.y-p.y)<h.r+55){dx+=(p.x-h.x)/50;dy+=(p.y-h.y)/50;}const length=Math.hypot(dx,dy);g.step(1/60,{x:dx/length,y:dy/length});if(g.mode==='levelup')g.choose(g.choices[0]);if(g.mode==='down'&&g.revives)g.revive();ticks++;}
 pilots.push({build:eclipseBuild(g),seconds:Math.round(ticks/60),won:g.reaperDefeated,health:Math.round(g.player.hp),bossHealth:Math.round(boss.hp)});assert(g.reaperDefeated,JSON.stringify(pilots.at(-1)));assert(ticks>60*15,'not an instant kill');recordChronicle(s,g);assert(s.unlockedRegions.includes('eclipse'));
}
checks.push('three legal evolved covenants can win through actual moving combat, without invulnerability or injected damage');
console.log(JSON.stringify({checks,pilots},null,2));
