import assert from 'node:assert/strict';
import {Game} from '../engine.js';
import {freshSave,WEAPONS,META} from '../data.js';
import {ensureProgression,validProgression} from '../gear.js';
import {spawnReaper} from '../challenge.js';
const checks=[];
function arena(save=freshSave()){const g=new Game(save);g.rng=42;g.time=1800;g.lateStarted=true;g.waveMinute=30;g.nextCache=g.nextHeal=g.nextBoss=g.nextElite=g.nextWorldStrike=g.nextObjective=g.nextDiscoveryScan=g.spawnClock=1e9;spawnReaper(g);const e=g.enemies[0];e.x=140;e.y=0;return g;}
// Identical raw hits must behave identically for every weapon and any combination.
for(const w of WEAPONS){const g=arena(),e=g.enemies[0];g.random=()=>.5;g.hit(e,100,w.id);assert(e.hp<e.maxHp);assert.equal(e.maxHp-e.hp,100*g.damage());}
let g=arena(),e=g.enemies[0];g.hit(e,1000,'bolt');const hp=e.hp;g.skills={};g.step(.05);assert.equal(e.hp,hp);g.evolved=['aegis','chrono'];g.random=()=>.5;g.hit(e,100,'bolt');assert.equal(hp-e.hp,100*g.damage());checks.push('all 22 weapons deal normal damage; no immunity, damage bonus, percent-health shortcut or regeneration');
// Existing v19 snapshots preserve boss health and rewards; obsolete ward fields are inert.
e.shatterAt=5000;e.punishAt=5000;e.hp=1234567;const old=g.snapshot();g=new Game(freshSave(),()=>{},old);assert.equal(g.enemies[0].hp,1234567);g.mode='playing';g.skills={};g.step(.05);assert.equal(g.enemies[0].hp,1234567);assert.equal(g.enemies.filter(e=>e.reaper).length,1);checks.push('existing boss saves keep their exact HP and spawn state without regeneration');
for(const id of ['frost','chrono']){g=arena();e=g.enemies[0];g.skills={[id]:8};g.evolved=[id];g.fire(id);assert(e.frozenUntil>g.time);g.skills={};e.x=0;e.y=0;e.attack=0;g.invuln=0;const timer=e.attack,hp=g.player.hp;g.step(.05);assert.equal(e.x,0);assert.equal(e.y,0);assert.equal(e.attack,timer);assert.equal(g.player.hp,hp);assert(!g.hazards.some(h=>h.kind==='eruption'));const until=e.frozenUntil;g.chill(e,5,3);assert.equal(e.frozenUntil,until);const save=g.snapshot();g=new Game(freshSave(),()=>{},save);assert.equal(g.enemies[0].frozenUntil,until);g.mode='playing';e=g.enemies[0];e.x=140;g.time=until;g.step(.01);assert(e.eclipseAction);assert(e.eclipseAction.timer>0);g.time=e.freezeReadyAt;g.chill(e,5,3);assert(e.frozenUntil>g.time);}
checks.push('frost and time spells freeze movement/contact/new casts, honor a short thaw, can refreeze, and persist through saves');
g=arena();g.skills={};g.chill(g.enemies[0],5,3);g.invuln=0;g.hazards=[{kind:'eruption',x:0,y:0,r:50,life:.01,max:1,damage:280}];g.step(.02);assert.equal(g.mode,'down');checks.push('already-cast ground strikes remain dangerous during a freeze');
const losses=[];for(const setup of [0,1,2]){g=arena();g.skills=setup?{guard:3}:{};g.evolved=setup===2?['aegis']:[];g.player.hp=1000;g.shield=0;g.hurt(280);losses.push(1000-g.player.hp);}assert(losses[0]>losses[1]&&losses[1]>losses[2]);assert(Math.abs(losses[2]-128.8)<1e-6);g=arena();g.skills={aegis:8,guard:3};g.evolved=['aegis'];g.fire('aegis');g.player.hp=500;g.hurt(280);assert(g.player.hp>400);checks.push('standalone Stone oath and evolved aegis stack reduction; shield absorbs remaining damage with no boss-dependent hit cap');
const pilots=[];
const builds=[['chrono','beam','solar','bolt','scythe','flame'],['aegis','blood','beam','solar','bolt','scythe'],['beam','solar','bolt','scythe','flame','chain']];
for(const [index,ids] of builds.entries()){
 const s=ensureProgression(freshSave());s.meta=Object.fromEntries(META.map(m=>[m.id,m.max]));s.inventory['flame:6']={level:10};s.equipment.ranger='flame:6';for(const id of ids)s.spellcraft[id]={power:10,haste:5};assert(validProgression(s));g=arena(s);g.skills=Object.fromEntries([...ids.map(id=>[id,8]),...['guard','regen','haste','reach','power','agility'].map(id=>[id,3])]);g.evolved=ids;for(const id of ids)assert(g.rank(WEAPONS.find(w=>w.id===id).pair)>=2);g.relics={ascend_power:20,ascend_regen:10,ascend_vigor:12};g.player.hp=g.maxHp();e=g.enemies[0];let ticks=0,hits=0;g.onEvent=type=>{if(type==='hurt')hits++;};while(!g.reaperDefeated&&g.mode==='playing'&&ticks<54000){const p=g.player,d=Math.hypot(e.x-p.x,e.y-p.y)||1,radial=d<170?-.9:d>240?.7:0;let dx=(e.x-p.x)/d*radial-(e.y-p.y)/d,dy=(e.y-p.y)/d*radial+(e.x-p.x)/d;for(const h of g.hazards)if(h.kind==='eruption'&&Math.hypot(h.x-p.x,h.y-p.y)<h.r+55){dx+=(p.x-h.x)/50;dy+=(p.y-h.y)/50;}const length=Math.hypot(dx,dy)||1;if(d<80)g.dash({x:dx/length,y:dy/length});g.step(1/60,{x:dx/length,y:dy/length});if(g.mode==='levelup')g.choose(g.choices[0]);if(g.mode==='down'&&g.revives)g.revive();ticks++;}
 const result={build:['Freeze and damage','Shield and sustain','Damage and mobility'][index],seconds:Math.round(ticks/60),won:g.reaperDefeated,hits,health:Math.round(g.player.hp),bossHealth:Math.round(e.hp)};pilots.push(result);assert(g.reaperDefeated,JSON.stringify(result));assert(ticks>30*60);
}
checks.push('three unrestricted six-weapon endgame builds win through actual combat, including one without freezing or aegis');
console.log(JSON.stringify({checks,damageTaken:losses,pilots},null,2));
