import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {CombatFoley,SPELL_SOUNDS} from '../foley.js';import {WEAPONS,freshSave} from '../data.js';import {Game} from '../engine.js';import {context} from './audio-mocks.mjs';
const manifest=JSON.parse(readFileSync(new URL('../audio/sfx/foley.json',import.meta.url)));for(const clip of Object.values(manifest.clips))for(const v of clip.variants){assert(v.offset>=0&&v.duration>0);assert(v.offset+v.duration<=manifest.banks[clip.bank].seconds+.05);}
for(const w of WEAPONS){assert(SPELL_SOUNDS[w.id],w.id);for(const cue of SPELL_SOUNDS[w.id])assert(manifest.clips[cue]);}
const ctx=context(),sfx=new CombatFoley(ctx,{fetcher:async url=>({ok:true,json:async()=>manifest,arrayBuffer:async()=>new ArrayBuffer(1)})});await sfx.load();assert.equal(sfx.state,'ready');
for(let i=0;i<100;i++)sfx.cue('impact-fire');assert.equal(sfx.voices.size,24);assert.equal(sfx.dropped,76);sfx.cue('hit-hammer-body',{priority:5});assert.equal(sfx.voices.size,24);assert([...sfx.voices].some(v=>v.priority===5));sfx.setEnabled(false);assert.equal(sfx.voices.size,0);assert.equal(sfx.cue('cast-frost'),false);sfx.setEnabled(true);
for(let i=0;i<100;i++)sfx.event('cast',{weapon:'frost'});assert.equal(sfx.voices.size,1);ctx.currentTime+=1;sfx.event('hurt');assert.equal(sfx.voices.size,2);
const events=[],g=new Game(freshSave(),(type,data)=>events.push([type,data]));g.spawn('crawler');g.enemies[0].x=50;g.enemies[0].y=0;g.fire('bolt');assert(events.some(([t,d])=>t==='cast'&&d.weapon==='bolt'));g.hit(g.enemies[0],5,'frost');assert(events.some(([t,d])=>t==='impact'&&d.weapon==='frost'));
const failed=new CombatFoley(context(),{fetcher:async()=>{throw Error('offline');}});await failed.load();assert.equal(failed.state,'unavailable');assert.equal(failed.cue('cast-frost'),false);
console.log('Recorded effects: every weapon mapped, sprite bounds verified, combat events, bounded polyphony, priority, mute and offline failure passed');

ctx.currentTime+=2;sfx.stop();const hazard={kind:'eruption',x:10,y:0};sfx.update({mode:'playing',player:{x:0,y:0},region:'hollow',hazards:[hazard,{kind:'meteor',x:0,y:0}]});const dangerCount=sfx.played;assert.equal(sfx.voices.size,1);sfx.update({mode:'playing',player:{x:0,y:0},region:'hollow',hazards:[hazard]});assert.equal(sfx.played,dangerCount,'one warning per hostile telegraph; player effects do not trigger enemy cues');
