import assert from 'node:assert/strict';
import {Game} from '../engine.js';
import {freshSave,WEAPONS,PASSIVES,META,costOf} from '../data.js';
const s=freshSave();const g=new Game(s);g.rng=420;let checks=[];
let x=g.player.x;g.step(.05,{x:1,y:0});assert(g.player.x>x);checks.push('movement');
let t=g.time;g.mode='paused';g.step(.05,{x:1,y:0});assert.equal(g.time,t);checks.push('pause freezes simulation');g.mode='playing';
assert(g.dash({x:1,y:0}));assert(!g.dash());assert(g.invuln>0);checks.push('dash and cooldown');
for(const w of WEAPONS){let q=new Game(s);q.skills={[w.id]:7,[w.pair]:2};q.mode='levelup';q.choices=[w.id];assert(q.choose(w.id));assert.equal(q.rank(w.id),8);assert(!q.evolved.includes(w.id));q.openChest({gold:100,rewards:3,boss:true});assert(q.evolved.includes(w.id));q.closeChest();let e=q.spawn('brute');e.x=q.player.x+(w.id==='orbit'?90*q.area():65);e.y=q.player.y;e.speed=0;e.hp=5000;e.maxHp=5000;for(let i=0;i<300;i++){q.step(1/60);if(q.mode==='levelup')q.choose(q.choices[0]);}assert(q.damageDone[w.id]>0,`${w.id} damage`);}checks.push('all 16 weapons deal damage and evolve');
let cap=new Game(s);cap.skills=Object.fromEntries([...WEAPONS.slice(0,6),...PASSIVES.slice(0,6)].map(a=>[a.id,1]));for(let i=0;i<100;i++)for(const id of cap.offers())assert(cap.skills[id]);checks.push('6 weapon / 6 skill slot caps');
let rest=new Game(s);rest.player.hp=42;rest.time=92;rest.gold=27;rest.skills={bolt:3,power:2};rest.mode='levelup';rest.choices=['bolt','power','frost'];let rr=new Game(s,()=>{},rest.snapshot());assert.equal(rr.player.hp,42);assert.equal(rr.time,92);assert.equal(rr.gold,27);assert.deepEqual(rr.skills,rest.skills);assert.equal(rr.mode,'levelup');assert.deepEqual(rr.choices,rest.choices);checks.push('snapshot round trip with pending upgrade');
rest.mode='down';rest.player.hp=0;assert(rest.revive());assert.equal(rest.player.hp,60);assert.equal(rest.revives,0);rest.mode='down';assert(!rest.revive());checks.push('one free revive');
let died=new Game(s);died.invuln=0;died.player.hp=1;let enemy=died.spawn('brute');enemy.x=0;enemy.y=0;died.step(1/60);assert.equal(died.mode,'down');checks.push('contact damage and death');
let endless=new Game(s);endless.time=599.99;endless.step(.05);assert.equal(endless.mode,'playing');assert(endless.time>600);endless.time=1799.99;endless.step(.05);assert.equal(endless.mode,'playing');assert(endless.dawnReached);let won=false;endless.onEvent=(type,data)=>{if(type==='end')won=data.victory};endless.end(false);assert(won);checks.push('10-minute boundary continues; 30-minute dawn continues and banks a win');
let scaling=new Game(s);const stages=[0,5,10,20,30,60].map(m=>{scaling.time=m*60;return scaling.difficulty()});for(let i=1;i<stages.length;i++){assert(stages[i].health>stages[i-1].health);assert(stages[i].cap>=stages[i-1].cap);assert(stages[i].interval<=stages[i-1].interval);}checks.push('horde health, population and spawn pressure scale through 60 minutes');
let chestGame=new Game(s);chestGame.skills={bolt:7,power:2,orbit:4};let boss=chestGame.spawn('brute',false,true);boss.x=0;boss.y=0;chestGame.hit(boss,1e8,'bolt');let chest=chestGame.pickups.find(p=>p.kind==='chest');assert(chest);assert([3,5].includes(chest.rewards));chestGame.step(.01);assert.equal(chestGame.mode,'chest');assert(chestGame.chestReward.gold>=100);const gold=chestGame.gold,skillState={...chestGame.skills};let restoredChest=new Game(s,()=>{},chestGame.snapshot());assert.equal(restoredChest.mode,'chest');assert.deepEqual(restoredChest.skills,skillState);assert.equal(restoredChest.gold,gold);restoredChest.closeChest();restoredChest.step(.01);assert.equal(restoredChest.gold,gold);checks.push('boss drops chest; multiple rewards persist without duplicate collection');
let maxed=new Game(s);maxed.skills=Object.fromEntries([...WEAPONS.slice(0,6).map(w=>[w.id,8]),...PASSIVES.slice(0,6).map(p=>[p.id,3])]);maxed.evolved=WEAPONS.slice(0,6).map(w=>w.id);maxed.openChest({gold:100,rewards:5,boss:true});assert.equal(maxed.chestReward.gold,100);assert(maxed.chestReward.rewards.every(r=>r.ascension||r.union));assert.equal(Object.values(maxed.relics).reduce((a,b)=>a+b,0)+maxed.unions.length,5);assert.equal(maxed.chestReward.rewards.length,5);assert(Object.values(maxed.skills).every(n=>n<=8));checks.push('fully upgraded chests grant unions and Ascensions instead of wasted upgrades');
let legacy=new Game(s);legacy.skills={bolt:5,power:2};legacy.evolved=['bolt'];let migrated=new Game(s,()=>{},legacy.snapshot());assert.equal(migrated.rank('bolt'),8);assert(migrated.evolved.includes('bolt'));checks.push('existing evolved weapons retain evolution and migrate to rank 8');
let hour=new Game(s);hour.time=3599.99;hour.nextBoss=3600;hour.step(.05);assert(hour.time>3600);assert.equal(hour.mode,'playing');assert(hour.enemies.some(e=>e.boss));assert(hour.nextBoss>3600);let resumedHour=new Game(s,()=>{},hour.snapshot());assert(resumedHour.time>3600);checks.push('one-hour run restores and recurring boss schedule continues');
maxed.closeChest();maxed.skills.dagger=8;maxed.evolved.push('dagger');assert(maxed.offers().every(id=>id.startsWith('ascend_')));maxed.choices=[];maxed.xp=maxed.need;const maxGold=maxed.gold;maxed.step(.01);assert.equal(maxed.mode,'levelup');assert(maxed.choices.every(id=>id.startsWith('ascend_')));checks.push('max rank never offered again; maxed levels offer Ascensions');
let oldBalance=new Game(s);oldBalance.balanceVersion=4;oldBalance.need=8;oldBalance.xp=4;oldBalance.gold=123;oldBalance.enemies=[{...oldBalance.spawn('crawler'),speed:30}];let balanced=new Game(s,()=>{},oldBalance.snapshot());assert.equal(balanced.need,18);assert.equal(balanced.xp,9);assert.equal(balanced.gold,123);assert.equal(balanced.enemies[0].speed,52);checks.push('old saves retain XP fraction and gold while enemy speeds migrate');
let idleStrike=new Game(s);idleStrike.invuln=0;idleStrike.hazards=[{kind:'eruption',x:0,y:0,r:52,life:1.1,max:1.1,damage:40}];let dodging=new Game(s,()=>{},idleStrike.snapshot());dodging.mode='playing';for(let i=0;i<70;i++){idleStrike.step(1/60);dodging.step(1/60,{x:1,y:0});}assert(idleStrike.player.hp<100);assert.equal(dodging.player.hp,100);checks.push('telegraphed ground strike damages idle player and can be escaped');
let distantXP=new Game(s);distantXP.time=100;distantXP.gems=[{x:500,y:0,value:10,born:0}];distantXP.step(.01);assert.equal(distantXP.gems[0].pull,undefined);checks.push('old distant XP no longer auto-collects while standing still');
// Play complete expeditions using a deterministic collection / avoidance bot.
function simulate(seed,upgraded=false){let state=freshSave();if(upgraded)state.meta={might:3,health:3,armor:2,regen:2,magnet:3,haste:2};let q=new Game(state);q.rng=seed;let frames=0,firstLevel=0,choices=0,usedRevive=false;let begin=performance.now();while(q.mode!=='ended'&&frames<110000&&q.time<1801){if(q.mode==='chest')q.closeChest();if(q.mode==='down'){if(q.revives){q.revive();usedRevive=true;}else break;}if(q.mode==='levelup'){if(!firstLevel)firstLevel=q.time;const pref=['bolt','power','orbit','reach','chain','haste','nova','vitality'];let option=pref.find(id=>q.choices.includes(id));q.choose(option||q.choices[0]);choices++;}
 let dx=0,dy=0,p=q.player,target=null,dist=Infinity;const nearbyChest=q.pickups.filter(p=>p.kind==='chest').sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];for(const gem of (nearbyChest?[nearbyChest]:q.gems)){let d=Math.hypot(gem.x-p.x,gem.y-p.y);if(d<dist){target=gem;dist=d;}}if(target){dx=(target.x-p.x)/(dist||1);dy=(target.y-p.y)/(dist||1);}else{dx=Math.cos(q.time*.11);dy=Math.sin(q.time*.11);}for(const e of q.enemies){const d=Math.hypot(e.x-p.x,e.y-p.y)||1;if(d<100){const avoid=(100-d)/45;dx+=(p.x-e.x)/d*avoid;dy+=(p.y-e.y)/d*avoid;if(d<38)q.dash({x:dx,y:dy});}}
 const n=Math.hypot(dx,dy)||1;q.step(1/60,{x:dx/n,y:dy/n});frames++;
 }
 const r={seed,upgraded,time:Math.round(q.time),level:q.level,kills:q.kills,gold:Math.floor(q.gold),evolved:q.evolved,firstLevel:Math.round(firstLevel),revive:usedRevive,mode:q.mode,chests:q.chestsOpened,bosses:q.bossesKilled,elapsedMs:Math.round(performance.now()-begin),enemies:q.enemies.length,gems:q.gems.length};assert(q.gems.length<=450);assert(q.enemies.length<=610);assert(q.gold>=10);return r;}
const runs=[simulate(42),simulate(312),simulate(812,true)];
console.log(JSON.stringify({checks,runs},null,2));
