import assert from 'node:assert/strict';
import {Game} from '../engine.js';
import {freshSave} from '../data.js';
import {FAMILIES,gearItem,gearStats,gearPerks,ascendGear} from '../gear.js';
import {GODLY,validGodly} from '../godly.js';
const checks=[];
function arena(id,tier=6,level=0){const s=freshSave();s.inventory[id+':'+tier]={level};s.equipment.ranger=id+':'+tier;const g=new Game(s);g.skills={};g.random=()=>.99;g.invuln=999;g.nextBoss=g.nextElite=g.nextCache=g.nextHeal=g.nextWorldStrike=g.nextChallengeStrike=g.nextObjective=g.nextDiscoveryScan=g.spawnClock=1e9;g.lateStarted=true;return g;}
function enemy(g,x=80,y=0,boss=false,hp=1e7){const e=g.spawn('brute',false,boss);e.x=x;e.y=y;e.hp=e.maxHp=hp;e.speed=0;e.attack=999;return e;}
function advance(g,seconds){for(let i=0;i<Math.ceil(seconds/.05);i++){g.step(.05);if(g.mode==='levelup'){g.choices=[];g.mode='playing';}}}
function hit(g,e,n=1){const hp=e.hp;g.hit(e,n,'bolt');return hp-e.hp;}
for(const f of FAMILIES){const low=gearStats(gearItem(f.id+':5')),high=gearStats(gearItem(f.id+':6'));assert(!low.godly);assert.equal(high.godly,f.id);assert(!high.revive);const perks=gearPerks(gearItem(f.id+':5'),true);assert.equal(perks.length,7);assert(perks[6].locked);assert(perks[6].text.includes(GODLY[f.id].name));assert(!perks[6].text.includes('revive'));const g=arena(f.id);assert.equal(g.revives,1);assert(validGodly(g.snapshot()));}
assert.equal(new Set(Object.values(GODLY).map(p=>p.name)).size,16);checks.push('16 unique previewable seventh perks; no new gear revives; lower tiers unchanged');
let g=arena('bolt'),e=enemy(g),behind=enemy(g,300);hit(g,e);assert(behind.hp<behind.maxHp);let d=g.damageDone.godly;hit(g,e);assert.equal(g.damageDone.godly,d);g.time=5;hit(g,e);assert(g.damageDone.godly>d);checks.push('Heavenpiercer penetrates multiple enemies and respects cooldown');
g=arena('orbit');e=enemy(g);g.shield=0;let hp=g.player.hp;g.hurt(40);assert.equal(hp-g.player.hp,20);assert(e.hp<e.maxHp);hp=g.player.hp;g.hurt(40);assert.equal(hp-g.player.hp,40);checks.push('Lunar riposte halves one hit and retaliates; subsequent hits are not halved');
g=arena('chain');e=enemy(g);for(let i=0;i<8;i++)enemy(g,90+i*10);for(let i=0;i<5;i++)hit(g,e);assert(!g.damageDone.godly);hit(g,e);assert(g.damageDone.godly>2000);assert.equal(g.enemies.filter(e=>e.hp<e.maxHp).length,8);checks.push('Storm sovereign triggers on sixth hit with eight-target cap');
g=arena('nova');e=enemy(g);g.shield=0;hp=g.player.hp;g.hurt(10);assert.equal(g.player.hp,hp);assert(g.shield>0);assert(e.hp<e.maxHp);g.shield=300;g.wardClock=19.99;advance(g,.05);assert.equal(g.shield,300);checks.push('Worldbreaker creates shield before absorption, deals area damage, and ward recharge cannot overwrite a larger shield');
g=arena('frost');e=enemy(g);let boss=enemy(g,180,0,true);advance(g,.05);assert(e.frozenUntil-g.time>3.9);assert(boss.frozenUntil-g.time<=1.61);let x=e.x;advance(g,1);assert.equal(e.x,x);checks.push('Absolute winter actually freezes normal enemies and bosses with different duration');
g=arena('flame');e=enemy(g);hit(g,e);assert.equal(g.divine.fires.length,3);advance(g,1.1);assert(g.damageDone.godly>900);const fireSave=g.snapshot();let restored=new Game(freshSave(),()=>{},fireSave);assert.deepEqual(restored.divine,fireSave.divine);checks.push('Dragonwake pools damage repeatedly and survive save/resume');
g=arena('dagger');e=enemy(g);let normal=hit(g,e,100);assert(g.dash({x:1,y:0}));assert(g.dashCd<2);assert(hit(g,e,100)>normal*2);g.time=3.1;assert.equal(hit(g,e,100),normal);checks.push('Ghoststep guarantees criticals during its window and expires');
g=arena('meteor');e=enemy(g);hit(g,e);assert.equal(g.hazards.length,3);advance(g,1.4);assert(g.damageDone.godly>1500);checks.push('Astral bombardment produces three damaging delayed impacts');
g=arena('spear');e=enemy(g);boss=enemy(g,180,0,true);normal=hit(g,e,100);assert(Math.abs(hit(g,boss,100)/normal-1.8)<1e-6);checks.push('Sovereign slayer increases actual boss damage by 80%');
g=arena('scythe');e=enemy(g,80,0,false,1000);e.hp=249;hit(g,e);assert(e.hp<=0);assert.equal(g.kills,1);hit(g,e);assert.equal(g.kills,1);boss=enemy(g,100,0,true,1000);boss.hp=249;hit(g,boss);assert(boss.hp>0);checks.push('Final harvest executes ordinary enemies exactly once and never executes bosses');
g=arena('mine');e=enemy(g);g.dash({x:1,y:0});assert.equal(g.hazards.length,5);advance(g,1);assert(g.damageDone.godly>0);checks.push('Siege runner lays five functional armed mines');
g=arena('venom');e=enemy(g);for(let i=0;i<20;i++)hit(g,e);assert.equal(g.divine.poisons[0].stacks,5);advance(g,1.1);assert(g.damageDone.godly>=450);for(let i=0;i<30;i++)hit(g,enemy(g,100+i));assert.equal(g.divine.poisons.length,16);advance(g,4.2);assert.equal(g.divine.poisons.length,0);checks.push('Blight stacks, damages, expires and caps infected targets');
g=arena('beam');e=enemy(g);for(let i=0;i<12;i++)hit(g,e);normal=hit(g,e,100);g.time=5;assert(Math.abs(normal/hit(g,e,100)-2)<1e-6);checks.push('Prismatic overload doubles real damage then expires');
g=arena('wisp');e=enemy(g);advance(g,1);assert(g.damageDone.godly>0);assert.equal(Object.keys(g.skills).length,0);checks.push('Spirit court fires homing attacks with no spell slot');
g=arena('axe');e=enemy(g,200);normal=hit(g,e,100);for(let i=0;i<12;i++)hit(g,enemy(g,100,0,false,1),100);assert(g.divine.activeUntil>g.time);assert(Math.abs(hit(g,e,100)/normal-1.7)<1e-6);checks.push('Endless conquest triggers after twelve kills and boosts real damage');
g=arena('tide');e=enemy(g);g.hazards=[{kind:'shot',x:100,y:0,life:3},{kind:'eruption',x:100,y:0,life:3},{kind:'shot',x:800,y:0,life:3}];g.dash({x:1,y:0});assert.equal(g.hazards.filter(h=>h.kind==='shot').length,1);assert(g.hazards.some(h=>h.kind==='eruption'));advance(g,.5);assert(g.damageDone.godly>0);checks.push('Ocean dominion clears nearby shots, preserves ground tells, and deals wave damage');
// New powers apply automatically to already-owned Godly gear. Existing run state is preserved.
for(const f of FAMILIES){g=arena(f.id);e=enemy(g);hit(g,e);g.dash({x:1,y:0});advance(g,.1);const snap=g.snapshot();assert(validGodly(snap));restored=new Game(freshSave(),()=>{},snap);assert.deepEqual(restored.divine,snap.divine);assert.equal(restored.revives,snap.revives);assert.equal(restored.player.hp,snap.player.hp);assert.equal(restored.gear.id,snap.gear.id);assert.equal(restored.gearBonuses.godly,f.id);const legacy=JSON.parse(JSON.stringify(snap));delete legacy.divine;legacy.revives=2;legacy.gearBonuses.revive=1;restored=new Game(freshSave(),()=>{},legacy);assert.equal(restored.revives,2);assert.equal(restored.gearBonuses.godly,f.id);assert(validGodly(restored.snapshot()));}
let s=freshSave();s.gold=60000;s.inventory['bolt:5']={level:7};s.equipment.ranger='bolt:5';assert.equal(ascendGear(s,'bolt:5'),'bolt:6');assert.equal(s.gold,5000);assert.equal(s.inventory['bolt:6'].level,7);assert.equal(new Game(s).gearBonuses.godly,'bolt');assert(!ascendGear(s,'bolt:6'));checks.push('Ascension costs, temper level, equipped reference, legacy remaining revives and all power timers preserved');
assert(!validGodly({divine:{...g.divine,readyAt:NaN}}));assert(!validGodly({divine:{...g.divine,poisons:Array(17).fill({})}}));
// Ability damage grows with temper; unlimited hits cannot recurse or grow entity counts.
let low=arena('bolt',6,0),high=arena('bolt',6,10);hit(low,enemy(low));hit(high,enemy(high));assert(high.damageDone.godly>low.damageDone.godly*1.8);
for(const f of FAMILIES){g=arena(f.id);e=enemy(g);for(let i=0;i<1000;i++)hit(g,e);assert(g.hazards.length<=5);assert(g.divine.fires.length<=3);assert(g.divine.poisons.length<=16);assert(g.effects.length<=80);assert(Number.isFinite(e.hp));}
console.log(JSON.stringify(checks,null,2));
