import assert from 'node:assert/strict';
import {Game} from '../engine.js';
import {freshSave,WEAPONS,PASSIVES,RELICS,META} from '../data.js';
import {ensureRegions,recordRegion,resolveTerrain,lavaAt,riftAt,safePoint,obstacles} from '../world.js';
import {spawnOverlord,attackOverlord,stepObjective,stepWorld} from '../expedition.js';
const checks=[];
const full=(region='ashwood')=>{const s=freshSave();s.region=region;s.meta=Object.fromEntries(META.map(m=>[m.id,m.max]));const g=new Game(s);g.skills=Object.fromEntries([...WEAPONS.slice(0,6).map(w=>[w.id,8]),...PASSIVES.slice(0,6).map(w=>[w.id,3])]);g.evolved=WEAPONS.slice(0,6).map(w=>w.id);g.time=600;g.waveMinute=10;g.player.hp=g.maxHp();g.rng=42;return g;};
const legacy=freshSave();legacy.stats.bestTime=610;legacy.gold=777;delete legacy.regionBest;delete legacy.unlockedRegions;ensureRegions(legacy);assert(legacy.unlockedRegions.includes('hollow'));assert(!legacy.unlockedRegions.includes('cinder'));assert.equal(legacy.gold,777);const oldWins=freshSave();oldWins.stats.wins=3;ensureRegions(oldWins);assert(oldWins.unlockedRegions.includes('cinder'));
const unlock=freshSave(),q=new Game(unlock);q.time=599.99;recordRegion(unlock,q);assert.equal(unlock.unlockedRegions.length,1);q.time=600;assert.deepEqual(recordRegion(unlock,q),['hollow']);q.region='hollow';assert.deepEqual(recordRegion(unlock,q),['cinder']);assert.deepEqual(recordRegion(unlock,q),[]);const resume=freshSave();q.time=678;resume.run=q.snapshot();ensureRegions(resume);assert(resume.unlockedRegions.includes('cinder'));checks.push('10:00 region unlocks save during runs; legacy best times and old unlocks migrate without gold changes');
const maxed=full();for(let i=0;i<200;i++){const choices=maxed.offers();assert.equal(choices.length,3);assert(choices.every(id=>RELICS.some(r=>r.id===id)));maxed.mode='levelup';assert(maxed.choose(choices[0]));}assert.equal(Object.values(maxed.relics).reduce((a,b)=>a+b,0),200);assert(Object.values(maxed.skills).every(n=>n<=8));for(let i=0;i<100;i++)maxed.upgrade('ascend_haste');assert.equal(maxed.a('haste'),15);assert(maxed.haste('bolt')>=.3);const before=maxed.damage();maxed.upgrade('ascend_power');assert(maxed.damage()>before);const hp=maxed.maxHp();maxed.upgrade('ascend_vigor');assert.equal(maxed.maxHp(),hp+15);const partial=new Game(freshSave());partial.time=600;for(let i=0;i<20;i++)assert(partial.offers().some(id=>id.startsWith('ascend_')));checks.push('Finished builds still offer three upgrades after 200 Ascensions; rank-eight weapons and haste caps remain intact');
for(const region of ['ashwood','hollow','cinder']){const g=full(region);stepObjective(g);assert.equal(g.objective.nodes.length,3);for(const n of g.objective.nodes){assert(Math.hypot(n.x-g.player.x,n.y-g.player.y)>180);if(region==='cinder')assert(!lavaAt(n.x,n.y));if(region==='hollow')for(const b of obstacles(region,n.x,n.y))assert(!(n.x>b.x-30&&n.x<b.x+b.w+30&&n.y>b.y-30&&n.y<b.y+b.h+30));}
 const restored=new Game(freshSave(),()=>{},g.snapshot());assert.deepEqual(restored.objective,g.objective);restored.mode='playing';const gold=restored.gold;for(const n of restored.objective.nodes){restored.player.x=n.x;restored.player.y=n.y;stepObjective(restored);}assert.equal(restored.mode,'levelup');assert(restored.objectiveChoice);assert.equal(restored.objectivesCompleted,1);assert(restored.gold>gold+179);const earned=restored.gold;stepObjective(restored);assert.equal(restored.gold,earned);const paused=restored.time;restored.step(.05);assert.equal(restored.time,paused);restored.choose(restored.choices[0]);assert(!restored.objectiveChoice);const rewardRestore=new Game(freshSave(),()=>{},restored.snapshot());assert.equal(rewardRestore.objectivesCompleted,1);}
const expired=full();stepObjective(expired);expired.time=expired.objective.expires;stepObjective(expired);assert.equal(expired.objective,null);assert.equal(expired.objectivesCompleted,0);checks.push('Reachable three-shrine hunts survive reload, reward exactly once, pause with choices, and expire without damage');
for(const region of ['ashwood','hollow','cinder']){const g=full(region),boss=spawnOverlord(g);assert(boss.maxHp>=95000);boss.x=150;boss.y=0;g.nextElite=g.nextCache=g.nextHeal=1e9;g.spawnClock=1e9;g.invuln=1e9;for(let i=0;i<120;i++)g.step(1/60);assert(boss.hp>boss.maxHp*.65,'Overlord should survive opening burst');boss.hp=boss.maxHp*.45;g.hazards=[];attackOverlord(g,boss);assert(boss.fury);assert.equal(g.hazards.length,region==='hollow'?8:5);assert(g.hazards.every(h=>h.max>=1.6&&h.kind==='eruption'));g.hit(boss,1e9,'bolt');const chest=g.pickups.find(p=>p.kind==='chest');assert.equal(chest.rewards,5);assert(chest.gold>=550);g.mode='playing';g.openChest(chest);assert.equal(g.chestReward.rewards.length,5);assert(g.chestReward.gear);}
checks.push('Region Overlords survive evolved opening bursts, enrage below half health, telegraph attacks, and drop five upgrades plus gear');
const dodge=full(),idle=full();for(const g of [dodge,idle]){g.enemies=[];g.spawnClock=1e9;g.nextElite=g.nextBoss=g.nextCache=g.nextHeal=1e9;g.lateStarted=true;g.nextWorldStrike=600;g.invuln=0;g.player.hp=g.maxHp();}for(let i=0;i<120;i++){idle.step(1/60);dodge.step(1/60,{x:1,y:0});}assert(dodge.player.hp>idle.player.hp+40);checks.push('Nightfall ground attacks punish standing still and can be dodged without dashing');
const rock={x:175,y:175};resolveTerrain('hollow',rock);assert(rock.y<=144||rock.y>=206||rock.x<=116||rock.x>=234);assert(lavaAt(320,160));assert(!lavaAt(320,0));const hot=full('cinder');hot.player={x:320,y:160,hp:100};hot.invuln=0;stepWorld(hot);assert(hot.player.hp<100);const bridge=full('cinder');bridge.player={x:320,y:0,hp:100};bridge.invuln=0;stepWorld(bridge);assert.equal(bridge.player.hp,100);let activeTime=0;while(!riftAt(280,280,activeTime).active)activeTime++;const rift=full('hollow');rift.time=activeTime;rift.player={x:280,y:280,hp:100};rift.invuln=0;stepWorld(rift);assert(rift.player.hp<100);checks.push('Hollow walls block movement; active rifts and lava hurt; bridges remain safe');
const late=full();for(const [minute,id]of [[10,'bulwark'],[12,'stalker'],[14,'siege'],[18,'harbinger']]){late.time=minute*60;const types=new Set(Array.from({length:2000},()=>late.enemyType()));assert(types.has(id));late.time=(minute-.01)*60;const earlier=new Set(Array.from({length:2000},()=>late.enemyType()));assert(!earlier.has(id));}late.time=599.99;const a=late.difficulty();late.time=600.01;const b=late.difficulty();assert(Math.abs(a.count-b.count)<.001);assert(Math.abs(a.health-b.health)<.01);checks.push('Four durable enemy types arrive over time; spawn pressure and health remain continuous at ten minutes');
console.log(JSON.stringify({checks},null,2));
