import assert from 'node:assert/strict';
import fs from 'node:fs';import vm from 'node:vm';
import {Game} from '../engine.js';
import {freshSave,WEAPONS,PASSIVES,HEROES,REGIONS,META,MILESTONES,RELICS,ENEMIES,byId} from '../data.js';
import {UNIONS,readyUnion,mergeUnion,stepUnions,validUnionRun} from '../unions.js';
import {secretSites,stepSecrets,recordSecrets,validSecrets,buyTrade,equipCharm,SECRET_WEAPONS} from '../secrets.js';
import {safePoint,ensureRegions,isSafePoint} from '../world.js';
import {weaponUnlocked,ensureChronicle,recordChronicle,validChronicle} from '../chronicle.js';
import {validProgression,ensureProgression,gearItem} from '../gear.js';import {musicSettings} from '../music.js';import {WEAPON_FEATS} from '../relic-weapons.js';
function arena(s=freshSave()){const g=new Game(s);g.skills={};g.invuln=1e9;g.nextBoss=g.nextElite=g.nextCache=g.nextHeal=g.nextWorldStrike=g.nextObjective=g.nextDiscoveryScan=g.spawnClock=1e9;g.lateStarted=true;return g;}
for(const u of UNIONS){let g=arena();g.skills=Object.fromEntries(u.parts.map(id=>[id,8]));g.evolved=[...u.parts];g.skills.bolt=8;g.skills.nova=8;g.skills.spear=8;g.skills.axe=8;assert.equal(WEAPONS.filter(w=>g.rank(w.id)).length,6);g.skills[u.parts[1]]=7;assert(!readyUnion(g));g.skills[u.parts[1]]=8;assert(g.openChest({boss:true,rewards:1,gold:100}));assert.equal(g.chestReward.rewards[0].union,u.id);assert.equal(WEAPONS.filter(w=>g.rank(w.id)).length,5);assert(!g.rank(u.parts[1]));assert(!g.evolved.includes(u.parts[1]));assert(validUnionRun(g.snapshot()));g.closeChest();for(let i=0;i<100;i++)assert(g.offers().every(id=>!u.parts.includes(id)));g.choices=[];g.mode='playing';g.enemies=[];for(let i=0;i<20;i++){const e=g.spawn();const a=i*Math.PI/10;e.x=Math.cos(a)*100;e.y=Math.sin(a)*100;e.hp=e.maxHp=1e8;e.speed=0;}g.skills=Object.fromEntries([[u.parts[0],8]]);for(let i=0;i<80;i++)g.step(.05);assert(g.damageDone[u.parts[0]]>0,u.id+' causes real damage');assert(g.fusionEntities.length<=64);const saved=g.snapshot();g=new Game(freshSave(),()=>{},saved);assert.deepEqual(g.unions,[u.id]);assert.equal(g.rank(u.parts[1]),0);assert.deepEqual(g.fusionEntities,saved.fusionEntities);assert(validUnionRun(g.snapshot()));}
// Discoveries have no compass entry, unlock by proximity only, and cannot farm repeat rewards.
for(const region of REGIONS){const s=ensureChronicle(freshSave());s.region=region.id;const g=arena(s);const sites=secretSites(g);assert(!g.discoveries.length);for(const site of sites){const point=safePoint(g.region,site.x,site.y);assert(isSafePoint(region.id,point.x,point.y));g.player.x=point.x;g.player.y=point.y;stepSecrets(g,safePoint);recordSecrets(s,g);}assert(validSecrets(s));assert(buyTrade({...s,gold:1e5},'rerolls'));const gold=g.gold,rerolls=g.rerolls;stepSecrets(g,safePoint);recordSecrets(s,g);assert.equal(g.gold,gold);assert.equal(g.rerolls,rerolls);assert(s.unlockedRegions.includes('astral')||region.id==='astral');const resumed=new Game(s,()=>{},g.snapshot());assert.deepEqual(resumed.secretClaims,g.secretClaims);for(const w of SECRET_WEAPONS)assert.equal(weaponUnlocked(s,w.id),sites.some(site=>site.kind===w.id));}
const s=ensureChronicle(freshSave());s.gold=1e5;assert(!buyTrade(s,'glass'));s.secrets.found.push('ashwood:trader');assert(buyTrade(s,'glass'));const gold=s.gold;assert(!buyTrade(s,'glass'));assert.equal(s.gold,gold);assert(equipCharm(s,'glass'));const glass=new Game(s);assert.equal(glass.maxHp(),80);assert(glass.damage()>1.3);assert(buyTrade(s,'banish'));assert(buyTrade(s,'rerolls'));const g=new Game(s);assert.equal(g.rerolls,5);g.mode='levelup';g.offers();const banned=g.choices[0];assert(g.banish(banned));assert(!g.choices.includes(banned));assert.equal(g.banishes,0);const restored=new Game(s,()=>{},g.snapshot());assert(restored.banished.includes(banned));
assert(!validSecrets({secrets:{...s.secrets,purchases:{glass:20}}}));assert(!validUnionRun({...g.snapshot(),unions:['stormwheel']}));
// Exercise the actual import validator with all new state plus existing purchased progress.
const context={validSecrets,validUnionRun,WEAPON_FEATS,Game,freshSave,WEAPONS,PASSIVES,HEROES,REGIONS,META,MILESTONES,RELICS,ENEMIES,byId,validProgression,ensureProgression,gearItem,ensureRegions,ensureChronicle,validChronicle,musicSettings};vm.createContext(context);const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');vm.runInContext(app.slice(app.indexOf('function validateSave('),app.indexOf('function registerTools('))+';this.validate=validateSave;',context);s.inventory['flame:6']={level:10};s.spellcraft.bolt={power:10};s.run=g.snapshot();ensureRegions(s);const before=JSON.parse(JSON.stringify(s));context.validate(s);assert.deepEqual(JSON.parse(JSON.stringify(s)),before);
// All hostile damage sources use continuous post-ten-minute pressure; regen is trimmed exactly 15%.
const heal=arena();heal.meta.regen=5;heal.skills.regen=3;assert(Math.abs(heal.regenRate()-(.75+1.8)*.85)<1e-9);const losses=[];for(const time of [599,600,900,1200,1800]){heal.time=time;heal.player.hp=1000;heal.shield=0;heal.hurt(50);losses.push(1000-heal.player.hp);}assert.equal(losses[0],losses[1]);for(let i=2;i<losses.length;i++)assert(losses[i]>losses[i-1]);assert.equal(losses[3],82.5);assert.equal(losses[4],125);
const vampire=arena();vampire.gearBonuses.leech=.03;vampire.player.hp=1;vampire.leechBudget=vampire.leechRate();const enemy=vampire.spawn();enemy.hp=enemy.maxHp=1e12;for(let i=0;i<1000;i++)vampire.hit(enemy,10000,'bolt');assert(vampire.player.hp<=1+vampire.leechRate()+1e-8,'crowd damage cannot heal without a rate limit');
console.log('Six actual unions, ten maps of hidden discovery persistence, trader costs/charms/banishes, real save import, late damage and healing limits verified.');

const winter=arena();winter.skills={frost:8,meteor:8};mergeUnion(winter,readyUnion(winter));const frozen=winter.spawn();frozen.x=60;frozen.y=0;frozen.hp=1e6;stepUnions(winter,.01);assert(frozen.frozenUntil>winter.time);const location={x:frozen.x,y:frozen.y};winter.step(.05);assert.equal(frozen.x,location.x);assert.equal(frozen.y,location.y);
