import assert from 'node:assert/strict';
import {AdaptiveMusic,THEMES,scoreState,scoreNotes,musicSettings} from '../dist/music.js';
import {drawDanger,DANGER_RED} from '../dist/danger.js';
import {Game} from '../dist/engine.js';
import {freshSave} from '../dist/data.js';
const checks=[];
assert.deepEqual(musicSettings({sound:false}),{enabled:false,volume:.4});assert.deepEqual(musicSettings({sound:true}),{enabled:true,volume:.4});assert.deepEqual(musicSettings({sound:false,music:true,musicVolume:.7}),{enabled:true,volume:.7});assert.equal(musicSettings({musicVolume:NaN}).volume,.4);
checks.push('Legacy sound opt-out stays muted; music toggle and volume are independent with safe defaults');
const signatures=[];
for(const region of Object.keys(THEMES)){
 const opening=Array.from({length:64},(_,i)=>scoreNotes(region,0,i)),late=Array.from({length:64},(_,i)=>scoreNotes(region,1200,i));signatures.push(JSON.stringify(opening));assert(late.flat().length>opening.flat().length);assert(scoreState(region,1200).bpm>scoreState(region,0).bpm);assert.deepEqual(scoreState(region,1200),scoreState(region,1e6));
 for(const note of [...opening.flat(),...late.flat()]){assert(note.gain>0&&note.gain<=.2);assert(note.duration>0&&Number.isFinite(note.duration));}
}assert.equal(new Set(signatures).size,3);checks.push('Three distinct scores gain tempo and instruments with survival time; intensity remains bounded in endless runs');
class Param{constructor(){this.value=0;}setValueAtTime(v){assert(Number.isFinite(v));}exponentialRampToValueAtTime(v){assert(v>0&&Number.isFinite(v));}setTargetAtTime(v){assert(Number.isFinite(v));}cancelScheduledValues(){}}
class Node{constructor(){this.gain=this.frequency=this.threshold=this.ratio=new Param();}connect(){}disconnect(){this.disconnected=true;}start(t){assert(t>=0);}stop(t){assert(t>=0);this.stops=(this.stops||0)+1;}}
const ctx={currentTime:0,state:'running',sampleRate:8000,destination:{},createGain:()=>new Node(),createBiquadFilter:()=>new Node(),createDynamicsCompressor:()=>new Node(),createOscillator:()=>new Node(),createBufferSource:()=>new Node(),createBuffer:()=>({getChannelData:()=>new Float32Array(8000)})};
const music=new AdaptiveMusic(ctx);music.update('ashwood',0,true,{music:true,musicVolume:.4});assert(music.status().playing);assert(music.scheduled>0);const count=music.scheduled;music.update('ashwood',0,false,{music:true});assert(!music.running);const stopCounts=[...music.voices].map(v=>v.source.stops);for(let i=0;i<120;i++)music.update('ashwood',0,false,{music:true});assert.deepEqual([...music.voices].map(v=>v.source.stops),stopCounts);music.update('ashwood',0,true,{music:false});assert.equal(music.scheduled,count);music.update('hollow',600,true,{music:true});assert.equal(music.region,'hollow');music.update('hollow',600,true,{music:true},true);assert(!music.running);ctx.currentTime=500;music.update('cinder',1200,true,{music:true});assert(music.scheduled<count+100);assert(music.voices.size<=64);ctx.state='suspended';music.update('cinder',1200,true,{music:true});assert(!music.running);
checks.push('Scheduler pauses for menus, mute, background and suspended audio; switches regions and bounds voices/backlog');
const commands=[],canvas=new Proxy({save(){},restore(){},beginPath(){},arc(){},fill(){commands.push(['fill',this.fillStyle]);},stroke(){commands.push(['stroke',this.strokeStyle]);},strokeText(t){commands.push(['text',t]);},fillText(t){commands.push(['text',t]);}},{set(o,k,v){o[k]=v;return true;}});
const hazards=[{kind:'eruption',x:1,y:2,r:50,life:1,max:2,color:'#cdadff'},{kind:'shot',x:2,y:3,r:6,color:'#bea1ff'},{kind:'meteor',x:1,y:2,r:50,life:1,max:2}];const before=JSON.stringify(hazards);drawDanger(canvas,hazards,1);assert.equal(JSON.stringify(hazards),before);assert(commands.some(([kind,color])=>kind==='stroke'&&color===DANGER_RED));assert(commands.some(([kind,text])=>kind==='text'&&text==='!'));assert(!JSON.stringify(commands).includes('#cdadff'));const empty=[];canvas.fill=()=>empty.push(1);canvas.stroke=()=>empty.push(1);drawDanger(canvas,[hazards[2]],1);assert.equal(empty.length,0);
checks.push('Saved purple enemy warnings render red with ! markers, player meteors are excluded, and drawing never mutates saved hazards');
const save=freshSave();delete save.settings.music;delete save.settings.musicVolume;save.gold=852;save.inventory={'flame:5':{level:8}};save.equipment={ranger:'flame:5'};save.spellcraft={flame:{power:8,opening:2}};const g=new Game(save);g.time=843;g.player.hp=64;g.skills={bolt:8,flame:6};g.hazards=hazards;g.spawn('brute');const snap=g.snapshot();const r=new Game(save,()=>{},snap);assert.equal(r.time,g.time);assert.equal(r.player.hp,g.player.hp);assert.deepEqual(r.skills,g.skills);assert.deepEqual(r.enemies,g.enemies);assert.deepEqual(r.hazards,g.hazards);assert.deepEqual(r.gear,g.gear);assert.deepEqual(r.spellcraft,g.spellcraft);assert.equal(save.gold,852);
checks.push('Legacy upgraded run restores health, gear, spellcraft, enemies, pending attacks and gold without reset');
console.log(JSON.stringify({checks},null,2));
