import assert from 'node:assert/strict';
import {drawDanger,DANGER_RED} from '../danger.js';
import {Game} from '../engine.js';
import {freshSave} from '../data.js';
const checks=[];
const commands=[],canvas=new Proxy({save(){},restore(){},beginPath(){},arc(){},fill(){commands.push(['fill',this.fillStyle]);},stroke(){commands.push(['stroke',this.strokeStyle]);},strokeText(t){commands.push(['text',t]);},fillText(t){commands.push(['text',t]);}},{set(o,k,v){o[k]=v;return true;}});
const hazards=[{kind:'eruption',x:1,y:2,r:50,life:1,max:2,color:'#cdadff'},{kind:'shot',x:2,y:3,r:6,color:'#bea1ff'},{kind:'meteor',x:1,y:2,r:50,life:1,max:2}];const before=JSON.stringify(hazards);drawDanger(canvas,hazards,1);assert.equal(JSON.stringify(hazards),before);assert(commands.some(([kind,color])=>kind==='stroke'&&color===DANGER_RED));assert(commands.some(([kind,text])=>kind==='text'&&text==='!'));assert(!JSON.stringify(commands).includes('#cdadff'));const empty=[];canvas.fill=()=>empty.push(1);canvas.stroke=()=>empty.push(1);drawDanger(canvas,[hazards[2]],1);assert.equal(empty.length,0);
checks.push('Saved purple enemy warnings render red with ! markers, player meteors are excluded, and drawing never mutates saved hazards');
const save=freshSave();delete save.settings.music;delete save.settings.musicVolume;save.gold=852;save.inventory={'flame:5':{level:8}};save.equipment={ranger:'flame:5'};save.spellcraft={flame:{power:8,opening:2}};const g=new Game(save);g.time=843;g.player.hp=64;g.skills={bolt:8,flame:6};g.hazards=hazards;g.spawn('brute');const snap=g.snapshot();const r=new Game(save,()=>{},snap);assert.equal(r.time,g.time);assert.equal(r.player.hp,g.player.hp);assert.deepEqual(r.skills,g.skills);assert.deepEqual(r.enemies,g.enemies);assert.deepEqual(r.hazards,g.hazards);assert.deepEqual(r.gear,g.gear);assert.deepEqual(r.spellcraft,g.spellcraft);assert.equal(save.gold,852);
checks.push('Legacy upgraded run restores health, gear, spellcraft, enemies, pending attacks and gold without reset');
console.log(JSON.stringify({checks},null,2));
